# -*- coding: utf-8 -*-
"""External_cohort_Validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-w5kD0ViKNKEOkkyVQV0MqW_RQhiunb
"""

import pandas as pd
import numpy as np
from scipy.stats import mannwhitneyu
import seaborn as sns
import matplotlib.pyplot as plt

# ---------------------- Config ----------------------
external_biomarkers_path = "Filtered_biomarker_annotated.csv"
external_matrix_path     = "Matrix_PRJEB10878_combined_VF_ARG.csv"
external_meta_path       = "PRJEB10878_Metadata_Aligned.csv"
internal_matrix_path     = "combined_ARG_VFDB_final_DATA.csv"
internal_meta_path       = "Metadata_Aligned_VF_ARG_CountMatrix.csv"

external_stats_path      = "External_MannWhitney_Stats.csv"
internal_stats_path      = "Internal_MannWhitney_Stats.csv"
trend_comparison_path    = "Trend_Comparison.csv"
plot_path                = "Barplot_Trend_Comparison.png"

# ---------------------- Load Data ----------------------
external_biomarkers = pd.read_csv(external_biomarkers_path)
external_matrix     = pd.read_csv(external_matrix_path)
external_meta       = pd.read_csv(external_meta_path)

internal_matrix     = pd.read_csv(internal_matrix_path)
internal_meta       = pd.read_csv(internal_meta_path)

# ---------------------- External Prep ----------------------
external_matrix = external_matrix.rename(columns={external_matrix.columns[0]: "Sample_ID"})
features = external_biomarkers["Feature"].tolist()
present_ext = [f for f in features if f in external_matrix.columns]

external_df = external_matrix[["Sample_ID"] + present_ext] \
    .merge(external_meta[["Sample_ID", "Group"]], on="Sample_ID", how="inner")

external_long = external_df.melt(
    id_vars=["Sample_ID", "Group"],
    var_name="Biomarker",
    value_name="Value"
)

# ---------------------- Internal Prep ----------------------
# transpose so samples are rows
internal_t = internal_matrix.set_index(internal_matrix.columns[0]).T.reset_index().rename(columns={"index": "Sample_ID"})
internal_df = internal_t.merge(internal_meta[["Sample_ID", "Group"]], on="Sample_ID", how="inner")

internal_long = internal_df.melt(
    id_vars=["Sample_ID", "Group"],
    var_name="Biomarker",
    value_name="Value"
)
internal_long["Group"] = internal_long["Group"].replace({
    "Cancer": "Case", "Adenoma": "Case", "Healthy": "Control"
})

# ---------------------- Mann-Whitney ----------------------
def mann_whitney_test(df, group_col, value_col, case_label, control_label):
    results = []
    for biomarker, sub in df.groupby("Biomarker"):
        case_vals    = sub[sub[group_col] == case_label][value_col]
        control_vals = sub[sub[group_col] == control_label][value_col]
        if len(case_vals) >= 3 and len(control_vals) >= 3:
            stat, p = mannwhitneyu(case_vals, control_vals, alternative="two-sided")
            results.append((biomarker, stat, p))
    res = pd.DataFrame(results, columns=["Biomarker", "U-statistic", "P-value"])
    res["Adjusted P-value"] = res["P-value"].rank(method="first") / len(res) * 0.05
    return res

external_stats = mann_whitney_test(external_long, "Group", "Value", "CRC", "Control")
internal_filtered = internal_long[internal_long["Biomarker"].isin(features)]
internal_stats    = mann_whitney_test(internal_filtered, "Group", "Value", "Case", "Control")

external_stats.to_csv(external_stats_path, index=False)
internal_stats.to_csv(internal_stats_path, index=False)

# ---------------------- Trend Comparison ----------------------
ext_means = external_long.groupby(["Biomarker", "Group"])["Value"].mean().unstack()
int_means = internal_long.groupby(["Biomarker", "Group"])["Value"].mean().unstack()

common = [b for b in present_ext if b in int_means.index and b in ext_means.index]
comparison_df = pd.DataFrame(index=common)
comparison_df.index.name = "Biomarker"  # ensure reset_index gives correct column

comparison_df["External_CRC"]     = ext_means.loc[common, "CRC"]
comparison_df["External_Control"] = ext_means.loc[common, "Control"]
comparison_df["Internal_Case"]    = int_means.loc[common, "Case"]
comparison_df["Internal_Control"] = int_means.loc[common, "Control"]

comparison_df["External_Trend"]   = comparison_df["External_CRC"] - comparison_df["External_Control"]
comparison_df["Internal_Trend"]   = comparison_df["Internal_Case"] - comparison_df["Internal_Control"]
comparison_df["Consistent_Trend"] = (
    (comparison_df["External_Trend"] > 0) & (comparison_df["Internal_Trend"] > 0)
) | (
    (comparison_df["External_Trend"] < 0) & (comparison_df["Internal_Trend"] < 0)
)

comparison_df.to_csv(trend_comparison_path)

# ---------------------- Prepare bar_df ----------------------
bar_df = comparison_df.reset_index().melt(
    id_vars="Biomarker",
    value_vars=["External_Trend", "Internal_Trend"],
    var_name="Dataset",
    value_name="Trend"
)
bar_df["Dataset"] = bar_df["Dataset"].str.replace("_Trend", "", regex=False)

consistent = comparison_df[comparison_df["Consistent_Trend"]].index.tolist()

# ---------------------- Plot ----------------------
sns.set(style="whitegrid")
plt.figure(figsize=(7, 5))

ax = sns.barplot(
    data=bar_df,
    x="Trend",
    y="Biomarker",
    hue="Dataset",
    edgecolor="black",
    linewidth=2
)

for spine in ax.spines.values():
    spine.set_linewidth(2)
    spine.set_edgecolor("black")

plt.axvline(0, color="black", linestyle="--", linewidth=1.2)
plt.xlabel("Trend (Case/CRC − Control)", fontsize=11)
plt.ylabel("Genes", fontsize=11)
plt.legend(title="Dataset", loc="upper left", frameon=True)

for label in ax.get_yticklabels():
    gene = label.get_text()
    label.set_color("black" if gene in consistent else "black")

plt.tight_layout()
plt.savefig(plot_path, dpi=600)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib_venn import venn2
import seaborn as sns

# ---------------------- CONFIG ----------------------
# File paths (adjust if needed)
external_file = "External_MannWhitney_Stats.csv"
internal_file = "Internal_MannWhitney_Stats.csv"
output_file = "Merged_Significance_Comparison.csv"

# Significance threshold
alpha = 0.05

# ---------------------- LOAD DATA ----------------------
external = pd.read_csv(external_file)
internal = pd.read_csv(internal_file)

# Add significance flags
external["Significant_External"] = external["Adjusted P-value"] < alpha
internal["Significant_Internal"] = internal["Adjusted P-value"] < alpha

# Merge
merged = pd.merge(
    external[["Biomarker", "Significant_External"]],
    internal[["Biomarker", "Significant_Internal"]],
    on="Biomarker", how="outer"
).fillna(False)

# Add comparison label
def label_row(row):
    if row["Significant_External"] and row["Significant_Internal"]:
        return "Both"
    elif row["Significant_External"]:
        return "External Only"
    elif row["Significant_Internal"]:
        return "Internal Only"
    else:
        return "None"

merged["Significance_Status"] = merged.apply(label_row, axis=1)

# ---------------------- SAVE OUTPUT ----------------------
merged.to_csv(output_file, index=False)
print(f"Saved: {output_file}")

# ---------------------- SUMMARY COUNTS ----------------------
summary = merged["Significance_Status"].value_counts()
print("\nSummary:")
print(summary)

# ---------------------- OPTIONAL: BAR PLOT ----------------------
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))
ax = sns.countplot(
    data=merged,
    y="Significance_Status",
    order=["Both", "External Only", "Internal Only", "None"],
    edgecolor="black",    # outline color for bars
    linewidth=2           # thickness of bar borders
)

# Thicken and darken the outer plot border
for spine in ax.spines.values():
    spine.set_linewidth(2)
    spine.set_edgecolor("black")

# Axis labels and layout
plt.xlabel("Count")
plt.tight_layout()
plt.savefig("Significance_Comparison_Barplot.png")
plt.show()


# ---------------------- OPTIONAL: VENN DIAGRAM ----------------------
try:
    external_set = set(merged[merged["Significant_External"]]["Biomarker"])
    internal_set = set(merged[merged["Significant_Internal"]]["Biomarker"])

    plt.figure(figsize=(5, 5))
    venn2([external_set, internal_set], set_labels=("External", "Internal"))
    #plt.title("Overlap of Significant Biomarkers")
    plt.tight_layout()
    plt.savefig("Significance_Comparison_Venn.png")
    plt.show()
except ImportError:
    print("Install matplotlib-venn for Venn diagram: pip install matplotlib-venn")

    # ---------------------- LIST: Significant in Both Datasets ----------------------
both_significant = merged[
    (merged["Significant_External"]) & (merged["Significant_Internal"])
]

# Save to file
both_significant.to_csv("Significant_in_Both_Datasets.csv", index=False)

# Display result
print("\nBiomarkers significant in both datasets:")
print(both_significant["Biomarker"].tolist())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib_venn import venn2

# ---------------------- CONFIG ----------------------
external_file = "External_MannWhitney_Stats.csv"
internal_file = "Internal_MannWhitney_Stats.csv"
trend_file = "Trend_Comparison.csv"
output_file = "Merged_Significance_Comparison.csv"
alpha = 0.05

# ---------------------- LOAD DATA ----------------------
external = pd.read_csv(external_file)
internal = pd.read_csv(internal_file)
trend = pd.read_csv(trend_file)

# ---------------------- SIGNIFICANCE FLAGS ----------------------
external["Significant_External"] = external["Adjusted P-value"] < alpha
internal["Significant_Internal"] = internal["Adjusted P-value"] < alpha

# ---------------------- MERGE SIGNIFICANCE ----------------------
merged = pd.merge(
    external[["Biomarker", "Significant_External"]],
    internal[["Biomarker", "Significant_Internal"]],
    on="Biomarker",
    how="outer"
).fillna(False)

# ---------------------- ADD SIGNIFICANCE LABEL ----------------------
def label_row(row):
    if row["Significant_External"] and row["Significant_Internal"]:
        return "Both"
    elif row["Significant_External"]:
        return "External Only"
    elif row["Significant_Internal"]:
        return "Internal Only"
    else:
        return "None"

merged["Significance_Status"] = merged.apply(label_row, axis=1)

# ---------------------- MERGE TREND INFO ----------------------
# Rename column in trend file for consistency
trend = trend.rename(columns={"Unnamed: 0": "Biomarker"})

# Merge trend data into merged table
merged = pd.merge(
    merged,
    trend[["Biomarker", "External_Trend", "Internal_Trend", "Consistent_Trend"]],
    on="Biomarker",
    how="left"
)

# ---------------------- SAVE MERGED TABLE ----------------------
merged.to_csv(output_file, index=False)
print(f"✅ Merged significance + trend saved to: {output_file}")

# ---------------------- FILTER: Significant in Both & Consistent ----------------------
sig_consistent = merged[
    (merged["Significant_External"]) &
    (merged["Significant_Internal"]) &
    (merged["Consistent_Trend"] == True)
].copy()

print(f"\n✅ Biomarkers significant in both datasets and consistent: {len(sig_consistent)}")
print(sig_consistent["Biomarker"].tolist())

# ---------------------- PREP FOR PLOTTING ----------------------
bar_df = pd.melt(
    sig_consistent,
    id_vars="Biomarker",
    value_vars=["External_Trend", "Internal_Trend"],
    var_name="Dataset",
    value_name="Trend"
)
bar_df["Dataset"] = bar_df["Dataset"].str.replace("_Trend", "")

# ---------------------- BAR PLOT ----------------------
sns.set(style="whitegrid")
plt.figure(figsize=(7, 5))
ax = sns.barplot(
    data=bar_df,
    x="Trend",
    y="Biomarker",
    hue="Dataset",
    edgecolor="black",
    linewidth=2
)

# Thicken plot border
for spine in ax.spines.values():
    spine.set_linewidth(2)
    spine.set_edgecolor("black")

plt.axvline(0, color="black", linestyle="--", linewidth=1.2)
plt.xlabel("Trend (Case/CRC - Control)", fontsize=11)
plt.ylabel("Genes", fontsize=11)
plt.tight_layout()
#plt.savefig("Barplot_Significant_Consistent_Only.png")
plt.show()

!pip install adjustText

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# If adjustText isn’t installed, use the annotate fallback:
try:
    from adjustText import adjust_text
    use_adjusttext = True
except ImportError:
    use_adjusttext = False

# Load the data
comparison_df = pd.read_csv("Trend_Comparison.csv", index_col=0)
dfc = comparison_df[comparison_df["Consistent_Trend"]].copy()
dfc["Avg_Trend"] = (dfc["External_Trend"].abs() + dfc["Internal_Trend"].abs()) / 2

# Publication style
plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times"],
    "font.size": 12,
    "axes.titlesize": 14,
    "axes.labelsize": 12,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "axes.linewidth": 2,        # thick axes border
    "xtick.direction": "out",
    "ytick.direction": "out",
})

fig, ax = plt.subplots(figsize=(6,6))

# Scatter
pts = ax.scatter(
    dfc["External_Trend"], dfc["Internal_Trend"],
    s = 100 + 400 * (dfc["Avg_Trend"] / dfc["Avg_Trend"].max()),
    c = dfc["Avg_Trend"], cmap="coolwarm",
    edgecolor="black", linewidth=1.2,
    alpha=0.9
)

# Diagonal (heavier)
lims = [
    min(ax.get_xlim()[0], ax.get_ylim()[0]),
    max(ax.get_xlim()[1], ax.get_ylim()[1])
]
ax.plot(lims, lims, ls="--", lw=2, color="gray", zorder=0)
ax.set_xlim(lims); ax.set_ylim(lims)

# Labels
ax.set_xlabel("External CRC – Control Trend", labelpad=8)
ax.set_ylabel("Internal Case – Control Trend", labelpad=8)
#ax.set_title("Consistent Biomarker Trends", pad=12)

# Colorbar with thick border
cbar = fig.colorbar(pts, ax=ax, pad=0.02)
cbar.set_label("Mean |Trend|", rotation=270, labelpad=15)
cbar.outline.set_linewidth(2)    # thick border around colorbar

# Annotations
texts = []
if use_adjusttext:
    for idx, row in dfc.iterrows():
        texts.append(ax.text(
            row["External_Trend"], row["Internal_Trend"],
            idx, fontsize=10
        ))
    from adjustText import adjust_text
    adjust_text(texts, arrowprops=dict(arrowstyle="-", color="gray", lw=1.0))
else:
    for idx, row in dfc.iterrows():
        ax.annotate(
            idx,
            (row["External_Trend"], row["Internal_Trend"]),
            textcoords="offset points",
            xytext=(5,5),
            ha="left",
            fontsize=8
        )

# Thicken plot spines
for spine in ax.spines.values():
    spine.set_linewidth(2)
    spine.set_edgecolor("black")

sns.despine(trim=True)
plt.tight_layout()
plt.savefig("Consistent_Trends.png", dpi=600)
plt.show()