# -*- coding: utf-8 -*-
"""Files_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGDoadR_3Zu0l3H3eOAPQ1oVAGsVHhXZ
"""

# Here we select the species of interest from the main expression abundance file/ matrix to form its own abundance matrix file using the species names from the VFDB and CARD files##

import pandas as pd

# Load the CSV files
card_vfdb_matched_species = pd.read_csv('/content/pathogen_species_list')
species_contaminants_final = pd.read_csv('/content/hellinger_transformed.csv')

# Rename columns for clarity
card_vfdb_matched_species = card_vfdb_matched_species.rename(columns={card_vfdb_matched_species.columns[0]: "taxon"})

# Strip whitespace from species names in both datasets
card_vfdb_matched_species["taxon"] = card_vfdb_matched_species["taxon"].str.strip()
species_contaminants_final["taxon"] = species_contaminants_final["taxon"].str.strip()

# Extract the species list from card_matched_species
species_list = card_vfdb_matched_species["taxon"].tolist()

# Filter species_contaminants_final for matching species
filtered_data = species_contaminants_final[species_contaminants_final["taxon"].isin(species_list)]

# Save the filtered data to a new file
output_path = '/content/Species_Pathogen_New.csv'
filtered_data.to_csv(output_path, index=False)

print(f"Filtered data saved to {output_path}")

import pandas as pd

# === Step 1: Load Files ===
expr = pd.read_csv("Species_Pathogen_New.csv")
meta = pd.read_csv("Aligned_metadata.csv")

# === Step 2: Transpose Expression Matrix ===
# Set 'taxon' column as index before transposing
expr = expr.rename(columns={expr.columns[0]: "taxon"})
expr.set_index("taxon", inplace=True)
expr_t = expr.T  # Now rows = Sample_IDs

# Clean sample IDs
expr_t.index = expr_t.index.str.strip()
meta["Sample_ID"] = meta["Sample_ID"].astype(str).str.strip()
meta.set_index("Sample_ID", inplace=True)

# === Step 3: Align by Sample_ID ===
common_samples = expr_t.index.intersection(meta.index)
expr_aligned = expr_t.loc[common_samples]
meta_aligned = meta.loc[common_samples]

# === Step 4: Save Outputs ===
expr_aligned.to_csv("Expression_Matrix_Aligned.csv")
meta_expr_merged = meta_aligned.join(expr_aligned)
meta_expr_merged.to_csv("Merged_Metadata_Expression.csv")

print("✅ Transposed, aligned, and merged files saved.")