# -*- coding: utf-8 -*-
"""Metagenomics_Data_Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySmSyMy3N2tBQLGUcGY_8jzsda_Lss9n

Synthetic Data Generation
"""

#!/usr/bin/env python3
import pandas as pd
import numpy as np
import os
from pathlib import Path
from sklearn.decomposition import PCA

# === CONFIGURATION ===
REAL_HELLINGER = "combined_ARG_VFDB_final_DATA.csv"  # genes x samples before transpose
REAL_METADATA = "Metadata_Aligned_VF_ARG_CountMatrix.csv"
OUTPUT_DIR = "synthetic_output_pca_phase2"
BALANCED_N = 1000  # samples per class in balanced version
SEED = 42
EXPLAINED_VAR = 0.95  # keep 95% variance in PCA

np.random.seed(SEED)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# === LOAD DATA ===
print("Loading real data...")
hellinger_df = pd.read_csv(REAL_HELLINGER, index_col=0).T  # samples x genes
metadata_df = pd.read_csv(REAL_METADATA)
sample_col = [c for c in metadata_df.columns if c.lower().startswith("sample")][0]
metadata_df[sample_col] = metadata_df[sample_col].astype(str)
hellinger_df.index = hellinger_df.index.astype(str)

# Match sample IDs
common_ids = sorted(set(hellinger_df.index) & set(metadata_df[sample_col]))
hellinger_df = hellinger_df.loc[common_ids]
metadata_df = metadata_df.set_index(sample_col).loc[common_ids]

gene_cols = hellinger_df.columns
group_labels = metadata_df["Group"].unique()

def generate_pca_synthetic_class(group, n_samples):
    group_data = hellinger_df[metadata_df["Group"] == group]
    if len(group_data) < 5:
        raise ValueError(f"Too few samples for PCA in group '{group}'")

    pca = PCA(n_components=EXPLAINED_VAR, svd_solver='full')
    pca.fit(group_data)

    # Sample from standard normal, then transform
    synthetic_scores = np.random.normal(size=(n_samples, pca.n_components_))
    synthetic_genes = synthetic_scores @ pca.components_ + pca.mean_
    synthetic_genes = np.clip(synthetic_genes, 0, 1)
    df = pd.DataFrame(synthetic_genes, columns=gene_cols)

    # Bootstrap metadata
    group_meta = metadata_df[metadata_df["Group"] == group]
    sampled_meta = group_meta.sample(n=n_samples, replace=True, random_state=SEED).reset_index()
    df.insert(0, "Sample_ID", [f"{group}_synPCA_{i}" for i in range(n_samples)])
    sampled_meta["Sample_ID"] = df["Sample_ID"]

    return df, sampled_meta

# === ORIGINAL RATIO SYNTHETIC SET ===
print("Generating PCA-enhanced synthetic data (real ratio)...")
ratio_hellinger = []
ratio_metadata = []

for group in group_labels:
    n_samples = (metadata_df["Group"] == group).sum()
    syn_X, syn_meta = generate_pca_synthetic_class(group, n_samples)
    ratio_hellinger.append(syn_X)
    ratio_metadata.append(syn_meta)

pd.concat(ratio_hellinger).reset_index(drop=True).to_csv(
    os.path.join(OUTPUT_DIR, "PCA_synthetic_hellinger_real_ratio.csv"), index=False)
pd.concat(ratio_metadata).reset_index(drop=True).to_csv(
    os.path.join(OUTPUT_DIR, "PCA_synthetic_metadata_real_ratio.csv"), index=False)

# === BALANCED SYNTHETIC SET ===
print("Generating PCA-enhanced synthetic data (balanced)...")
balanced_hellinger = []
balanced_metadata = []

for group in group_labels:
    syn_X, syn_meta = generate_pca_synthetic_class(group, BALANCED_N)
    balanced_hellinger.append(syn_X)
    balanced_metadata.append(syn_meta)

pd.concat(balanced_hellinger).reset_index(drop=True).to_csv(
    os.path.join(OUTPUT_DIR, "PCA_synthetic_hellinger_balanced_PCA.csv"), index=False)
pd.concat(balanced_metadata).reset_index(drop=True).to_csv(
    os.path.join(OUTPUT_DIR, "PCA_synthetic_metadata_balanced_PCA.csv"), index=False)

print("PCA-enhanced synthetic data generation completed.")

"""Visualization of synthetic data (balanced)"""

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

real = pd.read_csv("/content/combined_ARG_VFDB_final_DATA_transposed.csv")  # aligned format with samples x features
syn = pd.read_csv("/content/synthetic_output_pca_phase2/PCA_synthetic_hellinger_balanced_PCA.csv")
real["source"] = "Real"
syn["source"] = "Synthetic"

combined = pd.concat([real, syn], ignore_index=True)
X = combined.drop(columns=["Sample_ID", "Group", "source"], errors='ignore')
pca = PCA(n_components=2).fit_transform(X)

combined["PC1"], combined["PC2"] = pca[:,0], pca[:,1]
sns.scatterplot(data=combined, x="PC1", y="PC2", hue="source")
plt.title("PCA: Real vs Synthetic")
plt.show()

from sklearn.manifold import TSNE
tsne = TSNE(n_components=2, perplexity=30, random_state=42)
coords = tsne.fit_transform(X)
combined["TSNE1"], combined["TSNE2"] = coords[:,0], coords[:,1]
sns.scatterplot(data=combined, x="TSNE1", y="TSNE2", hue="source")

"""Visualization of synthetic data (real)

"""

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

real = pd.read_csv("/content/combined_ARG_VFDB_final_DATA_transposed.csv")  # aligned format with samples x features
syn = pd.read_csv("/content/synthetic_output_pca_phase2/PCA_synthetic_hellinger_real_ratio.csv")
real["source"] = "Real"
syn["source"] = "Synthetic"

combined = pd.concat([real, syn], ignore_index=True)
X = combined.drop(columns=["Sample_ID", "Group", "source"], errors='ignore')
pca = PCA(n_components=2).fit_transform(X)

combined["PC1"], combined["PC2"] = pca[:,0], pca[:,1]
sns.scatterplot(data=combined, x="PC1", y="PC2", hue="source")
plt.title("PCA: Real vs Synthetic")
plt.show()


from sklearn.manifold import TSNE
tsne = TSNE(n_components=2, perplexity=30, random_state=42)
coords = tsne.fit_transform(X)
combined["TSNE1"], combined["TSNE2"] = coords[:,0], coords[:,1]
sns.scatterplot(data=combined, x="TSNE1", y="TSNE2", hue="source")

"""Statistical Evaluation of Synthetic data"""

import pandas as pd
import numpy as np
from scipy.stats import ks_2samp
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, silhouette_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns

# === LOAD DATA ===
real = pd.read_csv("combined_ARG_VFDB_final_DATA_transposed.csv")
syn = pd.read_csv("/content/PCA_synthetic_hellinger_balanced_PCA.csv")

real["source"] = "Real"
syn["source"] = "Synthetic"

combined = pd.concat([real, syn], ignore_index=True)
combined = combined.dropna(axis=1, how='any')  # drop columns with NA

# === Prepare Features and Labels ===
non_feature_cols = ["Sample_ID", "Group", "source"]
X = combined.drop(columns=[c for c in non_feature_cols if c in combined.columns], errors='ignore')
y = (combined["source"] == "Synthetic").astype(int)

# === 1. KS TEST on Top 100 Variable Features ===
feature_variances = X.var().sort_values(ascending=False)
top_features = feature_variances.head(100).index
ks_results = []

for feature in top_features:
    ks_stat, p_value = ks_2samp(real[feature], syn[feature])
    ks_results.append({"Feature": feature, "KS_stat": ks_stat, "p_value": p_value})

ks_df = pd.DataFrame(ks_results)
ks_df.to_csv("ks_test_top_100_features.csv", index=False)
print("KS test saved to ks_test_top_100_features.csv")


# === 3. Silhouette Score in PCA and t-SNE space ===
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
silhouette_pca = silhouette_score(X_pca, y)
print(f"Silhouette Score (PCA): {silhouette_pca:.3f}")

# t-SNE
tsne = TSNE(n_components=2, perplexity=30, random_state=42)
X_tsne = tsne.fit_transform(X_scaled)
silhouette_tsne = silhouette_score(X_tsne, y)
print(f"Silhouette Score (t-SNE): {silhouette_tsne:.3f}")

# === Optional: Plot PCA/t-SNE ===
combined["PC1"], combined["PC2"] = X_pca[:, 0], X_pca[:, 1]
sns.scatterplot(data=combined, x="PC1", y="PC2", hue="source")
plt.title("PCA: Real vs Synthetic")
plt.savefig("pca_real_vs_synthetic.png", dpi=300)
plt.clf()

combined["TSNE1"], combined["TSNE2"] = X_tsne[:, 0], X_tsne[:, 1]
sns.scatterplot(data=combined, x="TSNE1", y="TSNE2", hue="source")
plt.title("t-SNE: Real vs Synthetic")
plt.savefig("tsne_real_vs_synthetic.png", dpi=300)
plt.clf()

print("PCA and t-SNE plots saved.")
