# -*- coding: utf-8 -*-
"""Taxa_stats_correlations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tsN41VvRzP305Zb-QQc6KJoR345qWD01
"""

!pip install scikit-posthocs

# Install required package for Dunn's test


# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kruskal
import scikit_posthocs as sp
from statsmodels.stats.multitest import multipletests

# Mount Google Drive if your files are there
# from google.colab import drive
# drive.mount('/content/drive')

# === Load your files ===
# Replace with your actual file paths if not using uploads
abundance = pd.read_csv("hellinger_subset_combat_afterbatch_matrix.csv", index_col=0).T
metadata = pd.read_csv("Aligned_metadata_Taxonomy.csv")
rf_robust = pd.read_csv("robust_biomarkers.20250624csv")
ordinal = pd.read_csv("ordinal_forest_feature_importance.csv").rename(columns={"Gene": "Feature"})

# === Step 1: Filter RF to consistent only ===
rf_consistent = rf_robust[rf_robust["Consistent"] == 1]
rf_species_set = set(rf_consistent["Feature"])
ordinal_species_set = set(ordinal["Feature"])
overlap_species = list(rf_species_set.intersection(ordinal_species_set))

# === Step 2: Subset matrix to overlapping species ===
abundance = abundance[overlap_species]

## Merge RF robustness metadata (e.g. Importance, Stability, Consistency)
rf_full = rf_robust[["Feature", "Importance", "Stability", "Consistent"]].rename(
    columns={
        "Importance": "RF_Importance",
        "Stability": "RF_Stability",
        "Consistent": "RF_Consistent"
    }
)

# Merge Ordinal importance
ordinal_imp = ordinal[["Feature", "Importance"]].rename(columns={"Importance": "Ordinal_Importance"})

# Merge both on overlapping species
overlap_meta = pd.merge(rf_full, ordinal_imp, on="Feature")
overlap_meta = overlap_meta.sort_values("Ordinal_Importance", ascending=False)

# Save to file
overlap_meta.to_csv("Overlap_RF_Ordinal_Metadata.csv", index=False)
print("Overlap with RF and Ordinal importance + metadata saved to Overlap_RF_Ordinal_Metadata.csv")


# === Step 3: Merge metadata with abundance ===
metadata["Sample_ID"] = metadata["Sample_ID"].astype(str)
abundance.index = abundance.index.astype(str)
merged = abundance.merge(metadata[["Sample_ID", "Group"]], 
                         left_index=True, right_on="Sample_ID")

# === Step 4: Run Kruskal-Wallis for each species ===
kruskal_results = []
for species in overlap_species:
    grouped = [group[species].values for name, group in merged.groupby("Group")]
    stat, p = kruskal(*grouped)
    kruskal_results.append({"Species": species, "Kruskal_Stat": stat, "P_Value": p})

kruskal_df = pd.DataFrame(kruskal_results)
kruskal_df["FDR_Adjusted_P"] = multipletests(kruskal_df["P_Value"], method="fdr_bh")[1]
kruskal_df = kruskal_df.sort_values("FDR_Adjusted_P")

# View top results
kruskal_df.head(10)

# === Step 5: Run Dunn’s post-hoc test with FDR ===
dunn_all = []
top_species = kruskal_df.head(20)["Species"]

for species in top_species:
    dunn_raw = sp.posthoc_dunn(
        merged[[species, "Group"]].rename(columns={species: "value", "Group": "group"}),
        val_col="value", group_col="group", p_adjust=None
    )
    # Unstack to long format
    dunn_melted = dunn_raw.where(np.triu(np.ones(dunn_raw.shape), k=1).astype(bool)) \
                          .stack().reset_index()
    dunn_melted.columns = ["Group1", "Group2", "Raw_P"]
    dunn_melted["Species"] = species
    dunn_all.append(dunn_melted)

dunn_df = pd.concat(dunn_all, ignore_index=True)
dunn_df["FDR_Adjusted_P"] = multipletests(dunn_df["Raw_P"], method="fdr_bh")[1]
dunn_df = dunn_df.sort_values("FDR_Adjusted_P")

# Display top significant post-hoc results
dunn_df.head(15)

# === Save Kruskal-Wallis results
kruskal_df.to_csv("kruskal_results.csv", index=False)
print("Saved Kruskal-Wallis results to kruskal_results.csv")

# === Save Dunn's post-hoc results
dunn_df.to_csv("dunn_posthoc_results.csv", index=False)
print(" Saved Dunn's post-hoc results to dunn_posthoc_results.csv")


import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Custom group colors
group_colors = {
    "Healthy": "#ffcc00",
    "Adenoma": "#984ea3",
    "Cancer": "#4daf4a"
}

# Set Seaborn theme
sns.set(style="white", rc={"axes.spines.right": True, "axes.spines.top": True})

# Top species to plot
top_species = kruskal_df.head(10)["Species"].tolist()

# Apply log1p to abundance values for these species
logged_merged = merged.copy()
for species in top_species:
    logged_merged[species] = np.log1p(logged_merged[species])

# Create multi-panel layout
ncols = 2
nrows = int(np.ceil(len(top_species) / ncols))
fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(5 * ncols, 2.5 * nrows))

# Flatten axes for easier iteration
axes = axes.flatten()

for i, species in enumerate(top_species):
    ax = axes[i]
    sns.violinplot(data=logged_merged, x="Group", y=species, palette=group_colors, ax=ax)
    sns.stripplot(data=logged_merged, x="Group", y=species, color="black", size=2, alpha=0.5, ax=ax)

    ax.set_title(species, fontsize=12)
    ax.set_xlabel("")
    ax.set_ylabel("log(1 + abundance)")

    # Thicken axis borders
    for spine in ax.spines.values():
        spine.set_linewidth(2)

    # Remove gridlines
    ax.grid(False)

# Hide any empty subplots
for j in range(i+1, len(axes)):
    axes[j].axis('off')

plt.tight_layout()
plt.savefig("crc_topspecies.png", dpi=600, bbox_inches="tight")
plt.show()

# Import libraries
import pandas as pd
import numpy as np

# ===  Load files ===
# Replace these with your actual file paths
dunn_path = "dunn_posthoc_results.csv"  # Output from Dunn’s test
abundance_path = "hellinger_subset_combat_afterbatch_matrix.csv"
metadata_path = "Aligned_metadata_Taxonomy.csv"

# Load data
dunn_df = pd.read_csv(dunn_path)
abundance_df = pd.read_csv(abundance_path, index_col=0).T  # samples as rows
metadata_df = pd.read_csv(metadata_path)

# ===  Merge abundance and metadata ===
abundance_df.index = abundance_df.index.astype(str)
metadata_df["Sample_ID"] = metadata_df["Sample_ID"].astype(str)
merged_df = abundance_df.merge(metadata_df[["Sample_ID", "Group"]],
                               left_index=True, right_on="Sample_ID")

# === Filter significant comparisons ===
dunn_df = dunn_df[dunn_df["FDR_Adjusted_P"] < 0.05].copy()

# === Compute direction based on median abundance ===
directions = []
for _, row in dunn_df.iterrows():
    species = row["Species"]
    g1, g2 = row["Group1"], row["Group2"]

    median1 = merged_df[merged_df["Group"] == g1][species].median()
    median2 = merged_df[merged_df["Group"] == g2][species].median()

    if median1 > median2:
        directions.append(f"{g1} > {g2}")
    elif median2 > median1:
        directions.append(f"{g2} > {g1}")
    else:
        directions.append("No difference")

dunn_df["Direction"] = directions
dunn_df.rename(columns={"FDR_Adjusted_P": "FDR_P"}, inplace=True)

# === Classify trend category ===
def classify_trend(row):
    d = row["Direction"]
    if "Cancer > Adenoma" in d or "Cancer > Healthy" in d:
        return "Late CRC Enriched"
    elif "Adenoma > Healthy" in d:
        return "Early CRC Enriched"
    elif "Healthy > Adenoma" in d:
        return "Early CRC Depleted"
    elif "Healthy > Cancer" in d:
        return "Late CRC Depleted"
    else:
        return "Ambiguous/Complex"

dunn_df["Trend"] = dunn_df.apply(classify_trend, axis=1)

# === Final summary table ===
summary = dunn_df[["Species", "Group1", "Group2", "Direction", "FDR_P", "Trend"]]
summary.sort_values(["Trend", "Species", "FDR_P"], inplace=True)

# === Save to file
summary.to_csv("crc_trend_clustered_biomarkers.csv", index=False)
print("Clustered biomarker trends saved as crc_trend_clustered_biomarkers.csv")

# Optional: display top results
print(summary.head(10))

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load and prep
df = pd.read_csv("crc_trend_clustered_biomarkers.csv")
df["-log10(FDR_P)"] = -np.log10(df["FDR_P"])
df["Genus"] = df["Species"].str.extract(r'([\w\[\]]+)')

# Static color palette with Enterobacter included
static_genus_colors = {
    "Bacteroides": "#1f77b4",
    "Lactobacillus": "#000000",
    "Eggerthella": "#2ca02c",
    "[Clostridium]": "#d62728",
    "Megasphaera": "#9467bd",
    "Streptococcus": "#8c564b",
    "Adlercreutzia": "#e377c2",
    "Collinsella": "#7f7f7f",
    "Pseudomonas": "#bcbd22",
    "Phoenicibacter": "#17becf",
    "Enterobacter": "#ff7f0e",
    "Serratia": "#0072B2",  # deep blue — new and distinct
    "Other": "#cccccc"
}



# Apply genus grouping
df["Genus_Display"] = df["Genus"].where(df["Genus"].isin(static_genus_colors.keys()), "Other")

# Define trend order
trend_order = ["Early CRC Enriched", "Early CRC Depleted", "Late CRC Enriched", "Late CRC Depleted", "Ambiguous/Complex"]

# Set Seaborn style
sns.set(style="white", context="notebook")

# Plot
plt.figure(figsize=(7, 5))
ax = sns.swarmplot(
    data=df,
    x="Trend",
    y="-log10(FDR_P)",
    order=trend_order,
    hue="Genus_Display",
    palette=static_genus_colors,
    size=8,
    linewidth=1.0,
    edgecolor="black"
)

# FDR threshold
plt.axhline(-np.log10(0.05), color="red", linestyle="--", linewidth=1.2)
plt.text(x=4.4, y=2.0, s="FDR = 0.05", color="red", fontsize=10, ha='right')

# Axes labels and ticks
plt.ylabel(r"$-\log_{10}$(FDR-adjusted p-value)", fontsize=12)
plt.xlabel("CRC Progression Trend", fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=12)
plt.yticks(fontsize=12)
plt.ylim(0, df["-log10(FDR_P)"].max() + 3)

# Legend sorting (move "Other" to the end)
handles, labels = ax.get_legend_handles_labels()
sorted_labels = sorted([l for l in labels if l != "Other"]) + ["Other"]
sorted_handles = [handles[labels.index(l)] for l in sorted_labels]
plt.legend(
    sorted_handles,
    sorted_labels,
    title="Genus",
    title_fontsize=10,
    fontsize=9,
    frameon=True,
    loc="upper left",
    bbox_to_anchor=(1.02, 1),
    borderpad=0.5,
    borderaxespad=0.5,
    labelspacing=0.3,
    handletextpad=0.4,
    handlelength=1.5,
    framealpha=0.95
)

sns.despine()
plt.tight_layout()
plt.savefig("crc_genus_beeswarm.png", dpi=600, bbox_inches="tight")
plt.show()

import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as mcolors
from matplotlib.lines import Line2D

# === LOAD DATA ===
abundance = pd.read_csv("hellinger_subset_combat_afterbatch_matrix.csv", index_col=0).T
trend_df = pd.read_csv("crc_trend_clustered_biomarkers.csv")  # includes 'Species'

# === FILTER TO POST-HOC SPECIES ===
species_list = trend_df["Species"].unique()
abundance_filtered = abundance[abundance.columns.intersection(species_list)]

# === COMPUTE SPEARMAN CORRELATION ===
corr = abundance_filtered.corr(method="spearman")

# === BUILD EDGE LIST (exclude self-correlation) ===
edges_signed = [(i, j, corr.loc[i, j]) for i in corr.columns for j in corr.index if i != j]

# === BUILD GRAPH ===
G = nx.Graph()
for src, tgt, weight in edges_signed:
    G.add_edge(src, tgt, weight=weight)

# Add isolated nodes
for sp in species_list:
    if sp not in G:
        G.add_node(sp)

# === ABS GRAPH FOR LAYOUT ===
G_abs = nx.Graph()
for src, tgt, weight in edges_signed:
    G_abs.add_edge(src, tgt, weight=abs(weight))
for sp in species_list:
    if sp not in G_abs:
        G_abs.add_node(sp)

# === LAYOUT ===
pos = nx.kamada_kawai_layout(G_abs)

# === EDGE STYLES ===
edge_colors = ['#1f77b4' if G[u][v]['weight'] > 0 else '#d62728' for u, v in G.edges()]
edge_widths = [np.clip(abs(G[u][v]['weight']), 0.1, 1.0) * 1.5 for u, v in G.edges()]

# === NODE STYLE BY DEGREE CENTRALITY ===
centrality = nx.degree_centrality(G)
node_sizes = [np.clip(centrality[n] * 2000, 100, 1500) for n in G.nodes()]

# Use a bright colormap and lighten with alpha
centrality_vals = np.array(list(centrality.values()))
norm = mcolors.Normalize(vmin=centrality_vals.min(), vmax=centrality_vals.max())
cmap = cm.get_cmap('cool')  # brighter and softer
node_color = [cmap(norm(centrality[n])) for n in G.nodes()]

# === PLOT NETWORK ===
plt.figure(figsize=(11, 8))
nx.draw_networkx_nodes(G, pos,
    node_size=node_sizes,
    node_color=node_color,
    edgecolors='black',
    linewidths=1.0,
    alpha=0.85
)
nx.draw_networkx_edges(G, pos,
    edge_color=edge_colors,
    width=edge_widths,
    alpha=0.5,
    connectionstyle="arc3,rad=0.2"
)
nx.draw_networkx_labels(G, pos, font_size=8, font_weight='bold')

# === LEGEND ===
legend_elements = [
    Line2D([0], [0], color='#1f77b4', lw=2, label='Positive correlation'),
    Line2D([0], [0], color='#d62728', lw=2, label='Negative correlation')
]
plt.legend(handles=legend_elements, loc='lower right', bbox_to_anchor=(1.02, 1),
           title="Edge Correlation", fontsize=8, title_fontsize=8, frameon=False)

plt.axis('off')
plt.tight_layout()
plt.savefig("cooccurrence_network_curved_edges.png", dpi=600, bbox_inches="tight")
plt.show()

# === EXPORT CORRELATION VALUES ===
corr_long = corr.stack().reset_index()
corr_long.columns = ["Species1", "Species2", "SpearmanR"]
corr_long = corr_long[corr_long["Species1"] != corr_long["Species2"]]
corr_long.to_csv("correlation_values.csv", index=False)

# === EXPORT NETWORK METRICS ===
metrics_df = pd.DataFrame({
    "Species": list(G.nodes),
    "Degree": [G.degree(n) for n in G.nodes()],
    "DegreeCentrality": [centrality[n] for n in G.nodes()],
    "Closeness": [nx.closeness_centrality(G)[n] for n in G.nodes()],
    "Betweenness": [nx.betweenness_centrality(G)[n] for n in G.nodes()],
})
metrics_df.to_csv("network_metrics.csv", index=False)
