# -*- coding: utf-8 -*-
"""ARG_VF_Normalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYUv9fUl93gSiRaljCY46_hDGfjPyI0c
"""

import pandas as pd
# First merge all the CARD files from the different projects and name as "Merged_Card"
# Load the CARD data
df = pd.read_csv('/content/Merged_card.csv', sep=',')

# Step 1: Add a 'Counts' column (presence/absence = 1)
df_with_counts = df.copy()
df_with_counts['Counts'] = 1

# Step 2: Convert 'Counts' to numeric (in case of any issues)
df_with_counts['Counts'] = pd.to_numeric(df_with_counts['Counts'], errors='coerce')

# Step 3: Calculate total gene counts per sample
df_with_counts['Total_Genes_in_Sample'] = df_with_counts.groupby('Sample_ID')['Counts'].transform('sum')

# Step 4: Compute relative abundance of each ARG per sample
df_with_counts['corrected_fraction_total_reads'] = df_with_counts['Counts'] / df_with_counts['Total_Genes_in_Sample']

# Step 5: Aggregate relative abundances across bins and ARGs. Verify the column names and make sure it matches what is in the brackets
overall_abundance_df = df_with_counts.groupby([
    'Sample_ID',
    'Abbreviated_Gene_Name',
    'Drug/Antibiotics_Class',
    'Matched_Species',
    'AMR Gene Family',
    'Resistance Mechanism'
]).agg({
    'corrected_fraction_total_reads': 'sum'
}).reset_index()

# Step 6: Optional — save relative abundance table
overall_abundance_df.to_csv('CRC_CARD_contaminants_data.csv', index=False)

# Step 7: Pivot to create ARG x Sample expression matrix
data_aggregated = overall_abundance_df.groupby(['Abbreviated_Gene_Name', 'Sample_ID'], as_index=False)['corrected_fraction_total_reads'].mean()
expression_matrix = data_aggregated.pivot(index='Abbreviated_Gene_Name', columns='Sample_ID', values='corrected_fraction_total_reads').fillna(0)

# Step 8: Apply Hellinger transformation manually (square root of relative abundance)
expression_matrix_hellinger = expression_matrix.applymap(lambda x: x**0.5)

# Step 9: Save the final Hellinger-transformed matrix
expression_matrix_hellinger.to_csv('CRC_CARD_expression_matrix_hellinger.csv')

# Optional: Display a few rows
print(expression_matrix_hellinger.head())

import pandas as pd
import re

# Load the CSV file
file_path = "/content/Merged_VFDB.csv"  # Update with the correct path if needed
df = pd.read_csv(file_path)

# Remove unnamed columns
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

# Function to parse Protein_Function column
def parse_protein_function(protein_function):
    match = re.match(r"\((.*?)\) (.*?) \[(.*?)\] \[(.*?)\]", str(protein_function))
    if match:
        gene, protein, mechanism, remaining = match.groups()
    else:
        gene, protein, mechanism, remaining = None, None, None, protein_function
    return pd.Series([gene, protein, mechanism, remaining])

# Apply function to extract new columns
df[['Gene', 'Protein', 'Mechanism', 'Remaining_Parts']] = df['Protein_Function'].apply(parse_protein_function)

# Function to split the Mechanism column into Mechanism_1 and Mechanism_2
def split_mechanism(mechanism):
    if pd.notna(mechanism):
        parts = mechanism.split(" - ", 1)  # Split at the first occurrence of " - "
        if len(parts) == 2:
            return pd.Series(parts)
        else:
            return pd.Series([parts[0], None])  # If no "-", put None in Mechanism_2
    return pd.Series([None, None])

# Apply function to create new columns
df[['Mechanism_1', 'Mechanism_2']] = df['Mechanism'].apply(split_mechanism)

# Save the cleaned data
df.to_csv("CRC_Processed_Merged_VFDB.csv", index=False)

# Display the processed DataFrame
print(df.head())

import pandas as pd

# Load the VFDB data
df = pd.read_csv('/content/CRC_Processed_Merged_VFDB.csv', sep=',')


# Step 1: Add a 'Counts' column (presence/absence = 1)
df_with_counts = df.copy()
df_with_counts['Counts'] = 1

# Step 2: Convert 'Counts' to numeric (in case of any issues)
df_with_counts['Counts'] = pd.to_numeric(df_with_counts['Counts'], errors='coerce')

# Step 3: Calculate total gene counts per sample
df_with_counts['Total_Genes_in_Sample'] = df_with_counts.groupby('Sample_ID')['Counts'].transform('sum')

# Step 4: Compute relative abundance of each ARG per sample
df_with_counts['corrected_fraction_total_reads'] = df_with_counts['Counts'] / df_with_counts['Total_Genes_in_Sample']

# Step 5: Aggregate relative abundances across bins and ARGs
# Step 5: Aggregate relative abundances across samples and genes
overall_abundance_df = df_with_counts.groupby([
    'Sample_ID',
    'Abbreviated_Gene_Name',
    'Matched_Species',
    'Mechanism_2',
    'Protein_Function'
]).agg({
    'corrected_fraction_total_reads': 'sum'
}).reset_index()


# Step 6: Optional — save relative abundance table
overall_abundance_df.to_csv('CRC_VFDB.csv', index=False)

# Step 7: Pivot to create ARG x Sample expression matrix
data_aggregated = overall_abundance_df.groupby(['Abbreviated_Gene_Name', 'Sample_ID'], as_index=False)['corrected_fraction_total_reads'].mean()
expression_matrix = data_aggregated.pivot(index='Abbreviated_Gene_Name', columns='Sample_ID', values='corrected_fraction_total_reads').fillna(0)

# Step 8: Apply Hellinger transformation manually (square root of relative abundance)
expression_matrix_hellinger = expression_matrix.applymap(lambda x: x**0.5)

# Step 9: Save the final Hellinger-transformed matrix
expression_matrix_hellinger.to_csv('CRC_VFDB_expression_matrix_hellinger.csv')

# Optional: Display a few rows
print(expression_matrix_hellinger.head())