# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18hcTVLTKRKnj2VtRm8J93nE0NiyDMo6b
"""

#####################################################

import pandas as pd

# =============================
# 1. Load and Preprocess Data
# =============================

# Read the CSV files (update the paths if needed)
before_df = pd.read_csv("Fastq_screen_before.csv")  
after_df = pd.read_csv("Fastq_screen_after.csv")    

# Clean and standardize column names (remove spaces and unify casing)
before_df.columns = before_df.columns.str.strip().str.replace(" ", "_")
after_df.columns = after_df.columns.str.strip().str.replace(" ", "_")

# =============================
# 2. Define Relevant Columns
# =============================

unmapped_cols = [
    "Unmapped_Human",
    "Unmapped_CHM13",
    "Unmapped_Mouse",
    "Unmapped_Adapters",
    "Unmapped_Vectors",
    "Unmapped_Plasmodium"
]

mapped_cols = [col.replace("Unmapped", "Mapped") for col in unmapped_cols]

# =============================
# 3. Calculate and Compare
# =============================

comparison_results = []

# Loop through each cohort
for cohort in before_df["Cohorts"].unique():
    # Filter data by cohort
    before_subset = before_df[before_df["Cohorts"] == cohort].copy()
    after_subset = after_df[after_df["Cohorts"] == cohort].copy()

    # Compute mapped reads for each type
    for unmapped, mapped in zip(unmapped_cols, mapped_cols):
        before_subset[mapped] = before_subset["Reads_processed"] - before_subset[unmapped]
        after_subset[mapped] = after_subset["Reads_processed"] - after_subset[unmapped]

    # Sum mapped reads for each metric
    before_totals = before_subset[mapped_cols].sum()
    after_totals = after_subset[mapped_cols].sum()

    # Calculate differences and percent changes
    change = after_totals - before_totals
    percent_change = (change / before_totals) * 100

    # Combine results into a DataFrame
    cohort_result = pd.DataFrame({
        "Metric": mapped_cols,
        "Before (Mapped)": before_totals.values,
        "After (Mapped)": after_totals.values,
        "Change": change.values,
        "% Change": percent_change.values,
        "Cohorts": cohort
    })

    comparison_results.append(cohort_result)

# =============================
# 4. Save and View Results
# =============================

# Combine all cohort results into one DataFrame
final_corrected_mapped_comparison_df = pd.concat(comparison_results, ignore_index=True)

# Save as CSV
final_corrected_mapped_comparison_df.to_csv("CRC_final_corrected_mapped_reads_comparison.csv", index=False)

# Display the first few rows
print(final_corrected_mapped_comparison_df.head())

###########################################################

import matplotlib.pyplot as plt
import seaborn as sns

# Set optimized DPI for high-quality output
optimized_dpi = 600

# Define colors for Before & After
#colors = ["#1f77b4", "#ff7f0e"]  # Blue for Before, Orange for After
colors = ["#228B22", "#FFD700"]
# Set style for aesthetics
sns.set_style("white")

# Bar Plot for Mapped Reads Before vs. After**
fig, ax = plt.subplots(figsize=(3, 3))

# Extract values for plotting
categories = final_corrected_mapped_comparison_df["Cohorts"].unique()
before_values = final_corrected_mapped_comparison_df.groupby("Cohorts")["Before (Mapped)"].sum()
after_values = final_corrected_mapped_comparison_df.groupby("Cohorts")["After (Mapped)"].sum()

# Define bar positions
x = range(len(categories))
width = 0.5  # Adjust bar width for better spacing

# Plot bars with black borders
ax.bar(x, before_values, width=width, color=colors[0], edgecolor="black", label="Before")
ax.bar([pos + width for pos in x], after_values, width=width, color=colors[1], edgecolor="black", label="After")

# Formatting
#ax.set_title("Mapped Reads Before vs. After Filtering", fontsize=12, fontweight="bold", color="black")
ax.set_xlabel("", fontsize=10, fontweight="bold", color="black")
ax.set_ylabel("Contaminant Reads Count", fontsize=10, color="black")
ax.set_xticks([pos + width /150 for pos in x])
ax.set_xticklabels(categories, rotation=45, fontsize=10, color="black")

# Remove grid lines
ax.grid(False)

# Make the borders black
for spine in ax.spines.values():
    spine.set_edgecolor("black")
    spine.set_linewidth(1.5)

# Add legend
ax.legend(title="", fontsize=10, loc="upper right", frameon=True, edgecolor="black")

# Save the plot
mapped_reads_improved_path = "CRC_Contaminants_reads.png"           #### Figure 2A
plt.savefig(mapped_reads_improved_path, dpi=optimized_dpi, bbox_inches="tight")

# Show the improved plot
plt.show()

###################################3###

import matplotlib.pyplot as plt
import seaborn as sns

# Your metrics of interest
metrics_to_plot = ['N50', 'No. of_contigs', 'L50', 'Total length']

# Set up grid for 2 rows × 2 columns
fig, axes = plt.subplots(2, 2, figsize=(6, 8))
axes = axes.flatten()

# Define green color
green_color = "#228B22"  # Forest green (or use "green")

# Plot each metric into a subplot
for i, metric in enumerate(metrics_to_plot):
    sns.boxplot(data=df, x='Cohorts', y=metric, ax=axes[i], color=green_color)
    axes[i].tick_params(axis='x', rotation=45)
    axes[i].set_xlabel('')

# Remove any unused subplot
for j in range(len(metrics_to_plot), len(axes)):
    fig.delaxes(axes[j])

# Final layout and save
plt.tight_layout()
plt.savefig("CRC_Quast_combined_boxplots.png", dpi=600)  # Supplementary Figure 1B
plt.show()

#########################################################

