# -*- coding: utf-8 -*-
"""Cancer_Prevalence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rGUd20IZ6q6t9H89YjIc7SfIr4KS4OE
"""

# --- SETUP ---
!pip install pandas openpyxl

# ============================================
# STEP 1: Setup
# ============================================

import pandas as pd, re
from pathlib import Path

# Helper: clean species names for cross-dataset harmonization
def clean_species_name(name: str) -> str:
    if pd.isna(name):
        return None
    s = re.sub(r"\[[^\]]+\]", "", str(name))
    s = re.sub(r"\([^)]*\)", "", s)
    s = s.split("|")[0]
    s = s.replace("_", " ").strip().lower()
    s = re.sub(r"\s{2,}", " ", s)
    return s


# ============================================
# STEP 2: Load Excel files
# ============================================
wirbel = pd.read_excel("wirbel_list.xlsx")
piccino = pd.read_excel("Piccino_study_list.xlsx")

# ============================================
# STEP 3: Extract Wirbel markers (core & extended)
# ============================================
for c in ["p.adj.meta", "fc.meta", "auc.meta"]:
    if c in wirbel.columns:
        wirbel[c] = pd.to_numeric(wirbel[c], errors="coerce")

wirbel["clean_species"] = wirbel["species"].apply(clean_species_name)

# Core thresholds (stringent)
core_mask = (wirbel["p.adj.meta"] <= 0.05) & (wirbel["fc.meta"].abs() >= 0.5)
wirbel_core = wirbel.loc[core_mask].copy()

# Extended thresholds (relaxed)
ext_mask = (wirbel["p.adj.meta"] <= 0.10) & (wirbel["fc.meta"].abs() >= 0.3)
wirbel_ext = wirbel.loc[ext_mask].copy()

# Direction annotation
wirbel_core["direction"] = wirbel_core["fc.meta"].apply(lambda x: "enriched_in_CRC" if x > 0 else "depleted_in_CRC")
wirbel_ext["direction"]  = wirbel_ext["fc.meta"].apply(lambda x: "enriched_in_CRC" if x > 0 else "depleted_in_CRC")

# Columns to keep
cols = ["species","clean_species","p.adj.meta","fc.meta","auc.meta","direction"]
wirbel_core[cols].to_csv("wirbel_markers_core.csv", index=False)
wirbel_ext[cols].to_csv("wirbel_markers_extended.csv", index=False)

print(f"✅ Wirbel markers: {len(wirbel_core)} core, {len(wirbel_ext)} extended")


# ============================================
# STEP 4: Extract Piccino stage-associated species
# ============================================
piccino["clean_species"] = piccino["feature"].apply(clean_species_name)
mask = (piccino["metadata"].astype(str).str.lower() == "stage_class") & (piccino["qval"] <= 0.1)
pic_stage = piccino.loc[mask].copy()

agg = (pic_stage.groupby("clean_species")
       .agg(n_sig=("qval","size"), min_q=("qval","min"), mean_coef=("coef","mean"))
       .reset_index()
       .sort_values(["n_sig","min_q"], ascending=[False,True]))

agg.to_csv("piccino_stage_associated_species.csv", index=False)
print(f"✅ Piccino stage-associated species: {len(agg)}")

# ============================================
# STEP 5: Merge into unified CRC reference panel
# ============================================
# Core markers from Wirbel (high confidence)
wir_core = wirbel_core[["clean_species","direction","p.adj.meta","fc.meta","auc.meta"]].copy()
wir_core["source"] = "Wirbel_core"

# Extended markers
wir_ext = wirbel_ext[["clean_species","direction","p.adj.meta","fc.meta","auc.meta"]].copy()
wir_ext["source"] = "Wirbel_extended"

# Piccino stage-associated
pic_df = agg[["clean_species","n_sig","min_q","mean_coef"]].copy()
pic_df["direction"] = pic_df["mean_coef"].apply(lambda x: "enriched_in_CRC_stage" if x > 0 else "depleted_in_CRC_stage")
pic_df["source"] = "Piccino_stage"

# Merge all
merged = pd.concat([wir_core, wir_ext, pic_df], ignore_index=True)
merged = merged.drop_duplicates(subset=["clean_species","source"]).reset_index(drop=True)
merged.to_csv("CRC_reference_marker_panel.csv", index=False)

print(f"✅ Unified CRC reference marker panel created with {len(merged)} unique entries.")

# ============================================
# STEP 6: Preview
# ============================================
print("\n--- Wirbel (core, first 5) ---")
display(wir_core.head())

print("\n--- Piccino stage-associated (first 5) ---")
display(pic_df.head())

print("\n--- Merged CRC marker panel (first 10) ---")
display(merged.head(10))

# --- SETUP ---
!pip install upsetplot matplotlib-venn -q

import pandas as pd, re
from pathlib import Path
import matplotlib.pyplot as plt
from upsetplot import UpSet, from_contents


# ============================================
# STEP 6: Overlap visualization (Venn + UpSet)
# ============================================
wir_core_set = set(wir_core["clean_species"])
wir_ext_set  = set(wir_ext["clean_species"])
pic_set      = set(agg["clean_species"])

# --- Simple 3-set Venn (if matplotlib-venn is available) ---
try:
    from matplotlib_venn import venn3
    plt.figure(figsize=(6,5))
    venn3([wir_core_set, wir_ext_set, pic_set],
          set_labels=("Wirbel Core", "Wirbel Extended", "Piccino Stage"))
    plt.title("Overlap between CRC Marker Sets")
    plt.show()
except Exception as e:
    print("Venn diagram skipped:", e)

# --- UpSet Plot for detailed intersections ---
contents = {
    "Wirbel_core": wir_core_set,
    "Wirbel_extended": wir_ext_set,
    "Piccino_stage": pic_set
}
upset_data = from_contents(contents)
UpSet(upset_data, subset_size='count', show_counts=True).plot()
plt.title("CRC Marker Overlap (UpSet Plot)")
plt.show()

# --- Nature-style Venn & UpSet Visualization (Fixed) ---
import matplotlib.pyplot as plt
from matplotlib_venn import venn3
from upsetplot import UpSet, from_contents
import seaborn as sns

# Use a Nature-style palette
colors = sns.color_palette("muted", 3)
plt.rcParams.update({
    "font.family": "sans-serif",
    "font.size": 12,
    "axes.linewidth": 1.2,
    "axes.titlesize": 14,
    "axes.titleweight": "bold",
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
})

# =========================================================
# 1️⃣ VENN DIAGRAM — Minimalist, clean, labelled with counts
# =========================================================
A, B, C = wir_core_set, wir_ext_set, pic_set
venn_data = venn3(
    [A, B, C],
    set_labels=("Wirbel Core", "Wirbel Extended", "Piccino Stage"),
    set_colors=colors,
    alpha=0.7
)

# Adjust label fonts
for subset in venn_data.subset_labels:
    if subset:
        subset.set_fontsize(10)

# Handle patch borders robustly (works for all versions)
if hasattr(venn_data, "patches"):
    patches = venn_data.patches
else:
    patches = venn_data.subset_patches  # older API fallback

for patch in patches:
    if patch:
        patch.set_linewidth(0.8)
        patch.set_edgecolor("black")

# Title and note
plt.title("Cross-study overlap of CRC-associated taxa", fontsize=14, fontweight="bold", pad=15)
plt.text(-0.8, -0.9, "Numbers denote unique taxa per intersection", fontsize=10, alpha=0.7)
plt.tight_layout()
plt.show()

# =========================================================
# 2️⃣ UPSET PLOT — For detailed intersection visualization
# =========================================================
contents = {
    "Wirbel_core": A,
    "Wirbel_extended": B,
    "Piccino_stage": C
}
upset_data = from_contents(contents)

plt.rcParams.update({"figure.figsize": (8, 5)})
u = UpSet(upset_data, subset_size='count', show_counts=True,
          facecolor="gray", intersection_plot_elements=10,
          sort_by='cardinality')
u.plot()
plt.suptitle("Intersection profile of CRC marker sets", fontsize=14, fontweight="bold", y=1.02)
plt.show()

# =========================================================
# 3️⃣ Quantitative overlap summary
# =========================================================
def overlap_stats(setA, setB, nameA, nameB):
    inter = len(setA & setB)
    pct = inter / len(setA) * 100 if len(setA) > 0 else 0
    return f"{nameA} reproducible in {nameB}: {inter} taxa ({pct:.1f}%)"

print("\n--- Overlap summary ---")
print(overlap_stats(pic_set, wir_core_set, "Piccino", "Wirbel Core"))
print(overlap_stats(pic_set, wir_ext_set, "Piccino", "Wirbel Extended"))
print(overlap_stats(wir_core_set, wir_ext_set, "Wirbel Core", "Wirbel Extended"))

# --- Nature-style Venn & UpSet Visualization with Saving ---
import matplotlib.pyplot as plt
from matplotlib_venn import venn3
from upsetplot import UpSet, from_contents
import seaborn as sns

# Define colors and style
colors = sns.color_palette("muted", 3)
plt.rcParams.update({
    "font.family": "sans-serif",
    "font.size": 12,
    "axes.linewidth": 1.2,
    "axes.titlesize": 14,
    "axes.titleweight": "bold",
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
})

# ============================
# 1️⃣ Venn Diagram (high-res)
# ============================
A, B, C = wir_core_set, wir_ext_set, pic_set
fig, ax = plt.subplots(figsize=(6, 5))
venn_data = venn3(
    [A, B, C],
    set_labels=("Wirbel Core", "Wirbel Extended", "Piccino Stage"),
    set_colors=colors,
    alpha=0.7,
    ax=ax
)

# Clean borders and fonts
for subset in venn_data.subset_labels:
    if subset:
        subset.set_fontsize(10)

if hasattr(venn_data, "patches"):
    patches = venn_data.patches
else:
    patches = venn_data.subset_patches

for patch in patches:
    if patch:
        patch.set_linewidth(0.8)
        patch.set_edgecolor("black")

ax.set_title("Cross-study overlap of CRC-associated taxa", fontsize=14, fontweight="bold", pad=15)
plt.text(-0.8, -0.9, "Numbers denote unique taxa per intersection", fontsize=10, alpha=0.7)
plt.tight_layout()

# --- Save in high resolution ---
fig.savefig("CRC_overlap_venn.tiff", dpi=600, bbox_inches="tight", facecolor="white")
fig.savefig("CRC_overlap_venn.pdf", dpi=600, bbox_inches="tight", facecolor="white")
plt.show()

print("✅ Saved Venn as 'CRC_overlap_venn.tiff' and 'CRC_overlap_venn.pdf'")

# ============================
# 2️⃣ UpSet Plot (high-res)
# ============================
contents = {
    "Wirbel_core": A,
    "Wirbel_extended": B,
    "Piccino_stage": C
}
upset_data = from_contents(contents)

fig2 = plt.figure(figsize=(8, 5))
u = UpSet(upset_data, subset_size='count', show_counts=True,
          facecolor="gray", intersection_plot_elements=10,
          sort_by='cardinality')
u.plot(fig=fig2)
plt.suptitle("Intersection profile of CRC marker sets", fontsize=14, fontweight="bold", y=1.02)

# --- Save high-res versions ---
fig2.savefig("CRC_overlap_upset.tiff", dpi=600, bbox_inches="tight", facecolor="white")
fig2.savefig("CRC_overlap_upset.pdf", dpi=600, bbox_inches="tight", facecolor="white")
plt.show()

print("✅ Saved UpSet as 'CRC_overlap_upset.tiff' and 'CRC_overlap_upset.pdf'")

# ============================
# 3️⃣ Overlap Summary
# ============================
def overlap_stats(setA, setB, nameA, nameB):
    inter = len(setA & setB)
    pct = inter / len(setA) * 100 if len(setA) > 0 else 0
    return f"{nameA} reproducible in {nameB}: {inter} taxa ({pct:.1f}%)"

print("\n--- Overlap summary ---")
print(overlap_stats(pic_set, wir_core_set, "Piccino", "Wirbel Core"))
print(overlap_stats(pic_set, wir_ext_set, "Piccino", "Wirbel Extended"))
print(overlap_stats(wir_core_set, wir_ext_set, "Wirbel Core", "Wirbel Extended"))

# ============================================
# STEP 1: Setup
# ============================================
import pandas as pd
from itertools import combinations

# These sets must already exist from your previous analysis:
# wir_core_set, wir_ext_set, pic_set

# Convert to sorted lists for reproducibility
wir_core_list = sorted(list(wir_core_set))
wir_ext_list  = sorted(list(wir_ext_set))
pic_list      = sorted(list(pic_set))

# ============================================
# STEP 2: Compute intersections and unique sets
# ============================================
# 1. Unique to each
unique_core = wir_core_set - (wir_ext_set | pic_set)
unique_ext  = wir_ext_set  - (wir_core_set | pic_set)
unique_pic  = pic_set      - (wir_core_set | wir_ext_set)

# 2. Pairwise intersections (excluding 3-way)
core_ext    = (wir_core_set & wir_ext_set) - pic_set
core_pic    = (wir_core_set & pic_set) - wir_ext_set
ext_pic     = (wir_ext_set & pic_set) - wir_core_set

# 3. Shared by all
shared_all  = wir_core_set & wir_ext_set & pic_set

# ============================================
# STEP 3: Build a master table
# ============================================
all_species = sorted(list(wir_core_set | wir_ext_set | pic_set))

def membership(sp):
    return {
        "Wirbel_core": sp in wir_core_set,
        "Wirbel_extended": sp in wir_ext_set,
        "Piccino_stage": sp in pic_set
    }

records = []
for sp in all_species:
    m = membership(sp)
    n_sets = sum(m.values())
    if n_sets == 3:
        category = "shared_all"
    elif n_sets == 2:
        if m["Wirbel_core"] and m["Wirbel_extended"]:
            category = "shared_WirbelCore_Extended"
        elif m["Wirbel_core"] and m["Piccino_stage"]:
            category = "shared_WirbelCore_Piccino"
        elif m["Wirbel_extended"] and m["Piccino_stage"]:
            category = "shared_WirbelExtended_Piccino"
        else:
            category = "shared_two"
    else:
        if m["Wirbel_core"]:
            category = "unique_WirbelCore"
        elif m["Wirbel_extended"]:
            category = "unique_WirbelExtended"
        elif m["Piccino_stage"]:
            category = "unique_Piccino"
        else:
            category = "unclassified"
    records.append({
        "species": sp,
        "in_Wirbel_core": m["Wirbel_core"],
        "in_Wirbel_extended": m["Wirbel_extended"],
        "in_Piccino_stage": m["Piccino_stage"],
        "category": category
    })

df_summary = pd.DataFrame(records)

# ============================================
# STEP 4: Save outputs
# ============================================
# Master CSV with all membership flags
df_summary.to_csv("CRC_marker_overlap_summary.csv", index=False)

# Optional: separate CSVs for shared and unique
df_summary[df_summary["category"].str.startswith("unique_")].to_csv("CRC_unique_species.csv", index=False)
df_summary[df_summary["category"].str.startswith("shared_")].to_csv("CRC_shared_species.csv", index=False)

print("✅ CSV files saved:")
print(" - CRC_marker_overlap_summary.csv (complete list)")
print(" - CRC_unique_species.csv (unique to each set)")
print(" - CRC_shared_species.csv (shared across sets)")

# ============================================
# STEP 5: Quick summary counts
# ============================================
print("\n--- Species counts per category ---")
print(df_summary["category"].value_counts())

print("\nShared across all 3 sets:", len(shared_all))
print("Unique to Wirbel Core:", len(unique_core))
print("Unique to Wirbel Extended:", len(unique_ext))
print("Unique to Piccino Stage:", len(unique_pic))

# ============================================
# STEP 1: Setup
# ============================================
import pandas as pd
import numpy as np
import re

# Load your data
df = pd.read_excel("/content/CRC_all_Species.xls")

print("Raw data shape:", df.shape)
print("Columns:", df.columns.tolist())

# ============================================
# STEP 2: Filter species-level entries
# ============================================
# Keep only species-level taxa (taxonomy_lvl == "S")
df = df[df["taxonomy_lvl"] == "S"].copy()

# Keep relevant columns only
df = df[["Sample_ID", "Taxonomy_name", "fraction_total_reads"]]

# ============================================
# STEP 3: Pivot to wide format
# ============================================
# Each row = species, each column = sample
wide = df.pivot_table(index="Taxonomy_name", columns="Sample_ID",
                      values="fraction_total_reads", aggfunc="sum", fill_value=0)

print(f"✅ Pivoted matrix shape: {wide.shape}")

# ============================================
# STEP 3b: Remove non-microbial taxa (e.g. Homo sapiens)
# ============================================

# Define non-microbial keywords (customizable)
non_microbes = [
    "Homo sapiens", "Homo_sapiens", "Mus musculus", "Rattus",
    "Bos taurus", "Arabidopsis", "Zea mays", "Oryza",
    "Drosophila", "Danio rerio", "Unclassified", "uncultured", "unknown"
]

pattern = re.compile("|".join(non_microbes), flags=re.IGNORECASE)

# Filter out non-microbial species
before = wide.shape[0]
wide = wide[~wide.index.str.contains(pattern)]
after = wide.shape[0]

print(f"✅ Removed {before - after} non-microbial taxa (kept {after} microbial species)")

# ============================================
# STEP 4: Normalize (each sample sums to 1)
# ============================================
wide = wide.div(wide.sum(axis=0), axis=1)
print("✅ Normalized each sample to relative abundance")

# ============================================
# STEP 5: Filter out low-prevalence species
# ============================================
presence = (wide > 0).sum(axis=1) / wide.shape[1]
filtered = wide.loc[presence >= 0.05].copy()

print(f"✅ Retained {filtered.shape[0]} species (present in ≥5% of samples)")
print(f"Filtered out {wide.shape[0] - filtered.shape[0]} low-prevalence taxa")

# ============================================
# STEP 6: Save outputs for R
# ============================================
filtered.to_csv("CRC_species_matrix_filtered.csv")
wide.to_csv("CRC_species_matrix_unfiltered.csv")

print("\n✅ Files saved:")
print(" - CRC_species_matrix_filtered.csv  (microbial-only, normalized, ≥5% prevalence)")
print(" - CRC_species_matrix_unfiltered.csv (microbial-only, normalized, all taxa)")

# Optional Excel versions for inspection
filtered.to_excel("CRC_species_matrix_filtered.xlsx")
wide.to_excel("CRC_species_matrix_unfiltered.xlsx")

print("🎯 Done — microbial-only species matrices ready for R (CLR, diversity, prevalence).")

# --- SETUP ---
!pip install upsetplot matplotlib-venn -q