# -*- coding: utf-8 -*-
"""First_ML_PART1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3fg9AxNVsDffvz9xFyFB9kzyQjqj6i8
"""

# ===============================
# Step 1. Data Preparation
# ===============================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# -------------------------
# Load data
# -------------------------
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)
meta = pd.read_csv("Merged_metadata_all.csv")

# Align samples
common_samples = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common_samples]
meta = meta[meta["Sample_ID"].isin(common_samples)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]   # enforce same order

# Features and labels
X = tpm.T.values                      # samples × species
y = meta["Group"].values              # environment labels

print("Features shape (samples × species):", X.shape)
print("Labels distribution:\n", meta["Group"].value_counts())

# -------------------------
# Split: 80% train, 20% hold-out
# -------------------------
X_train, X_hold, y_train, y_hold = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print("\n Train size:", X_train.shape[0], "Hold-out size:", X_hold.shape[0])
print("Train label distribution:\n", pd.Series(y_train).value_counts())
print("Hold-out label distribution:\n", pd.Series(y_hold).value_counts())

# ===============================
# Benchmarking with mean ± SD (Nature-style)
# ===============================

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import make_scorer, accuracy_score, balanced_accuracy_score, f1_score, cohen_kappa_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# -------------------------
# Define scorers
# -------------------------
scorers = {
    "accuracy": make_scorer(accuracy_score),
    "balanced_accuracy": make_scorer(balanced_accuracy_score),
    "f1_macro": make_scorer(f1_score, average="macro"),
    "kappa": make_scorer(cohen_kappa_score)
}

# -------------------------
# Define models
# -------------------------
models = {
    "DecisionTree": DecisionTreeClassifier(random_state=42, class_weight="balanced"),
    "RandomForest": RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced"),
    "LogisticRegression": LogisticRegression(max_iter=5000, random_state=42, class_weight="balanced"),
    "SVM": SVC(kernel="rbf", probability=True, random_state=42, class_weight="balanced"),
    "GradientBoosting": GradientBoostingClassifier(random_state=42)
}

# -------------------------
# Cross-validation (10-fold)
# -------------------------
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
results = []

for name, model in models.items():
    cv_out = cross_validate(model, X_train, y_train, cv=cv, scoring=scorers, n_jobs=-1, return_estimator=False)

    # Store mean + std for each metric
    for metric in scorers.keys():
        values = cv_out[f"test_{metric}"]
        results.append({
            "Model": name,
            "Metric": metric,
            "Mean": np.mean(values),
            "SD": np.std(values)
        })

df_results = pd.DataFrame(results)
print("\n Benchmarking results (mean ± SD across folds):")
print(df_results)

# Save table
df_results.to_csv("ML_Benchmarking_AllModels_1.csv", index=False)

# ============================================================
# Benchmarking Statistics Figure (Nature-style)
# ============================================================

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

# --------------------------------------------
# Prepare data formatting
# --------------------------------------------
df_results["Metric"] = df_results["Metric"].str.replace("_", " ").str.title()

metric_order = ["Accuracy", "Balanced Accuracy", "F1 Macro", "Kappa"]
model_order = ["DecisionTree", "RandomForest", "LogisticRegression", "SVM", "GradientBoosting"]

# Set Seaborn style
sns.set_theme(style="whitegrid", context="talk")

# --------------------------------------------
# Plot using catplot
# --------------------------------------------
g = sns.catplot(
    data=df_results,
    x="Mean", y="Model",
    col="Metric", col_wrap=2,
    kind="point", join=False,
    errorbar=None,
    dodge=True,
    palette="Set2",
    order=model_order,
    height=4.5, aspect=1.3
)

# --------------------------------------------
# Customize each subplot
# --------------------------------------------
for ax, metric in zip(g.axes.flat, metric_order):
    sub = df_results[df_results["Metric"] == metric]

    # Add error bars manually
    for i, row in sub.iterrows():
        ax.errorbar(
            row["Mean"], row["Model"],
            xerr=row["SD"],
            fmt='o', color="black", capsize=3, markersize=6, lw=1
        )

    # Alternate grey shading for rows
    for ytick, label in enumerate(sub["Model"].unique()):
        if ytick % 2 == 0:
            ax.axhspan(ytick - 0.4, ytick + 0.4, facecolor="lightgrey", alpha=0.15, zorder=0)

    # Clean axis and title
    ax.set_xlim(0.1, 0.8)  # adjust based on your accuracy range
    ax.set_xlabel("Score (mean ± SD)", fontsize=12, weight="bold")
    ax.set_ylabel("")
    ax.set_title(metric, fontsize=14, weight="bold")

    # Black border
    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_edgecolor("black")
        spine.set_linewidth(1.2)

plt.suptitle("Machine Learning Benchmarking Across Models", fontsize=16, weight="bold", y=1.03)
plt.tight_layout()
plt.savefig("ML_Benchmarking_Figure.tiff", dpi=600, bbox_inches="tight", facecolor="white")
plt.show()

# --------------------------------------------
# Compress the TIFF using Pillow
# --------------------------------------------
img = Image.open("ML_Benchmarking_Figure.tiff")
img.save("ML_Benchmarking_Figure_LZW.tiff", compression="tiff_lzw")
print("✅ Compressed image saved as ML_Benchmarking_Figure_LZW.tiff")

# ===============================
# Benchmarking Statistics Table
# ===============================

# Pivot for table
table = df_results.pivot(index="Model", columns="Metric", values="Mean")
table_sd = df_results.pivot(index="Model", columns="Metric", values="SD")

# Combine mean ± SD into one string
stats_table = table.round(3).astype(str) + " ± " + table_sd.round(3).astype(str)

# Save clean table
stats_table.to_csv("ML_Benchmarking_Statistics_2.csv")
print(stats_table)

!pip install scikit-posthocs

# ===============================
# Statistical Comparisons of Models ==== Fold_Level (This is important if you want to conduct some statistical Comparisons)
# ===============================

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import make_scorer, accuracy_score, balanced_accuracy_score, f1_score, cohen_kappa_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from scipy.stats import friedmanchisquare, wilcoxon
import scikit_posthocs as sp
import seaborn as sns
import matplotlib.pyplot as plt

# -------------------------
# 1. Setup scorers & models
# -------------------------
scorers = {
    "accuracy": make_scorer(accuracy_score),
    "balanced_accuracy": make_scorer(balanced_accuracy_score),
    "f1_macro": make_scorer(f1_score, average="macro"),
    "kappa": make_scorer(cohen_kappa_score)
}

models = {
    "DecisionTree": DecisionTreeClassifier(random_state=42, class_weight="balanced"),
    "RandomForest": RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced"),
    "LogisticRegression": LogisticRegression(max_iter=5000, random_state=42, class_weight="balanced"),
    "SVM": SVC(kernel="rbf", probability=True, random_state=42, class_weight="balanced"),
    "GradientBoosting": GradientBoostingClassifier(random_state=42)
}

# -------------------------
# 2. Collect fold-level results
# -------------------------
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
fold_results = []

for name, model in models.items():
    cv_out = cross_validate(model, X_train, y_train, cv=cv, scoring=scorers, n_jobs=-1, return_estimator=False)
    for metric in scorers.keys():
        for v in cv_out[f"test_{metric}"]:
            fold_results.append({"Model": name, "Metric": metric, "Score": v})

df_folds = pd.DataFrame(fold_results)
df_folds.to_csv("ML_Benchmarking_FoldLevel.csv", index=False)
print("Saved fold-level benchmarking results")

# -------------------------
# 3. Friedman test (global across models for each metric)
# -------------------------
friedman_results = {}
for metric in scorers.keys():
    pivot = df_folds[df_folds["Metric"]==metric].pivot(columns="Model", values="Score")
    stat, p = friedmanchisquare(*[pivot[m].dropna() for m in pivot.columns])
    friedman_results[metric] = {"stat": stat, "p": p}

friedman_df = pd.DataFrame(friedman_results).T
friedman_df.to_csv("ML_FriedmanTest.csv")
print("\n Friedman tests:\n", friedman_df)

# -------------------------
# 4. Pairwise Wilcoxon tests (Holm correction) === continue with this step only if you found atleast 1 difference in the Friedman test
# -------------------------
pairwise_results = []
for metric in scorers.keys():
    pivot = df_folds[df_folds["Metric"]==metric].pivot(columns="Model", values="Score")
    models_list = pivot.columns.tolist()
    for i in range(len(models_list)):
        for j in range(i+1, len(models_list)):
            m1, m2 = models_list[i], models_list[j]
            stat, p = wilcoxon(pivot[m1], pivot[m2])
            pairwise_results.append({"Metric": metric, "Model1": m1, "Model2": m2, "p_raw": p})

df_pairwise = pd.DataFrame(pairwise_results)

# Holm-Bonferroni correction
df_pairwise["p_adj"] = df_pairwise.groupby("Metric")["p_raw"].transform(lambda x: np.minimum(1, x * len(x)))
df_pairwise.to_csv("ML_Pairwise_Wilcoxon.csv", index=False)
print("\n Pairwise Wilcoxon with Holm correction:\n", df_pairwise.head())

# -------------------------
# 5. Critical Difference (CD) diagram (Nemenyi posthoc)
# -------------------------
for metric in scorers.keys():
    pivot = df_folds[df_folds["Metric"]==metric].pivot(columns="Model", values="Score")
    nemenyi = sp.posthoc_nemenyi_friedman(pivot.values)
    nemenyi.index, nemenyi.columns = pivot.columns, pivot.columns
    nemenyi.to_csv(f"ML_Nemenyi_{metric}.csv")

    plt.figure(figsize=(12,8))
    sns.heatmap(nemenyi, annot=True, fmt=".3f", cmap="coolwarm", cbar_kws={"label":"p-value"})
    plt.title(f"Posthoc Nemenyi test — {metric}")
    plt.tight_layout()
    plt.savefig(f"ML_NemenyiHeatmap_{metric}.tiff", dpi=600)
    plt.close()

# ============================================================
# Nested Cross-Validation + Holdout (RandomForest & GradientBoosting)
# ============================================================

import numpy as np
import pandas as pd
from collections import defaultdict
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score, f1_score, cohen_kappa_score
)
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# -------------------------
# 1️⃣ Load CLR batch-corrected features + metadata
# -------------------------
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)  # species x samples
meta = pd.read_csv("Merged_metadata_all.csv")

# Align sample IDs
common_samples = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common_samples]
meta = meta[meta["Sample_ID"].isin(common_samples)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]  # enforce same order

X = tpm.T.values
y = meta["Group"].values

print(f"✅ Data aligned — features: {X.shape}, labels: {np.unique(y)}")

# -------------------------
# 2️⃣ Train/test split (hold-out 20%)
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"Train size: {X_train.shape[0]} | Test size: {X_test.shape[0]}")

# -------------------------
# 3️⃣ Ensemble Models + Hyperparameter Grids
# -------------------------
models = {
    "RandomForest": RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced"),
    "GradientBoosting": GradientBoostingClassifier(random_state=42)
}

param_grids = {
    "RandomForest": {
        "n_estimators": [300, 500, 800],
        "max_depth": [None, 10, 20],
        "min_samples_leaf": [1, 3, 5],
        "max_features": ["sqrt", 0.3, 0.5]
    },
    "GradientBoosting": {
        "n_estimators": [200, 400],
        "learning_rate": [0.01, 0.05, 0.1],
        "max_depth": [3, 5]
    }
}

# -------------------------
# 4️⃣ Nested CV setup (5 outer folds × 3 inner folds)
# -------------------------
outer = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
inner = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

cv_summary, fold_dfs, best_params = [], [], {}

# -------------------------
# 5️⃣ Run Nested CV
# -------------------------
for name, base_model in models.items():
    print(f"\n🚀 Running nested CV for {name} ...")
    outer_metrics = defaultdict(list)

    for fold, (tr_idx, te_idx) in enumerate(outer.split(X_train, y_train), 1):
        X_tr, X_te = X_train[tr_idx], X_train[te_idx]
        y_tr, y_te = y_train[tr_idx], y_train[te_idx]

        gs = GridSearchCV(
            base_model,
            param_grids[name],
            cv=inner,
            scoring="balanced_accuracy",
            n_jobs=-1
        )
        gs.fit(X_tr, y_tr)
        best = gs.best_estimator_

        y_pred = best.predict(X_te)
        acc = accuracy_score(y_te, y_pred)
        bacc = balanced_accuracy_score(y_te, y_pred)
        f1 = f1_score(y_te, y_pred, average="macro")
        kappa = cohen_kappa_score(y_te, y_pred)

        outer_metrics["Accuracy"].append(acc)
        outer_metrics["BalancedAcc"].append(bacc)
        outer_metrics["F1_macro"].append(f1)
        outer_metrics["Kappa"].append(kappa)

        fold_dfs.append(pd.DataFrame({
            "Model": [name], "Fold": [fold],
            "Accuracy": [acc], "BalancedAcc": [bacc],
            "F1_macro": [f1], "Kappa": [kappa]
        }))

        print(f"  Fold {fold}: BalancedAcc={bacc:.3f}, F1={f1:.3f}")

    # ---- Mean ± SD across outer folds ----
    cv_summary.append({
        "Model": name,
        "MeanAcc": np.mean(outer_metrics["Accuracy"]),
        "StdAcc": np.std(outer_metrics["Accuracy"]),
        "MeanBalancedAcc": np.mean(outer_metrics["BalancedAcc"]),
        "StdBalancedAcc": np.std(outer_metrics["BalancedAcc"]),
        "MeanF1": np.mean(outer_metrics["F1_macro"]),
        "MeanKappa": np.mean(outer_metrics["Kappa"])
    })

    # ---- Final best params from full training ----
    gs_full = GridSearchCV(
        base_model, param_grids[name],
        cv=inner, scoring="balanced_accuracy", n_jobs=-1
    )
    gs_full.fit(X_train, y_train)
    best_params[name] = gs_full.best_params_

# -------------------------
# 6️⃣ Save Nested CV results
# -------------------------
cv_df = pd.DataFrame(cv_summary).sort_values("MeanBalancedAcc", ascending=False)
pd.concat(fold_dfs).to_csv("NestedCV_folds_all.csv", index=False)
cv_df.to_csv("NestedCV_summary.csv", index=False)
pd.DataFrame(best_params).to_csv("NestedCV_best_params.csv")

print("\n📊 Nested CV Summary:")
print(cv_df)
print("\n🔧 Selected hyperparameters:")
print(best_params)

# ============================================================
# 7️⃣ Final Hold-Out Evaluation (RandomForest & GradientBoosting)
# ============================================================

from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score, cohen_kappa_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
import pandas as pd

def evaluate_model(name, model, X_train, y_train, X_test, y_test, filename):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    metrics = {
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "BalancedAcc": balanced_accuracy_score(y_test, y_pred),
        "F1_macro": f1_score(y_test, y_pred, average="macro"),
        "Kappa": cohen_kappa_score(y_test, y_pred)
    }
    print(f"\n✅ Hold-out performance ({name}):")
    for k, v in metrics.items():
        if k != "Model":
            print(f"  {k}: {v:.3f}")
    pd.DataFrame([metrics]).to_csv(filename, index=False)
    return metrics

# ---- Random Forest ----
rf_best = RandomForestClassifier(random_state=42, n_jobs=-1,
                                 class_weight="balanced", **best_params["RandomForest"])
rf_metrics = evaluate_model("RandomForest", rf_best, X_train, y_train, X_test, y_test,
                            "Holdout_RF_Performance.csv")

# ---- Gradient Boosting ----
gb_best = GradientBoostingClassifier(random_state=42, **best_params["GradientBoosting"])
gb_metrics = evaluate_model("GradientBoosting", gb_best, X_train, y_train, X_test, y_test,
                            "Holdout_GB_Performance.csv")

# ---- Combined summary ----
pd.DataFrame([rf_metrics, gb_metrics]).to_csv("Holdout_AllModels_Summary.csv", index=False)
print("\n📊 Hold-out results saved to Holdout_AllModels_Summary.csv")

# ============================================================
# Hold-out Evaluation + AUROC Curves (RF & GB)
# ============================================================

import numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns
from sklearn.metrics import (accuracy_score, balanced_accuracy_score, f1_score,
                             cohen_kappa_score, classification_report,
                             confusion_matrix, roc_curve, auc, RocCurveDisplay)
from sklearn.preprocessing import label_binarize
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# Helper to evaluate and save everything --------------------
def evaluate_and_save(model_name, model, X_train, y_train, X_test, y_test, labels):
    print(f"\n🚀 Evaluating {model_name} on hold-out set...")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # ---- Global metrics
    metrics = {
        "Model": model_name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "BalancedAcc": balanced_accuracy_score(y_test, y_pred),
        "F1_macro": f1_score(y_test, y_pred, average="macro"),
        "Kappa": cohen_kappa_score(y_test, y_pred)
    }
    pd.DataFrame([metrics]).to_csv(f"Holdout_metrics_{model_name}.csv", index=False)
    print(f"✅ Global metrics ({model_name}):", metrics)

    # ---- Per-class report
    report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    per_class = (pd.DataFrame(report).T
                 .loc[[c for c in report.keys() if c in labels]]
                 .rename_axis("Class").reset_index())
    per_class.to_csv(f"Holdout_per_class_{model_name}.csv", index=False)

    # ---- Confusion matrices
    cm = confusion_matrix(y_test, y_pred, labels=labels)
    cm_df = pd.DataFrame(cm, index=labels, columns=labels)
    cm_df.to_csv(f"Holdout_confusion_matrix_{model_name}.csv")
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
    cm_norm_df = pd.DataFrame(cm_norm, index=labels, columns=labels)
    cm_norm_df.to_csv(f"Holdout_confusion_matrix_normalized_{model_name}.csv")

    # ---- Plot confusion matrix
    plt.figure(figsize=(5,5))
    sns.heatmap(cm_norm_df, annot=True, fmt=".2f", cmap="Blues",
                cbar=False, square=True, annot_kws={"size":10})
    plt.title(f"{model_name} — Normalized Confusion Matrix", weight="bold")
    plt.xlabel("Predicted"); plt.ylabel("True")
    plt.tight_layout()
    plt.savefig(f"ConfusionMatrix_{model_name}.tiff", dpi=600)
    plt.close()

    # ---- AUROC (one-vs-rest)
    y_bin = label_binarize(y_test, classes=labels)
    y_score = model.predict_proba(X_test)
    plt.figure(figsize=(6,5))
    for i, cls in enumerate(labels):
        fpr, tpr, _ = roc_curve(y_bin[:, i], y_score[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, lw=2, label=f"{cls} (AUC = {roc_auc:.2f})")
    plt.plot([0,1],[0,1],'--',color='gray',lw=1)
    plt.xlim(0,1); plt.ylim(0,1.05)
    plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
    plt.title(f"{model_name} — One-vs-Rest ROC Curves", weight="bold")
    plt.legend(frameon=False, loc="lower right")
    plt.tight_layout()
    plt.savefig(f"AUROC_{model_name}.tiff", dpi=600)
    plt.close()
    print(f"🎯 AUROC curves saved for {model_name}")
    return metrics

# ============================================================
# Evaluate both tuned models
# ============================================================
labels = np.unique(y)
rf_best = RandomForestClassifier(random_state=42, n_jobs=-1,
                                 class_weight="balanced", **best_params["RandomForest"])
gb_best = GradientBoostingClassifier(random_state=42, **best_params["GradientBoosting"])

rf_results = evaluate_and_save("RandomForest", rf_best, X_train, y_train, X_test, y_test, labels)
gb_results = evaluate_and_save("GradientBoosting", gb_best, X_train, y_train, X_test, y_test, labels)

# ---- Combined summary
pd.DataFrame([rf_results, gb_results]).to_csv("Holdout_AllModels_Summary.csv", index=False)
print("\n📊 Hold-out metrics summary saved (RF + GB).")

#################################################################################################
### Extended Benchmarking with MCC metric
##################################################################################################
# -*- coding: utf-8 -*-
"""Species_ML_with_MCC.ipynb — FULL WORKING SCRIPT"""

# ===============================
# Step 1. Data Preparation
# ===============================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# -------------------------
# Load data
# -------------------------
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)
meta = pd.read_csv("/content/CRC_Cleaned_MetaData.csv")

# Align samples
common_samples = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common_samples]
meta = meta[meta["Sample_ID"].isin(common_samples)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]  # enforce same order

# Features and labels
X = tpm.T.values  # samples × species
y = meta["Group"].values

print("Features shape:", X.shape)
print("Labels distribution:\n", meta["Group"].value_counts())

# -------------------------
# 80/20 Hold-out split
# -------------------------
X_train, X_hold, y_train, y_hold = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print("\nTrain:", X_train.shape[0], "Hold-out:", X_hold.shape[0])


# ===============================
# Benchmarking (10-fold CV) — WITH MCC
# ===============================

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import (
    make_scorer,
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    cohen_kappa_score,
    matthews_corrcoef
)
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier
)
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# -------------------------
# Define scorers (MCC added)
# -------------------------
scorers = {
    "accuracy": make_scorer(accuracy_score),
    "balanced_accuracy": make_scorer(balanced_accuracy_score),
    "f1_macro": make_scorer(f1_score, average="macro"),
    "kappa": make_scorer(cohen_kappa_score),
    "mcc": make_scorer(matthews_corrcoef)
}

# -------------------------
# Define models
# -------------------------
models = {
    "DecisionTree": DecisionTreeClassifier(random_state=42, class_weight="balanced"),
    "RandomForest": RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced"),
    "LogisticRegression": LogisticRegression(max_iter=5000, random_state=42, class_weight="balanced"),
    "SVM": SVC(kernel="rbf", probability=True, random_state=42, class_weight="balanced"),
    "GradientBoosting": GradientBoostingClassifier(random_state=42)
}

# -------------------------
# Cross-validation (10 folds)
# -------------------------
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
results = []

print("\nRunning 10-fold benchmarking with MCC...")

for name, model in models.items():
    cv_out = cross_validate(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring=scorers,
        n_jobs=-1
    )

    for metric in scorers.keys():
        values = cv_out[f"test_{metric}"]
        results.append({
            "Model": name,
            "Metric": metric,
            "Mean": np.mean(values),
            "SD": np.std(values)
        })

df_results = pd.DataFrame(results)
df_results.to_csv("Species_Benchmarking_AllModels_MCC.csv", index=False)

print(df_results)


# ===============================
# Benchmarking Visualization
# ===============================

df_results["Metric"] = df_results["Metric"].str.replace("_", " ").str.title()

metric_order = ["Accuracy", "Balanced Accuracy", "F1 Macro", "Kappa", "Mcc"]
model_order = ["DecisionTree", "RandomForest", "LogisticRegression", "SVM", "GradientBoosting"]

sns.set_theme(style="whitegrid", context="talk")

g = sns.catplot(
    data=df_results,
    x="Mean", y="Model",
    col="Metric", col_wrap=2,
    kind="point", join=False,
    palette="Set2",
    errorbar=None,
    order=model_order,
    height=4.5, aspect=1.3
)

for ax, metric in zip(g.axes.flat, metric_order):
    sub = df_results[df_results["Metric"] == metric]

    for _, row in sub.iterrows():
        ax.errorbar(
            row["Mean"], row["Model"],
            xerr=row["SD"],
            fmt='o', color="black", capsize=3, markersize=6
        )

    ax.set_xlim(0, 1)
    ax.set_title(metric)

plt.savefig("Species_Benchmarking_Figure_MCC.tiff", dpi=600)
plt.show()


# ===============================
# Benchmarking Summary Table (mean ± SD)
# ===============================

table = df_results.pivot(index="Model", columns="Metric", values="Mean")
table_sd = df_results.pivot(index="Model", columns="Metric", values="SD")
stats_table = table.round(3).astype(str) + " ± " + table_sd.round(3).astype(str)

stats_table.to_csv("Species_Benchmarking_Statistics_MCC.csv")
print("\n===== Final Benchmark Table =====")
print(stats_table)


# ===============================
# Nested CV + Final Hold-out — WITH MCC
# ===============================

from sklearn.model_selection import GridSearchCV
from collections import defaultdict

# -------------------------
# Models for nested CV
# -------------------------
models_nested = {
    "RandomForest": RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced"),
    "GradientBoosting": GradientBoostingClassifier(random_state=42)
}

param_grids = {
    "RandomForest": {
        "n_estimators": [300, 500],
        "max_depth": [None, 10],
        "min_samples_leaf": [1, 3],
        "max_features": ["sqrt", 0.5]
    },
    "GradientBoosting": {
        "n_estimators": [200, 400],
        "learning_rate": [0.01, 0.05],
        "max_depth": [3, 5]
    }
}

outer = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
inner = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

cv_summary = []
best_params = {}

for name, base_model in models_nested.items():

    outer_metrics = defaultdict(list)

    for fold, (tr_idx, te_idx) in enumerate(outer.split(X_train, y_train), 1):
        X_tr, X_te = X_train[tr_idx], X_train[te_idx]
        y_tr, y_te = y_train[tr_idx], y_train[te_idx]

        gs = GridSearchCV(
            base_model,
            param_grids[name],
            cv=inner,
            scoring="balanced_accuracy",
            n_jobs=-1
        )
        gs.fit(X_tr, y_tr)
        best = gs.best_estimator_

        y_pred = best.predict(X_te)

        # Add MCC
        mcc = matthews_corrcoef(y_te, y_pred)

        outer_metrics["Accuracy"].append(accuracy_score(y_te, y_pred))
        outer_metrics["BalancedAcc"].append(balanced_accuracy_score(y_te, y_pred))
        outer_metrics["F1"].append(f1_score(y_te, y_pred, average="macro"))
        outer_metrics["Kappa"].append(cohen_kappa_score(y_te, y_pred))
        outer_metrics["MCC"].append(mcc)

    cv_summary.append({
        "Model": name,
        "Acc": np.mean(outer_metrics["Accuracy"]),
        "MCC": np.mean(outer_metrics["MCC"])
    })

    best_params[name] = gs.best_params_

print("\nNested CV Summary:")
print(pd.DataFrame(cv_summary))
print("\nBest params:", best_params)


# ===============================
# Final Hold-out Performance — MCC INCLUDED
# ===============================

from sklearn.metrics import matthews_corrcoef

def evaluate_holdout(model, X_train, y_train, X_hold, y_hold):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_hold)
    return {
        "Accuracy": accuracy_score(y_hold, y_pred),
        "BalancedAcc": balanced_accuracy_score(y_hold, y_pred),
        "F1": f1_score(y_hold, y_pred, average="macro"),
        "Kappa": cohen_kappa_score(y_hold, y_pred),
        "MCC": matthews_corrcoef(y_hold, y_pred)
    }

print("\nEvaluating final tuned models on hold-out...")

rf_final = models_nested["RandomForest"].set_params(**best_params["RandomForest"])
gb_final = models_nested["GradientBoosting"].set_params(**best_params["GradientBoosting"])

rf_hold = evaluate_holdout(rf_final, X_train, y_train, X_hold, y_hold)
gb_hold = evaluate_holdout(gb_final, X_train, y_train, X_hold, y_hold)

holdout_df = pd.DataFrame([rf_hold, gb_hold], index=["RandomForest", "GradientBoosting"])
holdout_df.to_csv("Species_Holdout_With_MCC.csv")

print("\n===== Hold-out Results (with MCC) =====")
print(holdout_df)


print("\n🎯 FULL SPECIES PIPELINE WITH MCC COMPLETE!")
