# -*- coding: utf-8 -*-
"""CRC_ARG_VF_Contigs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AU4y8zmlyVkllpv6Qvb0RC85X4lb6ZvU
"""

import pandas as pd
import re

### -------------------- CARD Normalization -------------------- ###
print("Processing CARD data...")

# Load CARD data
card_df = pd.read_csv('/content/CRC_contaminats_all_CARD', sep=',')

# Step 1: Add presence/absence column
card_df['Counts'] = 1

# Step 2: Ensure numeric
card_df['Counts'] = pd.to_numeric(card_df['Counts'], errors='coerce')

# Step 3: Compute total genes per sample
card_df['Total_Genes_in_Sample'] = card_df.groupby('Sample_ID')['Counts'].transform('sum')

# Step 4: Compute relative abundance per ARG per sample
card_df['relative_abundance'] = card_df['Counts'] / card_df['Total_Genes_in_Sample']

# Step 5: Aggregate by sample and relevant features
card_abundance = card_df.groupby([
    'Sample_ID',
    'Abbreviated_Gene_Name',
    'Drug/Antibiotics_Class',
    'Matched_Species',
    'AMR Gene Family',
    'Resistance Mechanism'
])['relative_abundance'].sum().reset_index()

# Step 6: Save normalized table
card_abundance.to_csv('CRC_CARD_Normalized.csv', index=False)

# Step 7: Pivot to create expression matrix (ARG × Sample)
card_data = card_abundance.groupby(['Abbreviated_Gene_Name', 'Sample_ID'], as_index=False)['relative_abundance'].mean()
card_matrix = card_data.pivot(index='Abbreviated_Gene_Name', columns='Sample_ID', values='relative_abundance').fillna(0)

# Step 8: Save the final CARD expression matrix
card_matrix.to_csv('CRC_CARD_expression_matrix.csv')
print("CARD normalization complete.")


### -------------------- VFDB Normalization -------------------- ###
print("Processing VFDB data...")

# Load VFDB data
vfdb_df = pd.read_csv('/content/CRC_contaminats_all_VFDB', sep=',')

# Clean up unnamed columns if present
vfdb_df = vfdb_df.loc[:, ~vfdb_df.columns.str.contains('^Unnamed')]

# Parse Protein_Function column (if needed)
def parse_protein_function(protein_function):
    match = re.match(r"\((.*?)\) (.*?) \[(.*?)\] \[(.*?)\]", str(protein_function))
    if match:
        gene, protein, mechanism, remaining = match.groups()
    else:
        gene, protein, mechanism, remaining = None, None, None, protein_function
    return pd.Series([gene, protein, mechanism, remaining])

if 'Protein_Function' in vfdb_df.columns:
    vfdb_df[['Gene', 'Protein', 'Mechanism', 'Remaining_Parts']] = vfdb_df['Protein_Function'].apply(parse_protein_function)

# Split Mechanism column (if present)
def split_mechanism(mechanism):
    if pd.notna(mechanism):
        parts = mechanism.split(" - ", 1)
        if len(parts) == 2:
            return pd.Series(parts)
        else:
            return pd.Series([parts[0], None])
    return pd.Series([None, None])

if 'Mechanism' in vfdb_df.columns:
    vfdb_df[['Mechanism_1', 'Mechanism_2']] = vfdb_df['Mechanism'].apply(split_mechanism)

# Step 1: Add presence/absence
vfdb_df['Counts'] = 1

# Step 2: Compute totals
vfdb_df['Total_Genes_in_Sample'] = vfdb_df.groupby('Sample_ID')['Counts'].transform('sum')

# Step 3: Relative abundance per gene per sample
vfdb_df['relative_abundance'] = vfdb_df['Counts'] / vfdb_df['Total_Genes_in_Sample']

# Step 4: Aggregate
vfdb_abundance = vfdb_df.groupby([
    'Sample_ID',
    'Abbreviated_Gene_Name',
    'Matched_Species',
    'Mechanism_2',
    'Protein_Function'
])['relative_abundance'].sum().reset_index()

# Step 5: Save normalized VFDB table
vfdb_abundance.to_csv('CRC_VFDB_Normalized.csv', index=False)

# Step 6: Pivot to create VFDB expression matrix (VF × Sample)
vfdb_data = vfdb_abundance.groupby(['Abbreviated_Gene_Name', 'Sample_ID'], as_index=False)['relative_abundance'].mean()
vfdb_matrix = vfdb_data.pivot(index='Abbreviated_Gene_Name', columns='Sample_ID', values='relative_abundance').fillna(0)

# Step 7: Save VFDB expression matrix
vfdb_matrix.to_csv('CRC_VFDB_expression_matrix.csv')
print("VFDB normalization complete.")

print("✅ Both CARD and VFDB normalization completed successfully.")