# -*- coding: utf-8 -*-
"""ML_ARG_VF_review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jjYwBDykFrdYkBWhn8CjLfYE2eXWDXI
"""

import pandas as pd

# Load data
tpm = pd.read_csv("Combined_ARG_VFDB_CLR_batch_corrected.csv", index_col=0)

# Transpose the dataframe
tpm_transposed = tpm.T

# Display the transposed dataframe
display(tpm_transposed.head())

# Save the transposed dataframe
tpm_transposed.to_csv("Combined_CLR.csv")
print("Transposed dataframe saved as Combined_CLr.csv")

# ===============================
# Step 1. Data Preparation
# ===============================

import os, random, numpy as np
SEED = 42
os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)


import pandas as pd
from sklearn.model_selection import train_test_split

# -------------------------
# Load data
# -------------------------
tpm = pd.read_csv("Combined_CLR.csv", index_col=0)
meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")

# Align samples
common_samples = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common_samples]
meta = meta[meta["Sample_ID"].isin(common_samples)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]   # enforce same order

# Features and labels
X = tpm.T.values                      # samples × species
y = meta["Group"].values              # environment labels

print("Features shape (samples × species):", X.shape)
print("Labels distribution:\n", meta["Group"].value_counts())

# -------------------------
# Split: 80% train, 20% hold-out
# -------------------------
X_train, X_hold, y_train, y_hold = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print("\n Train size:", X_train.shape[0], "Hold-out size:", X_hold.shape[0])
print("Train label distribution:\n", pd.Series(y_train).value_counts())
print("Hold-out label distribution:\n", pd.Series(y_hold).value_counts())

# ===============================
# Benchmarking with mean ± SD (Nature-style)
# ===============================

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import make_scorer, accuracy_score, balanced_accuracy_score, f1_score, cohen_kappa_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# -------------------------
# Define scorers
# -------------------------
scorers = {
    "accuracy": make_scorer(accuracy_score),
    "balanced_accuracy": make_scorer(balanced_accuracy_score),
    "f1_macro": make_scorer(f1_score, average="macro"),
    "kappa": make_scorer(cohen_kappa_score)
}

# -------------------------
# Define models
# -------------------------
models = {
    "DecisionTree": DecisionTreeClassifier(random_state=42, class_weight="balanced"),
    "RandomForest": RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced"),
    "LogisticRegression": LogisticRegression(max_iter=5000, random_state=42, class_weight="balanced"),
    "SVM": SVC(kernel="rbf", probability=True, random_state=42, class_weight="balanced"),
    "GradientBoosting": GradientBoostingClassifier(random_state=42)
}

# -------------------------
# Cross-validation (10-fold)
# -------------------------
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
results = []

for name, model in models.items():
    cv_out = cross_validate(model, X_train, y_train, cv=cv, scoring=scorers, n_jobs=-1, return_estimator=False)

    # Store mean + std for each metric
    for metric in scorers.keys():
        values = cv_out[f"test_{metric}"]
        results.append({
            "Model": name,
            "Metric": metric,
            "Mean": np.mean(values),
            "SD": np.std(values)
        })

df_results = pd.DataFrame(results)
print("\n Benchmarking results (mean ± SD across folds):")
print(df_results)

# Save table
df_results.to_csv("ML_Benchmarking_AllModels_1.csv", index=False)

# ============================================================
# Benchmarking Statistics Figure (Nature-style)
# ============================================================

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

# --------------------------------------------
# Prepare data formatting
# --------------------------------------------
df_results["Metric"] = df_results["Metric"].str.replace("_", " ").str.title()

metric_order = ["Accuracy", "Balanced Accuracy", "F1 Macro", "Kappa"]
model_order = ["DecisionTree", "RandomForest", "LogisticRegression", "SVM", "GradientBoosting"]

# Set Seaborn style
sns.set_theme(style="whitegrid", context="talk")

# --------------------------------------------
# Plot using catplot
# --------------------------------------------
g = sns.catplot(
data=df_results,
x="Mean", y="Model",
col="Metric", col_wrap=2,
kind="point", join=False,
errorbar=None,
dodge=True,
palette="Set2",
order=model_order,
height=4.5, aspect=1.3
)

# --------------------------------------------
# Customize each subplot
# --------------------------------------------
for ax, metric in zip(g.axes.flat, metric_order):
    sub = df_results[df_results["Metric"] == metric]

    # Add error bars manually
    for i, row in sub.iterrows():
        ax.errorbar(
        row["Mean"], row["Model"],
        xerr=row["SD"],
        fmt='o', color="black", capsize=3, markersize=6, lw=1
        )

    # Alternate grey shading for rows
    for ytick, label in enumerate(sub["Model"].unique()):
        if ytick % 2 == 0:
            ax.axhspan(ytick - 0.4, ytick + 0.4, facecolor="lightgrey", alpha=0.15, zorder=0)

    # Clean axis and title
    ax.set_xlim(-0.4, 1.0) # adjust based on your accuracy range
    ax.set_xlabel("Score (mean ± SD)", fontsize=12, weight="bold")
    ax.set_ylabel("")
    ax.set_title(metric, fontsize=14, weight="bold")

    # Black border
    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_edgecolor("black")
        spine.set_linewidth(1.2)

plt.suptitle("Machine Learning Benchmarking Across Models", fontsize=16, weight="bold", y=1.03)
plt.tight_layout()
plt.savefig("ML_Benchmarking_Figure.tiff", dpi=600, bbox_inches="tight", facecolor="white")
plt.show()





# =======================
# Setup: Reproducibility and Imports
# =======================
import os
import random
import numpy as np
import pandas as pd
from collections import defaultdict

# Global seed
SEED = 42
os.environ["PYTHONHASHSEED"] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score, f1_score,
    cohen_kappa_score, classification_report, confusion_matrix
)
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

# =======================
# 1. Load Data
# =======================
tpm = pd.read_csv("Combined_CLR.csv", index_col=0)  # species x samples
meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")

# Align sample IDs
common_samples = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common_samples]
meta = meta[meta["Sample_ID"].isin(common_samples)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]   # enforce same order

X = tpm.T.values
y = meta["Group"].values

# =======================
# 2. Train/test split (hold-out 20%)
# =======================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)

# =======================
# 3. Models + Param Grids
# =======================
models = {
    "RandomForest": RandomForestClassifier(random_state=SEED, class_weight="balanced", n_jobs=-1),
    "GradientBoosting": GradientBoostingClassifier(random_state=SEED)
}

param_grids = {
    "RandomForest": {
        "n_estimators": [100, 300, 500],
        "max_depth": [3, 7, 12],
        "min_samples_split": [2, 5, 10],
        "min_samples_leaf": [1, 2, 4],
        "max_features": ["sqrt", "log2", None]
    },
    "GradientBoosting": {
        "n_estimators": [100, 300, 500],
        "learning_rate": [0.01, 0.05, 0.1],
        "max_depth": [3, 5, 7],
        "subsample": [0.6, 0.8, 1.0]
    }
}

# =======================
# 4. Nested CV setup
# =======================
outer = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
inner = StratifiedKFold(n_splits=3, shuffle=True, random_state=SEED)

cv_summary = []
fold_records = []
best_params = {}

for name, base_model in models.items():
    outer_metrics = defaultdict(list)

    for fold, (tr_idx, te_idx) in enumerate(outer.split(X_train, y_train), 1):
        X_tr, X_te = X_train[tr_idx], X_train[te_idx]
        y_tr, y_te = y_train[tr_idx], y_train[te_idx]

        gs = GridSearchCV(
            base_model, param_grids[name], cv=inner,
            scoring="balanced_accuracy", n_jobs=-1
        )
        gs.fit(X_tr, y_tr)
        best = gs.best_estimator_

        y_pred = best.predict(X_te)
        acc = accuracy_score(y_te, y_pred)
        bacc = balanced_accuracy_score(y_te, y_pred)
        f1 = f1_score(y_te, y_pred, average="macro")
        kappa = cohen_kappa_score(y_te, y_pred)

        outer_metrics["Accuracy"].append(acc)
        outer_metrics["BalancedAcc"].append(bacc)
        outer_metrics["F1_macro"].append(f1)
        outer_metrics["Kappa"].append(kappa)

        fold_records.append({
            "Model": name,
            "Fold": fold,
            "Accuracy": acc,
            "BalancedAcc": bacc,
            "F1_macro": f1,
            "Kappa": kappa
        })

    # Summary across outer folds
    cv_summary.append({
        "Model": name,
        "MeanAcc": np.mean(outer_metrics["Accuracy"]),
        "StdAcc": np.std(outer_metrics["Accuracy"]),
        "MeanBalancedAcc": np.mean(outer_metrics["BalancedAcc"]),
        "StdBalancedAcc": np.std(outer_metrics["BalancedAcc"]),
        "MeanF1": np.mean(outer_metrics["F1_macro"]),
        "MeanKappa": np.mean(outer_metrics["Kappa"])
    })

    # Best params on full training set
    gs_full = GridSearchCV(
        base_model, param_grids[name], cv=inner,
        scoring="balanced_accuracy", n_jobs=-1
    )
    gs_full.fit(X_train, y_train)
    best_params[name] = gs_full.best_params_

# Save nested CV results
cv_df = pd.DataFrame(cv_summary).sort_values("MeanBalancedAcc", ascending=False)
pd.concat([pd.DataFrame(fold_records)]).to_csv("NestedCV_folds_RF_GB.csv", index=False)
cv_df.to_csv("NestedCV_summary_RF_GB.csv", index=False)
pd.DataFrame(best_params).to_csv("NestedCV_best_params_RF_GB.csv")

print("Nested CV summary:\n", cv_df)
print("Selected params:\n", best_params)

# =======================
# 5. Final model on hold-out set
# =======================
winner = cv_df.iloc[0]["Model"]
final_model = models[winner].set_params(**best_params[winner])
final_model.fit(X_train, y_train)
y_hat = final_model.predict(X_test)

# Hold-out metrics
holdout_metrics = {
    "Accuracy": accuracy_score(y_test, y_hat),
    "BalancedAcc": balanced_accuracy_score(y_test, y_hat),
    "F1_macro": f1_score(y_test, y_hat, average="macro"),
    "Kappa": cohen_kappa_score(y_test, y_hat)
}
pd.DataFrame([holdout_metrics]).to_csv("Holdout_metrics_RF_GB.csv", index=False)

# Per-class report
report = classification_report(y_test, y_hat, output_dict=True, zero_division=0)
per_class = pd.DataFrame(report).T.loc[list(np.unique(y_test))]
per_class.to_csv("Holdout_per_class_RF_GB.csv")

# Confusion matrices
cm = confusion_matrix(y_test, y_hat, labels=np.unique(y))
pd.DataFrame(cm, index=np.unique(y), columns=np.unique(y)).to_csv("Holdout_confusion_matrix_RF_GB.csv")
cm_norm = cm.astype(float) / cm.sum(axis=1)[:, None]
pd.DataFrame(cm_norm, index=np.unique(y), columns=np.unique(y)).to_csv("Holdout_confusion_matrix_normalized_RF_GB.csv")

# ============================================================
# 7️⃣ Final Hold-Out Evaluation (RandomForest & GradientBoosting)
# With full reproducibility
# ============================================================

import os
import random
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score,
    f1_score, cohen_kappa_score, classification_report, confusion_matrix
)
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# ------------------------------------------------------------
# 🌱 Global reproducibility setup
# ------------------------------------------------------------
SEED = 42
os.environ["PYTHONHASHSEED"] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)

# ------------------------------------------------------------
#  Function: train, evaluate, and save metrics
# ------------------------------------------------------------
def evaluate_model(name, model, X_train, y_train, X_test, y_test, filename):
    """Train model, evaluate on test set, and save metrics/reports."""
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    metrics = {
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "BalancedAcc": balanced_accuracy_score(y_test, y_pred),
        "F1_macro": f1_score(y_test, y_pred, average="macro"),
        "Kappa": cohen_kappa_score(y_test, y_pred)
    }

    print(f"\n📊 Hold-out performance ({name}):")
    for k, v in metrics.items():
        if k != "Model":
            print(f"  {k}: {v:.3f}")

    # --- Save overall metrics
    pd.DataFrame([metrics]).to_csv(filename, index=False)

    # --- Save per-class report
    report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    pd.DataFrame(report).T.to_csv(filename.replace(".csv", "_PerClass.csv"))

    # --- Save confusion matrices
    cm = confusion_matrix(y_test, y_pred, labels=np.unique(y_test))
    cm_df = pd.DataFrame(cm, index=np.unique(y_test), columns=np.unique(y_test))
    cm_df.to_csv(filename.replace(".csv", "_ConfusionMatrix.csv"))
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
    pd.DataFrame(cm_norm, index=np.unique(y_test), columns=np.unique(y_test)) \
        .to_csv(filename.replace(".csv", "_ConfusionMatrix_Normalized.csv"))

    return metrics


# ------------------------------------------------------------
#  🌲 Random Forest — Tuned Parameters
# ------------------------------------------------------------
rf_best = RandomForestClassifier(
    n_estimators=300,
    max_depth=3,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="log2",
    class_weight="balanced",
    random_state=SEED,
    n_jobs=-1
)
rf_metrics = evaluate_model(
    "RandomForest (Tuned)", rf_best,
    X_train, y_train, X_test, y_test,
    "Holdout_RF_Performance.csv"
)

# ------------------------------------------------------------
#  🚀 Gradient Boosting — Tuned Parameters
# ------------------------------------------------------------
gb_best = GradientBoostingClassifier(
    n_estimators=500,
    learning_rate=0.1,
    max_depth=5,
    subsample=0.6,
    random_state=SEED
)
gb_metrics = evaluate_model(
    "GradientBoosting (Tuned)", gb_best,
    X_train, y_train, X_test, y_test,
    "Holdout_GB_Performance.csv"
)

# ------------------------------------------------------------
#  Combined summary
# ------------------------------------------------------------
summary = pd.DataFrame([rf_metrics, gb_metrics])
summary.to_csv("Holdout_RF_GB_AllModels_Summary.csv", index=False)
print("\n✅ Hold-out results saved to Holdout_RF_GB_AllModels_Summary.csv")

# ============================================================
# 7️⃣ Hold-out Evaluation + AUROC Curves (RandomForest & GradientBoosting)
# With full reproducibility
# ============================================================

# 1. Setup
import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score, f1_score, cohen_kappa_score,
    classification_report, confusion_matrix,
    roc_curve, auc
)
from sklearn.preprocessing import label_binarize
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# ------------------------------------------------------------
# 🌱 Global reproducibility setup
# ------------------------------------------------------------
SEED = 42
os.environ["PYTHONHASHSEED"] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)

# ------------------------------------------------------------
# 2. Helper function — evaluation, saving, and AUROC plotting
# ------------------------------------------------------------
def evaluate_and_save(model_name, model, X_train, y_train, X_test, y_test, labels):
    print(f"\n🚀 Evaluating {model_name} on hold-out set...")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # ---- Global metrics
    metrics = {
        "Model": model_name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "BalancedAcc": balanced_accuracy_score(y_test, y_pred),
        "F1_macro": f1_score(y_test, y_pred, average="macro"),
        "Kappa": cohen_kappa_score(y_test, y_pred)
    }
    pd.DataFrame([metrics]).to_csv(f"Holdout_metrics_{model_name}.csv", index=False)
    print(f"✅ Global metrics ({model_name}):")
    for k, v in metrics.items():
        if k != "Model":
            print(f"  {k}: {v:.3f}")

    # ---- Per-class report
    report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    per_class = (
        pd.DataFrame(report).T
        .loc[[c for c in report.keys() if c in labels]]
        .rename_axis("Class")
        .reset_index()
    )
    per_class.to_csv(f"Holdout_per_class_{model_name}.csv", index=False)

    # ---- Confusion matrices
    cm = confusion_matrix(y_test, y_pred, labels=labels)
    cm_df = pd.DataFrame(cm, index=labels, columns=labels)
    cm_df.to_csv(f"Holdout_confusion_matrix_{model_name}.csv")
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
    cm_norm_df = pd.DataFrame(cm_norm, index=labels, columns=labels)
    cm_norm_df.to_csv(f"Holdout_confusion_matrix_normalized_{model_name}.csv")

    # ---- Confusion Matrix Plot
    plt.figure(figsize=(5, 5))
    sns.heatmap(cm_norm_df, annot=True, fmt=".2f", cmap="Blues",
                cbar=False, square=True, annot_kws={"size": 10})
    plt.title(f"{model_name} — Normalized Confusion Matrix", weight="bold")
    plt.xlabel("Predicted"); plt.ylabel("True")
    plt.tight_layout()
    plt.savefig(f"ConfusionMatrix_{model_name}.png", dpi=300)
    plt.close()

    # ---- AUROC Curves (One-vs-Rest)
    if hasattr(model, "predict_proba"):
        y_bin = label_binarize(y_test, classes=labels)
        y_score = model.predict_proba(X_test)
        plt.figure(figsize=(6, 5))
        for i, cls in enumerate(labels):
            fpr, tpr, _ = roc_curve(y_bin[:, i], y_score[:, i])
            roc_auc = auc(fpr, tpr)
            plt.plot(fpr, tpr, lw=2, label=f"{cls} (AUC = {roc_auc:.2f})")
        plt.plot([0, 1], [0, 1], "--", color="gray", lw=1)
        plt.xlim(0, 1); plt.ylim(0, 1.05)
        plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
        plt.title(f"{model_name} — One-vs-Rest ROC Curves", weight="bold")
        plt.legend(frameon=False, loc="lower right")
        plt.tight_layout()
        plt.savefig(f"AUROC_{model_name}.png", dpi=300)
        plt.close()
        print(f"✅ AUROC curves saved for {model_name}")
    else:
        print(f"⚠️ {model_name} does not support probability predictions (no AUROC plotted).")

    return metrics


# ------------------------------------------------------------
# 3. Labels and tuned models
# ------------------------------------------------------------
labels = np.unique(y_test)  # Ensure class order is consistent

# ---- Random Forest (Tuned Parameters)
rf_best = RandomForestClassifier(
    n_estimators=300,
    max_depth=3,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="log2",
    class_weight="balanced",
    random_state=SEED,
    n_jobs=-1
)

# ---- Gradient Boosting (Tuned Parameters)
gb_best = GradientBoostingClassifier(
    n_estimators=500,
    learning_rate=0.1,
    max_depth=5,
    subsample=0.6,
    random_state=SEED
)

# ------------------------------------------------------------
# 4. Evaluate both models
# ------------------------------------------------------------
rf_results = evaluate_and_save("RandomForest (Tuned)", rf_best,
                               X_train, y_train, X_test, y_test, labels)

gb_results = evaluate_and_save("GradientBoosting (Tuned)", gb_best,
                               X_train, y_train, X_test, y_test, labels)

# ------------------------------------------------------------
# 5. Combined summary
# ------------------------------------------------------------
summary = pd.DataFrame([rf_results, gb_results])
summary.to_csv("Holdout_AllModels_Summary_RF_GB.csv", index=False)
print("\n✅ Hold-out metrics summary saved to Holdout_AllModels_Summary_RF_GB.csv")

# ============================================================
# Feature Stability Analysis — RandomForest + GradientBoosting
# ============================================================

import numpy as np
import pandas as pd
import os, time
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.inspection import permutation_importance

# ------------------------------------------------------------
# 🌱 Global reproducibility
# ------------------------------------------------------------
GLOBAL_SEED = 42
np.random.seed(GLOBAL_SEED)

# ------------------------------------------------------------
# Load & align data
# ------------------------------------------------------------
tpm = pd.read_csv("Combined_CLR.csv", index_col=0)  # species × samples
meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")

common = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common]
meta = meta[meta["Sample_ID"].isin(common)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]  # enforce same sample order

X = tpm.T.values
y = meta["Group"].values
features = tpm.index.tolist()

print(f"✅ Data aligned | Samples: {X.shape[0]} | Features: {X.shape[1]} | Classes: {np.unique(y)}")

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
n_repeats = 30          # number of stability repeats
perm_repeats = 3        # repeats within permutation importance
top_k = 60              # top-K features to refine via permutation
save_every = 10         # save progress every N repeats

# Tuned / consistent model hyperparameters
rf_params = {
    "n_estimators": 300,
    "max_depth": 3,
    "min_samples_split": 2,
    "min_samples_leaf": 1,
    "max_features": "log2",
    "class_weight": "balanced",
    "n_jobs": -1
}

gb_params = {
    "n_estimators": 500,
    "learning_rate": 0.1,
    "max_depth": 5,
    "subsample": 0.6
}

# Stratified CV
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=GLOBAL_SEED)

# Containers
rf_perm_imps = []   # permutation importances for RF
gb_importances = [] # built-in importances for GB
perm_stability = [] # top-K permutation for GB

# Ensure directory
os.makedirs("importance_partials", exist_ok=True)

# ------------------------------------------------------------
# Main loop: reproducible repeats × CV folds
# ------------------------------------------------------------
for repeat in range(1, n_repeats + 1):
    local_seed = GLOBAL_SEED + repeat
    print(f"\n🌱 Repeat {repeat}/{n_repeats}")

    for fold, (tr_idx, te_idx) in enumerate(cv.split(X, y), 1):
        t0 = time.time()
        X_tr, X_te = X[tr_idx], X[te_idx]
        y_tr, y_te = y[tr_idx], y[te_idx]

        # =============================================
        # 1️⃣ Gradient Boosting feature importance
        # =============================================
        gb = GradientBoostingClassifier(random_state=local_seed, **gb_params)
        gb.fit(X_tr, y_tr)
        gb_importances.append(gb.feature_importances_)

        # ---- GB permutation importance (on top-K) ----
        top_idx_gb = np.argsort(gb.feature_importances_)[-top_k:]
        gb_k = GradientBoostingClassifier(random_state=local_seed, **gb_params)
        gb_k.fit(X_tr[:, top_idx_gb], y_tr)
        perm_gb = permutation_importance(
            gb_k, X_te[:, top_idx_gb], y_te,
            n_repeats=perm_repeats, random_state=local_seed, n_jobs=-1
        )
        perm_vec_gb = np.zeros(X.shape[1])
        perm_vec_gb[top_idx_gb] = perm_gb.importances_mean
        perm_stability.append(perm_vec_gb)

        # =============================================
        # 2️⃣ Random Forest permutation importance
        # =============================================
        rf = RandomForestClassifier(random_state=local_seed, **rf_params)
        rf.fit(X_tr, y_tr)
        perm_rf = permutation_importance(
            rf, X_te, y_te,
            n_repeats=perm_repeats, random_state=local_seed, n_jobs=-1
        )
        rf_perm_imps.append(perm_rf.importances_mean)

        print(f"  Fold {fold}/5 done ({time.time()-t0:.1f}s)")

    # ---------------------------------------------
    # Partial Save
    # ---------------------------------------------
    if repeat % save_every == 0:
        pd.DataFrame(rf_perm_imps, columns=features).to_csv(
            f"importance_partials/RF_perm_partial_{repeat}.csv", index=False
        )
        pd.DataFrame(gb_importances, columns=features).to_csv(
            f"importance_partials/GB_imp_partial_{repeat}.csv", index=False
        )
        pd.DataFrame(perm_stability, columns=features).to_csv(
            f"importance_partials/GB_perm_partial_{repeat}.csv", index=False
        )
        print(f"💾 Partial results saved at repeat {repeat}")

# ------------------------------------------------------------
# Final Saves
# ------------------------------------------------------------
pd.DataFrame(rf_perm_imps, columns=features).to_csv("RF_Permutation_Importances_Repeated.csv", index=False)
pd.DataFrame(gb_importances, columns=features).to_csv("GB_FeatureImportances_Repeated.csv", index=False)
pd.DataFrame(perm_stability, columns=features).to_csv("GB_TopK_PermutationImportances_Repeated.csv", index=False)

print("\n✅ Completed all stability runs.")
print("📁 Saved: RF_Permutation_Importances_Repeated.csv, GB_FeatureImportances_Repeated.csv, GB_TopK_PermutationImportances_Repeated.csv")

# ============================================================
# 🧠 Consensus Feature Ranking (RF + GB)
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ------------------------------------------------------------
# 1️⃣ Load saved feature importance results
# ------------------------------------------------------------
rf_df   = pd.read_csv("RF_Permutation_Importances_Repeated.csv")       # Random Forest (Permutation)
gb_df   = pd.read_csv("GB_FeatureImportances_Repeated.csv")            # GB built-in importance
perm_df = pd.read_csv("GB_TopK_PermutationImportances_Repeated.csv")   # GB permutation on top-K

features = rf_df.columns
print(f"✅ Loaded data for {len(features)} features")

# ------------------------------------------------------------
# 2️⃣ Aggregate mean importance per feature (across repeats)
# ------------------------------------------------------------
rf_mean   = rf_df.mean().rename("RF_Permutation")
gb_mean   = gb_df.mean().rename("GB_Builtin")
perm_mean = perm_df.mean().rename("GB_Permutation")

agg = pd.concat([rf_mean, gb_mean, perm_mean], axis=1)

# ------------------------------------------------------------
# 3️⃣ Normalize each method to [0, 1] for comparability
# ------------------------------------------------------------
agg_norm = agg.div(agg.max())

# ------------------------------------------------------------
# 4️⃣ Rank features within each method (1 = most important)
# ------------------------------------------------------------
ranks = agg.rank(ascending=False)
agg["RF_rank"]   = ranks["RF_Permutation"]
agg["GB_rank"]   = ranks["GB_Builtin"]
agg["Perm_rank"] = ranks["GB_Permutation"]

# ------------------------------------------------------------
# 5️⃣ Compute consensus rank (average of method ranks)
# ------------------------------------------------------------
agg["Consensus_rank"] = agg[["RF_rank", "GB_rank", "Perm_rank"]].mean(axis=1)

# ------------------------------------------------------------
# 6️⃣ Sort and save final consensus table
# ------------------------------------------------------------
consensus = (
    agg.sort_values("Consensus_rank")
       .reset_index()
       .rename(columns={"index": "Feature"})
)
consensus.to_csv("Consensus_Feature_Ranking_RF_GB.csv", index=False)

print("✅ Consensus ranking saved to Consensus_Feature_Ranking_RF_GB.csv")
print("\n🏆 Top 10 features:")
print(consensus[["Feature", "Consensus_rank"]].head(10))

# ============================================================
# 🧬 Consensus Feature Importance Visualization (Colorblind Friendly)
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ------------------------------------------------------------
# 1️⃣ Load consensus results and importance data
# ------------------------------------------------------------
consensus = pd.read_csv("Consensus_Feature_Ranking_RF_GB.csv")
rf_df = pd.read_csv("RF_Permutation_Importances_Repeated.csv")

# ------------------------------
# A. Consensus Rank Barplot (Top 30 Features)
# ------------------------------
topN = 30
consensus_sorted = consensus.head(topN)

# Colorblind-friendly palette
highlight_color = "#D55E00"  # Accessible red
regular_color = "#009E73"    # Accessible green

palette = [highlight_color if i < 5 else regular_color for i in range(topN)]

plt.figure(figsize=(7, 8))

sns.barplot(
    data=consensus_sorted,
    y="Feature",
    x="Consensus_rank",
    palette=palette,
    edgecolor="black"
)
plt.gca().invert_yaxis()

plt.xlabel("Consensus Rank (lower = more important)", fontsize=12, weight="bold")
plt.ylabel("")
plt.title("Top 30 Consensus Features (RF + GB)", fontsize=14, weight="bold")

sns.despine()
plt.grid(axis="x", linestyle="--", alpha=0.4)
plt.tight_layout()
plt.savefig("Consensus_Top30_Barplot_Colorblind.tiff", dpi=600, bbox_inches="tight")
plt.show()

print("✅ Saved: Consensus_Top30_Barplot_Colorblind.tiff")

# ------------------------------
# B. Boxplot of Importance Stability (Top 15 Features)
# ------------------------------
top_features = consensus["Feature"].head(15).tolist()

# Melt the RF permutation data for top features
ordered = rf_df[top_features].melt(var_name="Feature", value_name="Importance")

# Order by median importance
order = (
    ordered.groupby("Feature")["Importance"]
    .median()
    .sort_values(ascending=False)
    .index
)

plt.figure(figsize=(9, 5))
sns.boxplot(
    data=ordered,
    x="Feature",
    y="Importance",
    order=order,
    palette="colorblind",  # built-in colorblind-friendly palette
    width=0.6,
    showcaps=True,
    boxprops={"edgecolor": "black"},
    whiskerprops={"color": "black"},
    medianprops={"color": "black", "linewidth": 2},
)

plt.xticks(rotation=45, ha="right", fontsize=10)
plt.ylabel("Feature Importance (Random Forest)", fontsize=12, weight="bold")
plt.xlabel("")
plt.title("Stability of Top 15 Features Across Repeats", fontsize=14, weight="bold")

sns.despine()
plt.grid(axis="y", linestyle="--", alpha=0.4)
plt.tight_layout()
plt.savefig("RF_ImportanceStability_Top15_Colorblind.tiff", dpi=600, bbox_inches="tight")
plt.show()

print("✅ Saved: RF_ImportanceStability_Top15_Colorblind.tiff")

# ===============================
# Per-Environment Feature Importance (Gradient Boosting)
# Reproducible Version
# ===============================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import StratifiedKFold

# ---- 1) Global reproducibility setup ----
GLOBAL_SEED = 42
np.random.seed(GLOBAL_SEED)
os.environ["PYTHONHASHSEED"] = str(GLOBAL_SEED)

# ---- 2) Load data ----
tpm  = pd.read_csv("Combined_CLR.csv", index_col=0)     # species × samples
meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")
common = tpm.columns.intersection(meta["Sample_ID"])
tpm    = tpm[common]
meta   = meta[meta["Sample_ID"].isin(common)].reset_index(drop=True)
tpm    = tpm[meta["Sample_ID"]]   # enforce same order

X = tpm.T.values        # samples × species
y = meta["Group"].values
species = tpm.index.tolist()

print(f"Data loaded: {X.shape[0]} samples × {X.shape[1]} species; groups: {np.unique(y)}")

# ---- 3) Settings & tuned GB params ----
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=GLOBAL_SEED)
gb_base_params = {
    "n_estimators": 500,
    "learning_rate": 0.1,
    "max_depth": 5,
    "subsample": 0.6,
    "verbose": 0
}


# ---- 4) One-vs-rest training & importance collection ----
env_importances = {env: [] for env in np.unique(y)}

for env in env_importances:
    print(f"\nCollecting importances for environment: {env}")
    y_bin = (y == env).astype(int)

    for fold, (tr_idx, te_idx) in enumerate(cv.split(X, y_bin), 1):
        local_seed = GLOBAL_SEED + fold  # fixed per fold seed
        X_tr, y_tr = X[tr_idx], y_bin[tr_idx]

        gb = GradientBoostingClassifier(random_state=local_seed, **gb_base_params)
        gb.fit(X_tr, y_tr)

        env_importances[env].append(gb.feature_importances_)
        print(f" Fold {fold}/5 done (seed={local_seed})")

# ---- 5) Aggregate mean importances per environment ----
env_mean = {
    env: np.mean(imps, axis=0)
    for env, imps in env_importances.items()
}
env_df = pd.DataFrame(env_mean, index=species)

# ---- 6) Save and visualize ----
topN = 20
for env in env_df.columns:
    top_feats = env_df[env].sort_values(ascending=False).head(topN)
    csv_name = f"Top20_GB_{env}.csv"
    top_feats.to_csv(csv_name, header=["MeanImportance"])
    print(f"Saved top features for {env} to {csv_name}")

    plt.figure(figsize=(6,6))
    sns.barplot(
        x=top_feats.values,
        y=top_feats.index,
        palette="viridis",
        edgecolor="black"
    )
    plt.xlabel("Mean GB Feature Importance", weight="bold")
    plt.ylabel("")
    plt.title(f"Top {topN} Species — {env}", weight="bold")
    sns.despine(left=True, bottom=True)
    plt.tight_layout()
    fig_name = f"Top20_GB_{env}_Barplot.png"
    plt.savefig(fig_name, dpi=300)
    plt.close()
    print(f"Saved barplot for {env} to {fig_name}")

print("\n✅ All per-environment GB feature importance runs completed reproducibly.")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import linkage, leaves_list

# Load abundance and metadata
tpm = pd.read_csv("Combined_CLR.csv", index_col=0)
meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")

# Align samples
common = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common]
meta = meta[meta["Sample_ID"].isin(common)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]

# Load GB feature importance and select top 50 species
imp_df = pd.read_csv("GB_importances_repeated.csv")
top_species = imp_df.mean().sort_values(ascending=False).head(50).index

# Mean abundance per group
tpm_top = tpm.loc[top_species]
df_long = tpm_top.T.copy()
df_long["Group"] = meta["Group"].values
env_means = df_long.groupby("Group").mean().T

# Z-score normalization
scaler = StandardScaler()
env_scaled = pd.DataFrame(
    scaler.fit_transform(env_means),
    index=env_means.index,
    columns=env_means.columns
)

# Reorder environments clearly
env_order = ["Healthy", "Adenoma", "Cancer"]
env_scaled = env_scaled[env_order]

# Cluster species for logical ordering
link = linkage(env_scaled, method="average", metric="correlation")
order = leaves_list(link)
env_scaled = env_scaled.iloc[order, :]

# Plot heatmap clearly annotated
plt.figure(figsize=(10, 12))
ax = sns.heatmap(
    env_scaled,
    cmap="RdBu_r",  # red for enriched (high), blue for depleted (low)
    center=0,
    linewidths=0.5,
    linecolor="white",
    annot=True,  # explicit values
    fmt=".2f",
    annot_kws={"size": 7},
    cbar_kws={
        "label": "Z-score (Normalized Abundance)",
        "ticks": [-2, -1, 0, 1, 2]
    },
    yticklabels=True,
    xticklabels=True
)

# Titles and labels
ax.set_title("Top 50 Species Abundance by Clinical Group", fontsize=16, weight="bold", pad=15)
ax.set_xlabel("Clinical Group", fontsize=14, weight="bold")
ax.set_ylabel("Species", fontsize=14, weight="bold")

# Bold top 10 species labels
for i, label in enumerate(ax.get_yticklabels()):
    label.set_weight("bold" if i < 10 else "normal")
    label.set_fontsize(9)

# X-axis labels
ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha="right", fontsize=12, weight="bold")

plt.tight_layout()
plt.savefig("TopSpecies_EnvHeatmap_Annotated.tiff", dpi=600, bbox_inches="tight")
plt.show()

print("✅ Saved: TopSpecies_EnvHeatmap_Annotated.tiff")