# -*- coding: utf-8 -*-
"""Risk_score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXPeG-aXlSjmv1t8PUI1X-m9_fYX24O_
"""

# ============================================================
# 🧬 PLS–DML Functional Risk (2-component) with Overfitting Checks
# From PLS_1 & PLS_3 → Logistic (DAI_logit)
# Adds: OOF CV AUC + CI, optimism, permutation test, calibration
# Saves PNG figures; gridlines removed; risk table uses OOF preds
# ============================================================

import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, auc, brier_score_loss
from sklearn.calibration import calibration_curve

# -----------------------------
# Config
# -----------------------------
RANDOM_STATE = 42
N_SPLITS = 5
N_BOOT = 1000        # bootstrap for AUC CI
N_PERM = 1000        # permutation test iterations (can lower to 200 if slow)
CLASS_WEIGHT = None  # set to "balanced" if desired; None keeps your original spec
OUTDIR = "dai_outputs_overfit"
os.makedirs(OUTDIR, exist_ok=True)

ORDER = ["Healthy", "Adenoma", "Cancer"]
PALETTE_MAP = {"Healthy": "#4C72B0", "Adenoma": "#DD8452", "Cancer": "#55A868"}
PALETTE = [PALETTE_MAP[g] for g in ORDER]

# -----------------------------
# Utils
# -----------------------------
def bootstrap_auc_ci(y_true, y_score, n_boot=1000, seed=42):
    rng = np.random.default_rng(seed)
    y_true = np.asarray(y_true); y_score = np.asarray(y_score)
    aucs = []
    for _ in range(n_boot):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        fpr_b, tpr_b, _ = roc_curve(y_true[idx], y_score[idx])
        aucs.append(auc(fpr_b, tpr_b))
    lo, hi = np.percentile(aucs, [2.5, 97.5])
    return float(lo), float(hi)

def assign_risk(prob):
    if prob < 0.4: return "Low"
    elif prob <= 0.6: return "Medium"
    else: return "High"

def make_risk_table(df, prob_col="DAI_logit", group_col="Group", out_csv=None):
    tmp = df.copy()
    tmp["DAIlogit_Risk"] = tmp[prob_col].apply(assign_risk)
    tab = (tmp.groupby([group_col, "DAIlogit_Risk"])
             .size().unstack(fill_value=0)
             .reindex(index=ORDER, fill_value=0))
    tab = tab.assign(Total=lambda x: x.sum(axis=1))
    def pct(n,d): return 0.0 if d==0 else round(100*n/d,1)
    fmt = tab.copy()
    for col in ["Low","Medium","High"]:
        if col not in fmt.columns: fmt[col] = 0
    for row in fmt.index:
        tot = int(fmt.loc[row, "Total"])
        for col in ["Low","Medium","High"]:
            n = int(fmt.loc[row, col])
            fmt.loc[row, col] = f"{n} ({pct(n,tot)}%)"
    fmt = fmt.drop(columns="Total")
    if out_csv: fmt.to_csv(out_csv)
    return fmt

def setup_figure():
    sns.set_theme(style="white", font_scale=1.0)
    plt.rcParams["axes.grid"] = False

# -----------------------------
# 1) Load PLS scores + metadata
# -----------------------------
pls_scores = pd.read_csv("Stable_PLS_Scores.csv", index_col=0)  # rows = Sample_ID
meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")

# keep PLS_1 and PLS_3
pls_sub = pls_scores[["PLS_1", "PLS_3"]].copy()

# align to metadata and enforce order
common = pls_sub.index.intersection(meta["Sample_ID"])
pls_sub = pls_sub.loc[common]
meta = (meta[meta["Sample_ID"].isin(common)]
        .drop_duplicates(subset=["Sample_ID"])
        .set_index("Sample_ID").loc[pls_sub.index].reset_index())

meta["Group"] = pd.Categorical(meta["Group"], categories=ORDER, ordered=True)

# Binary outcome: Cancer=1, Healthy/Adenoma=0
y = (meta["Group"] == "Cancer").astype(int).values

# -----------------------------
# 2) Build pipeline (scaler + logistic)
# -----------------------------
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        class_weight=CLASS_WEIGHT,
        max_iter=5000,
        solver="lbfgs",
        random_state=RANDOM_STATE))
])

X = pls_sub.values

# -----------------------------
# 3) In-sample fit (optimistic) and OOF CV predictions
# -----------------------------
# In-sample predictions (optimistic baseline)
pipe.fit(X, y)
p_in = pipe.predict_proba(X)[:, 1]
fpr_in, tpr_in, _ = roc_curve(y, p_in)
auc_in = auc(fpr_in, tpr_in)

# OOF (out-of-fold) predictions
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)
oof_pred = np.zeros(len(y), dtype=float)
oof_fold = np.zeros(len(y), dtype=int)

for fold, (tr, te) in enumerate(skf.split(X, y), 1):
    pipe.fit(X[tr], y[tr])
    oof_pred[te] = pipe.predict_proba(X[te])[:, 1]
    oof_fold[te] = fold

fpr_o, tpr_o, _ = roc_curve(y, oof_pred)
auc_o = auc(fpr_o, tpr_o)
ci_lo, ci_hi = bootstrap_auc_ci(y, oof_pred, n_boot=N_BOOT, seed=RANDOM_STATE)

optimism = auc_in - auc_o

# save per-sample OOF
oof_df = pd.DataFrame({
    "Sample_ID": meta["Sample_ID"].values,
    "Group": meta["Group"].astype(str).values,
    "PLS_1": pls_sub["PLS_1"].values,
    "PLS_3": pls_sub["PLS_3"].values,
    "DAI_logit_OOF": oof_pred,
    "CV_Fold": oof_fold
})
oof_df.to_csv(os.path.join(OUTDIR, "DAIlogit_OOF.csv"), index=False)

print(f"✅ In-sample AUC = {auc_in:.3f}")
print(f"✅ OOF AUC       = {auc_o:.3f} (95% CI {ci_lo:.3f}–{ci_hi:.3f})")
print(f"🔎 Optimism (In - OOF) = {optimism:.3f}")

# -----------------------------
# 4) Permutation test (label shuffle → OOF AUC null)
# -----------------------------
rng = np.random.default_rng(RANDOM_STATE)
perm_aucs = np.zeros(N_PERM)
for b in range(N_PERM):
    y_perm = rng.permutation(y)
    oof_p = np.zeros(len(y))
    for tr, te in skf.split(X, y_perm):
        pipe.fit(X[tr], y_perm[tr])
        oof_p[te] = pipe.predict_proba(X[te])[:, 1]
    fpr_p, tpr_p, _ = roc_curve(y_perm, oof_p)
    perm_aucs[b] = auc(fpr_p, tpr_p)

# p-value (right-tail): proportion of perm AUC ≥ observed OOF AUC
p_perm = (1 + np.sum(perm_aucs >= auc_o)) / (N_PERM + 1)
np.savetxt(os.path.join(OUTDIR, "perm_auc_null.csv"), perm_aucs, delimiter=",")

print(f"🔬 Permutation p-value (AUC_OOF) = {p_perm:.4f}")

# -----------------------------
# 5) Calibration (OOF)
# -----------------------------
brier = brier_score_loss(y, oof_pred)
frac_pos, mean_pred = calibration_curve(y, oof_pred, n_bins=10, strategy="quantile")

# -----------------------------
# 6) Figures (PNG, no gridlines)
# -----------------------------
setup_figure()

# Violin (OOF probabilities)
vi_df = pd.DataFrame({"Group": meta["Group"].astype(str).values, "DAI_logit": oof_pred})
plt.figure(figsize=(5,4))
ax = sns.violinplot(
    data=vi_df.sort_values("Group"),
    x="Group", y="DAI_logit",
    order=ORDER,
    palette=PALETTE,
    inner="box", linewidth=1.2
)
plt.title("Functional Risk (DAI_logit, OOF) Across CRC Stages", fontsize=12, weight="bold")
plt.ylabel("DAI_logit (Predicted CRC Probability, OOF)", fontsize=10, weight="bold")
plt.xlabel("")
sns.despine(); ax.grid(False)
for spine in ax.spines.values(): spine.set_linewidth(1.5)
plt.tight_layout()
plt.savefig(os.path.join(OUTDIR, "Violin_DAIlogit_OOF.png"), dpi=600, bbox_inches="tight")
plt.close()

# ROC (OOF)
plt.figure(figsize=(5,5))
ax = plt.gca()
plt.plot(fpr_o, tpr_o, lw=2, label=f"AUC = {auc_o:.3f} (95% CI {ci_lo:.3f}–{ci_hi:.3f})")
plt.plot([0,1], [0,1], "--", color="gray", lw=1.2)
plt.xlabel("False Positive Rate", fontsize=11, weight="bold")
plt.ylabel("True Positive Rate", fontsize=11, weight="bold")
plt.title("ROC — DAI_logit (OOF, Cancer vs Non-Cancer)", fontsize=12, weight="bold")
plt.legend(frameon=True, loc="lower right")
sns.despine(); ax.grid(False)
for spine in ax.spines.values(): spine.set_linewidth(1.5)
plt.tight_layout()
plt.savefig(os.path.join(OUTDIR, "ROC_DAIlogit_OOF.png"), dpi=600, bbox_inches="tight")
plt.close()

# Permutation histogram
plt.figure(figsize=(6,4))
ax = plt.gca()
plt.hist(perm_aucs, bins=30, alpha=0.9)
plt.axvline(auc_o, color="red", lw=2, label=f"Observed OOF AUC = {auc_o:.3f}")
plt.xlabel("Permutation AUC (label-shuffled)"); plt.ylabel("Count")
plt.title("Permutation Test Null Distribution (OOF AUC)", fontsize=12, weight="bold")
plt.legend()
sns.despine(); ax.grid(False)
for spine in ax.spines.values(): spine.set_linewidth(1.5)
plt.tight_layout()
plt.savefig(os.path.join(OUTDIR, "Permutation_AUC_Hist.png"), dpi=600, bbox_inches="tight")
plt.close()

# Calibration plot
plt.figure(figsize=(5,5))
ax = plt.gca()
plt.plot([0,1], [0,1], "--", color="gray", lw=1.2, label="Perfect calibration")
plt.plot(mean_pred, frac_pos, marker="o", lw=2, label=f"DAI_logit (OOF)")
plt.xlabel("Mean Predicted Probability"); plt.ylabel("Fraction Positives")
plt.title(f"Calibration — OOF (Brier={brier:.3f})", fontsize=12, weight="bold")
plt.legend(frameon=True)
sns.despine(); ax.grid(False)
for spine in ax.spines.values(): spine.set_linewidth(1.5)
plt.tight_layout()
plt.savefig(os.path.join(OUTDIR, "Calibration_DAIlogit_OOF.png"), dpi=600, bbox_inches="tight")
plt.close()

# -----------------------------
# 7) Risk stratification (using OOF preds)
# -----------------------------
risk_table = make_risk_table(
    pd.DataFrame({"Group": meta["Group"].astype(str).values, "DAI_logit": oof_pred}),
    out_csv=os.path.join(OUTDIR, "RiskTable_OOF.csv")
)
print("\n📊 Risk table (OOF):")
print(risk_table)

# -----------------------------
# 8) Save a short report
# -----------------------------
with open(os.path.join(OUTDIR, "Overfitting_Report.txt"), "w") as f:
    f.write("PLS_1+PLS_3 → Logistic (DAI_logit) — Overfitting Checks\n")
    f.write(f"In-sample AUC: {auc_in:.3f}\n")
    f.write(f"OOF AUC: {auc_o:.3f} (95% CI {ci_lo:.3f}–{ci_hi:.3f})\n")
    f.write(f"Optimism (In - OOF): {optimism:.3f}\n")
    f.write(f"Permutation p-value (AUC_OOF): {p_perm:.4f}\n")
    f.write(f"Brier score (OOF): {brier:.3f}\n")
print(f"\n✅ Done. Outputs in: {OUTDIR}")
