# -*- coding: utf-8 -*-
"""External_validation_review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVZMAHi4yKxETqairz1KZTTrZ0V5JCuE
"""

# ============================================================
# 🧬 Internal Binary Classification Benchmark (RF, GB, LR, SVM, DT)
# ============================================================

import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    roc_auc_score, accuracy_score, balanced_accuracy_score,
    f1_score, roc_curve, auc
)
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# ------------------------------------------------------------
# 1️⃣ Load datasets
# ------------------------------------------------------------
internal_tpm = pd.read_csv("Combined_CLR.csv", index_col=0)
internal_meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")

# ------------------------------------------------------------
# 2️⃣ Load PLS-DML genes (PLS₁ & PLS₃)
# ------------------------------------------------------------
pls_genes = pd.read_csv("PLS_TopGenes_Ranked_with_ComponentStats.csv")
focus_components = ["PLS_1", "PLS_3"]
marker_genes = pls_genes[pls_genes["Component"].isin(focus_components)]["Gene"].unique().tolist()
print(f"✅ Loaded {len(marker_genes)} PLS-DML genes from components {focus_components}")

# ------------------------------------------------------------
# 3️⃣ Prepare data (Healthy → 0, Adenoma/Cancer → 1)
# ------------------------------------------------------------
internal_samples = internal_tpm.columns.intersection(internal_meta["Sample_ID"])
internal_tpm = internal_tpm[internal_samples]
internal_meta = internal_meta[internal_meta["Sample_ID"].isin(internal_samples)]

X = internal_tpm.loc[marker_genes].T
y = internal_meta["Group"].replace({
    "Healthy": 0,
    "Adenoma": 1,
    "Cancer": 1
}).astype(int)

print(f"✅ Internal dataset ready: {X.shape[0]} samples × {X.shape[1]} features")
print("Class distribution:")
print(y.value_counts().rename({0: "Control", 1: "CRC"}))

# ------------------------------------------------------------
# 4️⃣ Define models and parameter grids
# ------------------------------------------------------------
models = {
    "RandomForest": (
        RandomForestClassifier(random_state=42, class_weight="balanced"),
        {
            "n_estimators": [300, 500],
            "max_depth": [5, 10, None],
            "min_samples_split": [2, 4],
            "max_features": ["sqrt", "log2"]
        }
    ),
    "GradientBoosting": (
        GradientBoostingClassifier(random_state=42),
        {
            "n_estimators": [200, 500],
            "learning_rate": [0.01, 0.05, 0.1],
            "max_depth": [3, 5],
            "subsample": [0.6, 0.8, 1.0]
        }
    ),
    "LogisticRegression": (
        Pipeline([
            ("scaler", StandardScaler()),
            ("logreg", LogisticRegression(max_iter=5000, class_weight="balanced", random_state=42))
        ]),
        {
            "logreg__penalty": ["l1", "l2"],
            "logreg__C": [0.05, 0.1, 0.5, 1, 2],
            "logreg__solver": ["liblinear", "saga"]
        }
    ),
    "SVM": (
        Pipeline([
            ("scaler", StandardScaler()),
            ("svm", SVC(probability=True, class_weight="balanced", random_state=42))
        ]),
        {
            "svm__C": [0.1, 1, 10],
            "svm__kernel": ["linear", "rbf"],
            "svm__gamma": ["scale", "auto"]
        }
    ),
    "DecisionTree": (
        DecisionTreeClassifier(random_state=42, class_weight="balanced"),
        {
            "max_depth": [3, 5, 10, None],
            "min_samples_split": [2, 4, 6],
            "criterion": ["gini", "entropy"]
        }
    )
}

# ------------------------------------------------------------
# 5️⃣ 5-Fold CV Benchmarking
# ------------------------------------------------------------
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
results = []
roc_curves = {}
grids = {}

for name, (model, grid) in models.items():
    print(f"\n🔍 Tuning {name}...")
    gs = GridSearchCV(model, grid, scoring="roc_auc", cv=cv, n_jobs=-1, verbose=1)
    gs.fit(X, y)
    grids[name] = gs

    best_model = gs.best_estimator_
    best_params = gs.best_params_
    best_score = gs.best_score_

    print(f"✅ {name} best CV AUC: {best_score:.3f}")
    print(f"✅ Best parameters: {best_params}")

    results.append({
        "Model": name,
        "CV_AUC": best_score
    })

# ------------------------------------------------------------
# 6️⃣ Summarize results
# ------------------------------------------------------------
results_df = pd.DataFrame(results).sort_values("CV_AUC", ascending=False)
print("\n📊 Internal Benchmark Summary:")
print(results_df.round(3))
results_df.to_csv("Internal_Binary_Benchmark_5Models.csv", index=False)

# ------------------------------------------------------------
# 7️⃣ Plot CV AUC comparison
# ------------------------------------------------------------
plt.figure(figsize=(7,5))
sns.barplot(data=results_df, x="CV_AUC", y="Model", palette="viridis", edgecolor="black")
plt.title("Internal 5-Fold CV AUC (Binary CRC vs Control)", fontsize=13, weight="bold")
plt.xlabel("Cross-Validated ROC-AUC"); plt.ylabel("")
sns.despine(); plt.tight_layout()
plt.savefig("Internal_Binary_Benchmark_5Models.png", dpi=600)
plt.show()

print("\n✅ Internal binary benchmarking complete!")
print("   • Results table: Internal_Binary_Benchmark_5Models.csv")
print("   • Plot: Internal_Binary_Benchmark_5Models.png")
print("------------------------------------------------------------")
print("👉 Next step: Select the top 2 models (by CV AUC) for external validation.")

# ============================================================
# 🧬 Logistic Regression — Internal Tuning + External Validation (Publication ROC)
# ============================================================

import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    roc_auc_score, accuracy_score, balanced_accuracy_score,
    f1_score, confusion_matrix, roc_curve, auc
)
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# ------------------------------------------------------------
# 1️⃣ Load datasets
# ------------------------------------------------------------
internal_tpm = pd.read_csv("Combined_CLR.csv", index_col=0)
internal_meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")
external_tpm = pd.read_csv("Combined_CLR_ext.csv", index_col=0)
external_meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix_ext.csv")

# ------------------------------------------------------------
# 2️⃣ Load PLS-DML genes (PLS₁ & PLS₃)
# ------------------------------------------------------------
pls_genes = pd.read_csv("PLS_TopGenes_Ranked_with_ComponentStats.csv")
focus_components = ["PLS_1", "PLS_3"]
marker_genes = pls_genes[pls_genes["Component"].isin(focus_components)]["Gene"].unique().tolist()
print(f"✅ Loaded {len(marker_genes)} PLS-DML genes from components {focus_components}")

# ------------------------------------------------------------
# 3️⃣ Align datasets
# ------------------------------------------------------------
internal_samples = internal_tpm.columns.intersection(internal_meta["Sample_ID"])
external_samples = external_tpm.columns.intersection(external_meta["Sample_ID"])
internal_tpm = internal_tpm[internal_samples]
external_tpm = external_tpm[external_samples]
internal_meta = internal_meta[internal_meta["Sample_ID"].isin(internal_samples)]
external_meta = external_meta[external_meta["Sample_ID"].isin(external_samples)]

common_genes = [g for g in marker_genes if g in internal_tpm.index and g in external_tpm.index]
print(f"✅ {len(common_genes)} overlapping genes between internal & external data")

if len(common_genes) < 5:
    raise ValueError("Too few overlapping genes between internal and external datasets!")

# ------------------------------------------------------------
# 4️⃣ Prepare binary labels (Control vs CRC)
# ------------------------------------------------------------
X_train = internal_tpm.loc[common_genes].T
X_ext   = external_tpm.loc[common_genes].T

# Internal: Healthy → 0, Adenoma/Cancer → 1
internal_meta["BinaryGroup"] = internal_meta["Group"].replace({
    "Healthy": 0, "Adenoma": 1, "Cancer": 1
}).astype(int)

# External: Control → 0, CRC/Case/Cancer → 1
external_meta["BinaryGroup"] = external_meta["Group"].replace({
    "Control": 0, "Healthy": 0, "CRC": 1, "Case": 1, "Cancer": 1
}).astype(int)

y_train = internal_meta["BinaryGroup"]
y_ext   = external_meta["BinaryGroup"]

print(f"✅ Training samples: {X_train.shape[0]} | Validation samples: {X_ext.shape[0]}")
print("Class distribution (internal):")
print(y_train.value_counts().rename({0: "Control", 1: "CRC"}))

# ------------------------------------------------------------
# 5️⃣ Define Logistic Regression model & tuning grid
# ------------------------------------------------------------
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(max_iter=5000, class_weight="balanced", random_state=42))
])

param_grid = {
    "logreg__penalty": ["l1", "l2"],
    "logreg__C": [0.05, 0.1, 0.5, 1, 2, 5],
    "logreg__solver": ["liblinear", "saga"]
}

# ------------------------------------------------------------
# 6️⃣ Tune with 5-fold stratified CV (internal)
# ------------------------------------------------------------
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
grid_search = GridSearchCV(pipe, param_grid, scoring="roc_auc", cv=cv, n_jobs=-1, verbose=1)
grid_search.fit(X_train, y_train)

best_model = grid_search.best_estimator_
best_params = grid_search.best_params_
best_score = grid_search.best_score_

print(f"\n✅ Best CV ROC-AUC (Internal): {best_score:.3f}")
print(f"✅ Best Parameters: {best_params}")

# ------------------------------------------------------------
# 7️⃣ Retrain best model on full internal dataset
# ------------------------------------------------------------
best_model.fit(X_train, y_train)
print("✅ Logistic Regression retrained on full internal cohort.")

# ------------------------------------------------------------
# 8️⃣ External Validation
# ------------------------------------------------------------
y_pred = best_model.predict(X_ext)
y_prob = best_model.predict_proba(X_ext)[:, 1]

metrics = {
    "Accuracy": accuracy_score(y_ext, y_pred),
    "BalancedAcc": balanced_accuracy_score(y_ext, y_pred),
    "F1_macro": f1_score(y_ext, y_pred, average="macro"),
    "AUC_Overall": roc_auc_score(y_ext, y_prob)
}

# One-vs-Rest AUC for each class
y_ext_bin = label_binarize(y_ext, classes=[0, 1])
auc_control = roc_auc_score(y_ext_bin[:, 0], 1 - y_prob)
auc_crc = roc_auc_score(y_ext_bin[:, 0], y_prob)
metrics["AUC_Control"] = auc_control
metrics["AUC_CRC"] = auc_crc

print("\n📈 External Validation Metrics:")
for k, v in metrics.items():
    print(f"{k:15s}: {v:.3f}")

# Confusion Matrix
cm = confusion_matrix(y_ext, y_pred)
cm_df = pd.DataFrame(cm, index=["Control", "CRC"], columns=["Pred_Control", "Pred_CRC"])
print("\n📊 Confusion Matrix:")
print(cm_df)

# ------------------------------------------------------------
# 9️⃣ ROC Curve (Publication Style)
# ------------------------------------------------------------
fpr, tpr, _ = roc_curve(y_ext, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(5,5))
plt.plot(fpr, tpr, color="#006400", lw=2.5, label=f"Overall AUC = {roc_auc:.3f}")
plt.plot([0,1],[0,1],"--",color="gray", lw=1.2)
plt.xlabel("False Positive Rate", fontsize=12, weight="bold")
plt.ylabel("True Positive Rate", fontsize=12, weight="bold")
plt.title("ROC Curve — External Validation (Logistic Regression)", fontsize=13, weight="bold")
plt.legend(frameon=True, loc="lower right")

# Make borders thick and black
for spine in plt.gca().spines.values():
    spine.set_linewidth(2)
    spine.set_edgecolor("black")

sns.despine()
plt.tight_layout()
plt.savefig("External_ROC_LogisticRegression_Publication.png", dpi=600, bbox_inches="tight")
plt.show()

# ------------------------------------------------------------
# 🔟 Save metrics
# ------------------------------------------------------------
pd.DataFrame([metrics]).to_csv("External_LogReg_Publication_Metrics.csv", index=False)

print("\n✅ Logistic Regression (publication version) complete — results saved to:")
print("   • External_LogReg_Publication_Metrics.csv")
print("   • External_ROC_LogisticRegression_Publication.png")



# ============================================================
# 🧬 Compare Gene Directionality: Internal vs External (PLS₁ & PLS₃ Robust Genes)
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from adjustText import adjust_text  # pip install adjustText if not installed

# -----------------------------
# 1️⃣ Load data
# -----------------------------
internal_tpm = pd.read_csv("Combined_CLR.csv", index_col=0)
external_tpm = pd.read_csv("Combined_CLR_ext.csv", index_col=0)
internal_meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")
external_meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix_ext.csv")

# -----------------------------
# 2️⃣ Load and filter robust PLS genes (PLS₁ & PLS₃ only)
# -----------------------------
pls_genes = pd.read_csv("PLS_TopGenes_Ranked_with_ComponentStats.csv")

focus_components = ["PLS_1", "PLS_3"]
pls_focus = pls_genes[pls_genes["Component"].isin(focus_components)].copy()

# Filter by robustness if column exists
if "Robustness" in pls_focus.columns:
    pls_focus = pls_focus[pls_focus["Robustness"] >= 0.75]

marker_genes = pls_focus["Gene"].unique().tolist()
print(f"✅ Loaded {len(marker_genes)} robust genes from components {focus_components}")

# -----------------------------
# 3️⃣ Identify overlapping genes
# -----------------------------
common_genes = [g for g in marker_genes if g in internal_tpm.index and g in external_tpm.index]
print(f"✅ {len(common_genes)} overlapping robust genes between internal & external datasets")

if len(common_genes) == 0:
    raise ValueError("No overlapping robust PLS-DML genes found between internal and external datasets!")

# -----------------------------
# 4️⃣ Align samples and assign binary groups
# -----------------------------
internal_meta = internal_meta.set_index("Sample_ID").loc[internal_tpm.columns]
external_meta = external_meta.set_index("Sample_ID").loc[external_tpm.columns]

internal_meta["BinaryGroup"] = internal_meta["Group"].replace({
    "Healthy": 0, "Control": 0,
    "Adenoma": 1, "Cancer": 1, "Case": 1, "CRC": 1
}).astype(int)

external_meta["BinaryGroup"] = external_meta["Group"].replace({
    "Control": 0, "Healthy": 0,
    "Case": 1, "CRC": 1, "Cancer": 1, "Adenoma": 1
}).astype(int)

# -----------------------------
# 5️⃣ Compute mean CLR abundance per group
# -----------------------------
def compute_directionality(expr_df, meta_df, genes):
    expr = expr_df.loc[genes].copy()
    expr_T = expr.T.join(meta_df["BinaryGroup"])
    mean_vals = expr_T.groupby("BinaryGroup").mean().T
    mean_vals.columns = ["Control_mean", "Case_mean"]
    mean_vals["Delta"] = mean_vals["Case_mean"] - mean_vals["Control_mean"]
    mean_vals["Direction"] = np.sign(mean_vals["Delta"])
    mean_vals["Trend"] = mean_vals["Direction"].map({
        1: "Up in disease", -1: "Down in disease", 0: "No change"
    })
    return mean_vals

internal_dir = compute_directionality(internal_tpm, internal_meta, common_genes)
external_dir = compute_directionality(external_tpm, external_meta, common_genes)

# Rename columns
internal_dir = internal_dir.add_suffix("_Internal")
external_dir = external_dir.add_suffix("_External")

# -----------------------------
# 6️⃣ Merge and compare directionality
# -----------------------------
merged = internal_dir.join(external_dir, how="inner")

# Compute absolute mean delta (for ranking)
merged["abs_mean_delta"] = (merged["Delta_Internal"].abs() + merged["Delta_External"].abs()) / 2

# Concordance logic
merged["Concordant"] = np.sign(merged["Delta_Internal"]) == np.sign(merged["Delta_External"])
merged["Concordant"] = merged["Concordant"].astype(int)
merged["Concordance_Label"] = merged["Concordant"].map({
    1: "Same direction", 0: "Opposite or Neutral"
})

merged.to_csv("PLS_DML_RobustGene_Directionality_Comparison.csv")
print("✅ Saved → PLS_DML_RobustGene_Directionality_Comparison.csv")

# -----------------------------
# 7️⃣ Summary statistics (descriptive only)
# -----------------------------
n_same = (merged["Concordant"] == 1).sum()
n_total = merged.shape[0]
perc_same = 100 * n_same / n_total

print(f"\n✅ Directionality concordance summary (PLS₁ & PLS₃ robust genes):")
print(f"  • Total overlapping robust genes: {n_total}")
print(f"  • Same direction (Internal vs External): {n_same} ({perc_same:.1f}%)")
print(f"  • Opposite or neutral: {n_total - n_same} ({100 - perc_same:.1f}%)")

summary_df = pd.DataFrame({
    "Total_Overlapping_Robust_Genes": [n_total],
    "Same_Direction_Genes": [n_same],
    "Proportion_Concordant": [n_same / n_total]
})
summary_df.to_csv("PLS_DML_RobustGene_Concordance_Summary.csv", index=False)
print("✅ Saved → PLS_DML_RobustGene_Concordance_Summary.csv")

# ============================================================
# 🎨 Publication-Ready Plots
# ============================================================
sns.set(style="whitegrid")

# ---- Scatter Plot ----
plt.figure(figsize=(8,8))
ax = sns.scatterplot(
    data=merged,
    x="Delta_Internal", y="Delta_External",
    hue="Concordance_Label",
    palette={"Same direction": "#1f77b4", "Opposite or Neutral": "#d62728"},
    s=90, edgecolor="black", alpha=0.9
)
plt.axhline(0, color="gray", lw=1.2)
plt.axvline(0, color="gray", lw=1.2)
plt.title("PLS₁ + PLS₃ Robust Genes: Directionality Concordance", fontsize=15, weight="bold", pad=15)
plt.xlabel("Δ CLR (Case − Control) — Internal Cohort", fontsize=13, weight="bold")
plt.ylabel("Δ CLR (Case − Control) — External Cohort", fontsize=13, weight="bold")

for spine in ax.spines.values():
    spine.set_linewidth(1.8)
    spine.set_edgecolor("black")

texts = []
for gene, row in merged.iterrows():
    texts.append(plt.text(row["Delta_Internal"], row["Delta_External"], gene,
                          fontsize=9, weight="bold", color="black"))
adjust_text(texts, arrowprops=dict(arrowstyle="-", color="gray", lw=0.4))
plt.legend(title="Concordance", frameon=True, fontsize=10, title_fontsize=11)
sns.despine()
plt.tight_layout()
plt.savefig("PLS_DML_RobustGene_Concordance_Scatter_Publication.png", dpi=600, bbox_inches="tight")
plt.show()

# ---- Bar plot for concordant genes ----
top_concordant = merged.query("Concordant == 1").copy()
bar_data = pd.DataFrame({
    "Gene": np.repeat(top_concordant.index, 2),
    "Cohort": np.tile(["Internal", "External"], len(top_concordant)),
    "Delta": np.hstack([top_concordant["Delta_Internal"], top_concordant["Delta_External"]])
})

plt.figure(figsize=(9,6))
sns.barplot(
    data=bar_data, x="Delta", y="Gene", hue="Cohort",
    palette=["#4C72B0", "#55A868"], edgecolor="black"
)
plt.axvline(0, color="gray", lw=1)
plt.xlabel("Δ CLR (Case - Control)", fontsize=12)
plt.ylabel("")
plt.title("Directionally Concordant PLS₁ + PLS₃ Genes Across Cohorts", fontsize=14, weight="bold")
plt.legend(title="Cohort", frameon=True)
sns.despine()
plt.tight_layout()
plt.savefig("PLS_DML_RobustGene_TopConcordant_BarPlot.png", dpi=600)
plt.show()

# ---- Heatmap (improved: slanted x-axis labels for publication) ----
heat_df = merged.loc[top_concordant.index, ["Delta_Internal", "Delta_External"]].copy()
heat_df.columns = ["Internal", "External"]

plt.figure(figsize=(5, len(heat_df)*0.4 + 1))
ax = sns.heatmap(
    heat_df,
    cmap="coolwarm", center=0, annot=True, fmt=".2f",
    linewidths=0.6, cbar_kws={"label": "Δ CLR (Case - Control)"}
)
plt.title("PLS₁ + PLS₃ Robust Genes — Directionality Concordance Heatmap",
          fontsize=12, weight="bold")
plt.xticks(rotation=30, ha="right", fontsize=10, weight="bold")
plt.yticks(fontsize=9)
for spine in ax.spines.values():
    spine.set_linewidth(1.5)
    spine.set_edgecolor("black")
sns.despine()
plt.tight_layout()
plt.savefig("PLS_DML_RobustGene_Concordance_Heatmap.png", dpi=600)
plt.show()

# ============================================================
# 🧪 Mann–Whitney U Test: ΔCLR (Internal vs External)
# ============================================================

from scipy.stats import mannwhitneyu

# Perform Mann–Whitney U test (two-sided)
u_stat, p_val = mannwhitneyu(merged["Delta_Internal"], merged["Delta_External"], alternative="two-sided")

# Compute medians for context
median_internal = merged["Delta_Internal"].median()
median_external = merged["Delta_External"].median()

print("\n📊 Mann–Whitney U Test (ΔCLR Internal vs External):")
print(f"  • U statistic = {u_stat:.3f}")
print(f"  • p-value     = {p_val:.4f}")
print(f"  • Median ΔCLR (Internal) = {median_internal:.3f}")
print(f"  • Median ΔCLR (External) = {median_external:.3f}")

# Save summary
mannwhitney_df = pd.DataFrame({
    "U_statistic": [u_stat],
    "p_value": [p_val],
    "Median_Internal": [median_internal],
    "Median_External": [median_external]
})
mannwhitney_df.to_csv("PLS_DML_RobustGene_MannWhitney_DeltaCLR.csv", index=False)
print("✅ Saved → PLS_DML_RobustGene_MannWhitney_DeltaCLR.csv")

# ============================================================
# 🧪 Paired Wilcoxon Signed-Rank Test (ΔCLR Internal vs External)
# ============================================================

from scipy.stats import wilcoxon

# Perform paired Wilcoxon test
wilcoxon_stat, wilcoxon_p = wilcoxon(
    merged["Delta_Internal"], merged["Delta_External"], alternative="two-sided"
)

# Compute medians for context
median_internal = merged["Delta_Internal"].median()
median_external = merged["Delta_External"].median()
median_diff = (merged["Delta_Internal"] - merged["Delta_External"]).median()

print("\n📊 Paired Wilcoxon Signed-Rank Test (ΔCLR Internal vs External):")
print(f"  • Wilcoxon statistic = {wilcoxon_stat:.3f}")
print(f"  • p-value             = {wilcoxon_p:.4f}")
print(f"  • Median ΔCLR (Internal) = {median_internal:.3f}")
print(f"  • Median ΔCLR (External) = {median_external:.3f}")
print(f"  • Median Difference (Internal − External) = {median_diff:.3f}")

# Save results
wilcoxon_df = pd.DataFrame({
    "Wilcoxon_statistic": [wilcoxon_stat],
    "p_value": [wilcoxon_p],
    "Median_Internal": [median_internal],
    "Median_External": [median_external],
    "Median_Difference": [median_diff]
})
wilcoxon_df.to_csv("PLS_DML_RobustGene_Wilcoxon_PairedTest.csv", index=False)
print("✅ Saved → PLS_DML_RobustGene_Wilcoxon_PairedTest.csv")

# ============================================================
# 🎨 Paired Line Plot (ΔCLR Internal vs External per Gene)
# ============================================================

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting
paired_df = pd.DataFrame({
    "Gene": merged.index,
    "Internal": merged["Delta_Internal"],
    "External": merged["Delta_External"]
}).reset_index(drop=True)

# Sort genes by internal ΔCLR for cleaner layout
paired_df = paired_df.sort_values("Internal", ascending=True)

plt.figure(figsize=(8, 6))
sns.set(style="whitegrid", font_scale=1.1)

# Plot paired lines connecting each gene across cohorts
for i, row in paired_df.iterrows():
    plt.plot(
        ["Internal", "External"],
        [row["Internal"], row["External"]],
        color="#999999", lw=1.2, alpha=0.8, zorder=1
    )

# Overlay points for each cohort
plt.scatter(
    np.repeat("Internal", len(paired_df)),
    paired_df["Internal"],
    color="#4C72B0", s=40, edgecolor="black", zorder=2, label="Internal"
)
plt.scatter(
    np.repeat("External", len(paired_df)),
    paired_df["External"],
    color="#55A868", s=40, edgecolor="black", zorder=2, label="External"
)

# Titles and labels
plt.title("Paired ΔCLR per Gene — Internal vs External Cohorts", fontsize=14, weight="bold", pad=12)
plt.ylabel("ΔCLR (Case − Control)", fontsize=12, weight="bold")
plt.xlabel("")
plt.xticks(fontsize=11, weight="bold")
plt.yticks(fontsize=10)
plt.legend(frameon=True, fontsize=10, title_fontsize=11)

# Thicker black borders for publication
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(1.8)
    spine.set_edgecolor("black")

# Annotate Wilcoxon result
p_label = "p < 0.001" if wilcoxon_p < 0.001 else f"p = {wilcoxon_p:.3f}"
plt.text(
    0.5, max(paired_df[["Internal","External"]].max()) * 0.95,
    f"Wilcoxon p-value: {p_label}",
    ha="center", va="top", fontsize=11, weight="bold"
)

sns.despine()
plt.tight_layout()
plt.savefig("PLS_DML_RobustGene_Wilcoxon_PairedLinePlot.png", dpi=600, bbox_inches="tight")
plt.show()

# ============================================================
# 🎨 Enhanced Paired Line Plot: Highlighting Directional Concordance
# ============================================================

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting
paired_df = pd.DataFrame({
    "Gene": merged.index,
    "Internal": merged["Delta_Internal"],
    "External": merged["Delta_External"],
    "Concordant": merged["Concordant"]
}).reset_index(drop=True)

# Sort by internal ΔCLR for consistent layout
paired_df = paired_df.sort_values("Internal", ascending=True)

# Map concordance to colors
color_map = {1: "#1f77b4", 0: "#d62728"}  # blue = same, red = opposite
paired_df["Color"] = paired_df["Concordant"].map(color_map)

plt.figure(figsize=(8, 6))
sns.set(style="whitegrid", font_scale=1.1)

# Plot paired lines
for _, row in paired_df.iterrows():
    plt.plot(
        ["Internal", "External"],
        [row["Internal"], row["External"]],
        color=row["Color"], lw=1.6, alpha=0.9, zorder=1
    )

# Overlay points
plt.scatter(
    np.repeat("Internal", len(paired_df)),
    paired_df["Internal"],
    color="#4C72B0", s=40, edgecolor="black", zorder=2, label="Internal"
)
plt.scatter(
    np.repeat("External", len(paired_df)),
    paired_df["External"],
    color="#55A868", s=40, edgecolor="black", zorder=2, label="External"
)

# Title and labels
plt.title("Paired ΔCLR per Gene — Internal vs External Cohorts", fontsize=14, weight="bold", pad=12)
plt.ylabel("ΔCLR (Case − Control)", fontsize=12, weight="bold")
plt.xlabel("")
plt.xticks(fontsize=11, weight="bold")
plt.yticks(fontsize=10)

# Legend
from matplotlib.lines import Line2D
custom_lines = [
    Line2D([0], [0], color="#1f77b4", lw=2, label="Same direction"),
    Line2D([0], [0], color="#d62728", lw=2, label="Opposite direction")
]
plt.legend(handles=custom_lines, title="Directional Concordance", frameon=True, fontsize=10, title_fontsize=11, loc="best")

# Annotate Wilcoxon result
p_label = "p < 0.001" if wilcoxon_p < 0.001 else f"p = {wilcoxon_p:.3f}"
plt.text(
    0.5, max(paired_df[["Internal","External"]].max()) * 0.95,
    f"Wilcoxon signed-rank {p_label}",
    ha="center", va="top", fontsize=11, weight="bold"
)

# Thick black axes
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(1.8)
    spine.set_edgecolor("black")

sns.despine()
plt.tight_layout()
plt.savefig("PLS_DML_RobustGene_Wilcoxon_PairedLinePlot_Enhanced.png", dpi=600, bbox_inches="tight")
plt.show()

# ============================================================
# 🧮 Power Analysis for PLS₁ and PLS₃ Components (Three-Group ANOVA)
# ============================================================

import pandas as pd
import numpy as np
from statsmodels.stats.power import FTestAnovaPower
import matplotlib.pyplot as plt
from scipy.stats import f_oneway

# -----------------------------
# 1️⃣ Load data (PLS scores + metadata)
# -----------------------------
pls  = pd.read_csv("Stable_PLS_Scores.csv")                 # contains Sample_ID, PLS_1, PLS_3
meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv") # contains Sample_ID, Group

merged = pd.merge(pls, meta[["Sample_ID", "Group"]], on="Sample_ID", how="inner")
print(f"✅ Merged dataset: {merged.shape[0]} samples")

print("\nGroup distribution:")
print(merged["Group"].value_counts())

# -----------------------------
# 2️⃣ Prepare group-specific arrays
# -----------------------------
healthy_pls1 = merged.loc[merged["Group"] == "Healthy", "PLS_1"]
adenoma_pls1 = merged.loc[merged["Group"] == "Adenoma", "PLS_1"]
cancer_pls1  = merged.loc[merged["Group"] == "Cancer",  "PLS_1"]

healthy_pls3 = merged.loc[merged["Group"] == "Healthy", "PLS_3"]
adenoma_pls3 = merged.loc[merged["Group"] == "Adenoma", "PLS_3"]
cancer_pls3  = merged.loc[merged["Group"] == "Cancer",  "PLS_3"]

# -----------------------------
# 3️⃣ Compute ANOVA effect sizes
# -----------------------------
def cohen_f_from_anova(groups):
    group_means = [np.mean(g) for g in groups]
    grand_mean  = np.mean(np.concatenate(groups))
    ss_between  = sum([len(g) * (m - grand_mean)**2 for g, m in zip(groups, group_means)])
    ss_within   = sum([sum((g - np.mean(g))**2) for g in groups])
    eta_sq      = ss_between / (ss_between + ss_within)
    f           = np.sqrt(eta_sq / (1 - eta_sq))
    return f, eta_sq

f_pls1, eta1 = cohen_f_from_anova([healthy_pls1, adenoma_pls1, cancer_pls1])
f_pls3, eta3 = cohen_f_from_anova([healthy_pls3, adenoma_pls3, cancer_pls3])

print(f"\n📊 Effect Sizes:")
print(f"  • PLS₁: f = {f_pls1:.3f}  (η² = {eta1:.3f})")
print(f"  • PLS₃: f = {f_pls3:.3f}  (η² = {eta3:.3f})")

# -----------------------------
# 4️⃣ Power analysis parameters
# -----------------------------
alpha = 0.05
power_target = 0.8
analysis = FTestAnovaPower()

n_pls1 = analysis.solve_power(effect_size=f_pls1, k_groups=3, alpha=alpha, power=power_target)
n_pls3 = analysis.solve_power(effect_size=f_pls3, k_groups=3, alpha=alpha, power=power_target)

print(f"\n📈 Required Total Sample Size (80% power, α=0.05):")
print(f"  • PLS₁ = {np.ceil(n_pls1)} total (~{np.ceil(n_pls1/3)} per group)")
print(f"  • PLS₃ = {np.ceil(n_pls3)} total (~{np.ceil(n_pls3/3)} per group)")

# -----------------------------
# 5️⃣ Achieved power at current sample size
# -----------------------------
n_actual = merged.shape[0]
power_pls1 = analysis.power(effect_size=f_pls1, nobs=n_actual, alpha=alpha, k_groups=3)
power_pls3 = analysis.power(effect_size=f_pls3, nobs=n_actual, alpha=alpha, k_groups=3)

print(f"\n🎯 Achieved Power (current N = {n_actual}):")
print(f"  • PLS₁ = {power_pls1:.3f}")
print(f"  • PLS₃ = {power_pls3:.3f}")

# -----------------------------
# 6️⃣ Save summary to CSV
# -----------------------------
out = pd.DataFrame({
    "Component": ["PLS₁", "PLS₃"],
    "Effect_Size_f": [f_pls1, f_pls3],
    "Eta_Squared": [eta1, eta3],
    "Required_Total_N_80pwr": [np.ceil(n_pls1), np.ceil(n_pls3)],
    "Required_PerGroup_N_80pwr": [np.ceil(n_pls1/3), np.ceil(n_pls3/3)],
    "Achieved_Power_CurrentN": [power_pls1, power_pls3],
    "Actual_Total_N": [n_actual, n_actual]
})
out.to_csv("PLS1_PLS3_Component_PowerSummary.csv", index=False)
print("✅ Saved → PLS1_PLS3_Component_PowerSummary.csv")

# -----------------------------
# 7️⃣ Publication power-curve plot (no gridlines)
# -----------------------------
samples = np.arange(30, 300, 5)
power_curve1 = analysis.power(effect_size=f_pls1, nobs=samples, alpha=alpha, k_groups=3)
power_curve3 = analysis.power(effect_size=f_pls3, nobs=samples, alpha=alpha, k_groups=3)

plt.figure(figsize=(6,5))
plt.plot(samples, power_curve1, lw=2.5, color="#1f77b4", label=f"PLS₁ (f={f_pls1:.2f})")
plt.plot(samples, power_curve3, lw=2.5, color="#ff7f0e", label=f"PLS₃ (f={f_pls3:.2f})")
plt.axhline(0.8, color="red", ls="--", lw=1.6, label="80 % Power Threshold")

plt.xlabel("Total Sample Size", fontsize=12, weight="bold")
plt.ylabel("Statistical Power", fontsize=12, weight="bold")
#plt.title("Power Analysis (One-Way ANOVA) for PLS₁ and PLS₃", fontsize=13, weight="bold")
plt.legend(frameon=True, fontsize=10)

# remove gridlines
ax = plt.gca()
ax.grid(False)

# thick black frame
for spine in ax.spines.values():
    spine.set_linewidth(2)
    spine.set_edgecolor("black")

plt.tight_layout()
plt.savefig("PowerAnalysis_PLS1_PLS3_Publication_NoGrid.png", dpi=600, bbox_inches="tight")
plt.show()

# ============================================================
# 🧮 Gene-Level Power Analysis (Three-Group ANOVA): PLS₁ & PLS₃ Genes
#    Groups: Healthy, Adenoma, Cancer
# ============================================================

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.stats.power import FTestAnovaPower

# -----------------------------
# 1) Load data
# -----------------------------
expr = pd.read_csv("Combined_CLR.csv", index_col=0)               # rows = genes, cols = Sample_ID
meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")      # includes Sample_ID, Group
pls  = pd.read_csv("PLS_TopGenes_Ranked_with_ComponentStats.csv") # includes Gene, Component, Robustness (optional)

# -----------------------------
# 2) Select PLS₁ + PLS₃ genes (optionally robust)
# -----------------------------
focus_components = ["PLS_1", "PLS_3"]
pls_focus = pls[pls["Component"].isin(focus_components)].copy()

# OPTIONAL: keep only robust genes if column exists
if "Robustness" in pls_focus.columns:
    pls_focus = pls_focus[pls_focus["Robustness"] >= 0.75]

genes = [g for g in pls_focus["Gene"].unique() if g in expr.index]
print(f"✅ Using {len(genes)} genes from {focus_components} present in the expression matrix.")

# -----------------------------
# 3) Align metadata to expression & restrict to 3 target groups
# -----------------------------
meta = meta.set_index("Sample_ID").loc[expr.columns]
meta = meta[meta["Group"].isin(["Healthy", "Adenoma", "Cancer"])].copy()

# Keep expression to aligned sample set
expr = expr[meta.index]

# Quick group sizes
grp_counts = meta["Group"].value_counts()
print("\nGroup sizes:")
print(grp_counts)

# -----------------------------
# 4) Helpers: ANOVA effect size per gene
# -----------------------------
def anova_effect_sizes(y, groups):
    """
    y: pandas Series of values indexed by sample
    groups: pandas Series of group labels aligned to y
    Returns (eta_sq, f) for one-way ANOVA
    """
    # Split into group arrays
    g_levels = ["Healthy", "Adenoma", "Cancer"]
    arrays = [y[groups == g].dropna().values for g in g_levels]

    # Need >= 2 values per group to meaningfully compute variance terms
    if any(len(a) < 2 for a in arrays):
        return np.nan, np.nan

    # Grand mean
    all_vals = np.concatenate(arrays)
    gm = np.mean(all_vals)

    # SS_between and SS_within
    ss_between = sum(len(a) * (np.mean(a) - gm)**2 for a in arrays)
    ss_within  = sum(((a - np.mean(a))**2).sum() for a in arrays)

    # Handle degenerate cases
    if (ss_between + ss_within) == 0:
        return np.nan, np.nan

    eta_sq = ss_between / (ss_between + ss_within)
    # Cohen's f from eta^2
    if eta_sq >= 1.0:
        f = np.nan
    else:
        f = np.sqrt(eta_sq / (1 - eta_sq))
    return eta_sq, f

analysis = FTestAnovaPower()
alpha = 0.05
target_power = 0.80
k_groups = 3

# -----------------------------
# 5) Per-gene ANOVA power analysis
# -----------------------------
records = []
for gene in genes:
    y = expr.loc[gene]
    groups = meta["Group"]

    eta_sq, f = anova_effect_sizes(y, groups)
    if not np.isfinite(f) or f <= 0:
        # Skip genes with zero/undefined effect size
        continue

    # Required TOTAL N for 80% power
    try:
        n_total_required = analysis.solve_power(effect_size=f, k_groups=k_groups,
                                                alpha=alpha, power=target_power)
    except Exception:
        n_total_required = np.nan

    # Achieved power at current N (only samples with non-NA gene values)
    n_current = y.dropna().shape[0]
    try:
        achieved_power = analysis.power(effect_size=f, nobs=n_current,
                                        alpha=alpha, k_groups=k_groups)
    except Exception:
        achieved_power = np.nan

    # Per-group current counts & means
    means = y.groupby(groups).mean()
    counts = y.groupby(groups).count()
    vars_  = y.groupby(groups).var()

    records.append({
        "Gene": gene,
        "Component": pls_focus.loc[pls_focus["Gene"] == gene, "Component"].values[0],
        "eta_sq": eta_sq,
        "Cohen_f": f,
        "N_total_required_80pwr": np.ceil(n_total_required) if np.isfinite(n_total_required) else np.nan,
        "N_per_group_required_80pwr": np.ceil(n_total_required / k_groups) if np.isfinite(n_total_required) else np.nan,
        "N_current_total": n_current,
        "Achieved_power_currentN": achieved_power,
        "Mean_Healthy": means.get("Healthy", np.nan),
        "Mean_Adenoma": means.get("Adenoma", np.nan),
        "Mean_Cancer":  means.get("Cancer",  np.nan),
        "Var_Healthy":  vars_.get("Healthy", np.nan),
        "Var_Adenoma":  vars_.get("Adenoma", np.nan),
        "Var_Cancer":   vars_.get("Cancer",  np.nan),
        "N_Healthy":    counts.get("Healthy", 0),
        "N_Adenoma":    counts.get("Adenoma", 0),
        "N_Cancer":     counts.get("Cancer",  0),
    })

df = pd.DataFrame(records).sort_values(["Component", "N_per_group_required_80pwr"])
df.to_csv("PLS1_PLS3_GeneLevel_Power_ANOVA.csv", index=False)
print(f"\n✅ Saved → PLS1_PLS3_GeneLevel_Power_ANOVA.csv ({df.shape[0]} genes)")

# -----------------------------
# 6) Summary tables
# -----------------------------
summary = df.groupby("Component")["N_per_group_required_80pwr"].agg(["median", "min", "max", "count"]).rename(
    columns={"count": "n_genes"})
print("\n📊 Required per-group N (80% power, α=0.05) — summary by component:")
print(summary)

ach_power_summary = df.groupby("Component")["Achieved_power_currentN"].describe()
print("\n📊 Achieved power at current N — summary by component:")
print(ach_power_summary)

summary.to_csv("PLS1_PLS3_GeneLevel_Power_ANOVA_Summary.csv")

# -----------------------------
# 7) Publication plots
# -----------------------------
sns.set(style="whitegrid", font_scale=1.05)

# (A) Barplot of genes with smallest required per-group N (cap for readability)
plot_cap = 300
df_bar = df[df["N_per_group_required_80pwr"].notna() & (df["N_per_group_required_80pwr"] <= plot_cap)].copy()
df_bar = df_bar.sort_values("N_per_group_required_80pwr", ascending=True)

plt.figure(figsize=(8, 7))
ax = sns.barplot(
    data=df_bar,
    x="N_per_group_required_80pwr",
    y="Gene",
    hue="Component",
    palette=["#1f77b4", "#ff7f0e"],
    edgecolor="black"
)
plt.axvline(100, color="red", ls="--", lw=1.6, label="100 per group")
plt.xlabel("Required Sample Size per Group (80% power, α=0.05)", weight="bold")
plt.ylabel("Gene", weight="bold")
plt.title("Gene-Level Power (ANOVA) for PLS₁ and PLS₃ Genes", weight="bold")

# Thicker black frame
for spine in ax.spines.values():
    spine.set_linewidth(2)
    spine.set_edgecolor("black")

plt.legend(title="Component", frameon=True)
sns.despine()
plt.tight_layout()
plt.savefig("PLS1_PLS3_GeneLevel_Power_Barplot.png", dpi=600, bbox_inches="tight")
plt.show()

plt.figure(figsize=(6.5,5.5))
ax = sns.boxplot(
    data=df, x="Component", y="N_per_group_required_80pwr",
    palette=["#1f77b4", "#ff7f0e"], showfliers=False
)
sns.stripplot(
    data=df, x="Component", y="N_per_group_required_80pwr",
    color="black", size=3, alpha=0.5, dodge=True
)
plt.ylabel("Required Sample Size per Group (80% power)", weight="bold")
plt.xlabel("")
plt.title("Distribution of Required N per Group by Component", weight="bold")

# Limit y-axis to remove very large outliers
plt.ylim(0, 300)

for spine in ax.spines.values():
    spine.set_linewidth(2)
    spine.set_edgecolor("black")

sns.despine()
plt.tight_layout()
plt.savefig("PLS1_PLS3_GeneLevel_Power_Distribution_trimmed.png", dpi=600, bbox_inches="tight")
plt.show()
##########################################################################
## EXTERNAL VALIDATION BENCHMARKING
##########################################################################
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    roc_auc_score, accuracy_score, balanced_accuracy_score,
    f1_score, cohen_kappa_score, matthews_corrcoef
)
import warnings
warnings.filterwarnings("ignore")

# ------------------------------------------------------------
# 1. Load internal data EXACTLY LIKE ORIGINAL ANALYSIS
# ------------------------------------------------------------
internal_tpm = pd.read_csv("Combined_ARG_VFDB_CLR_batch_corrected.csv", index_col=0).T
internal_meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")

print("Matrix shape AFTER transpose (genes × samples):", internal_tpm.shape)

# ------------------------------------------------------------
# 2. Load PLS genes (unchanged)
# ------------------------------------------------------------
pls = pd.read_csv("PLS_TopGenes_Ranked_with_ComponentStats.csv")
marker_genes = pls[pls["Component"].isin(["PLS_1","PLS_3"])]["Gene"].unique().tolist()
print("Loaded PLS marker genes:", len(marker_genes))

# ------------------------------------------------------------
# 3. Prepare labels (unchanged)
# ------------------------------------------------------------
internal_samples = internal_tpm.columns.intersection(internal_meta["Sample_ID"])
internal_tpm = internal_tpm[internal_samples]
internal_meta = internal_meta[internal_meta["Sample_ID"].isin(internal_samples)]

X = internal_tpm.loc[marker_genes].T
y = internal_meta["Group"].replace({
    "Healthy":0, "Adenoma":1, "Cancer":1
}).astype(int)

print("Final X shape:", X.shape)
print("Class counts:\n", y.value_counts())

# ------------------------------------------------------------
# 4. Models (unchanged)
# ------------------------------------------------------------
models = {
    "RandomForest": (
        RandomForestClassifier(random_state=42, class_weight="balanced"),
        {
            "n_estimators":[300,500],
            "max_depth":[5,10,None],
            "min_samples_split":[2,4],
            "max_features":["sqrt","log2"]
        }
    ),
    "GradientBoosting": (
        GradientBoostingClassifier(random_state=42),
        {
            "n_estimators":[200,500],
            "learning_rate":[0.01,0.05,0.1],
            "max_depth":[3,5],
            "subsample":[0.6,0.8,1.0]
        }
    ),
    "LogisticRegression": (
        Pipeline([
            ("scaler", StandardScaler()),
            ("logreg", LogisticRegression(max_iter=5000, class_weight="balanced", random_state=42))
        ]),
        {
            "logreg__penalty":["l1","l2"],
            "logreg__C":[0.05,0.1,0.5,1,2],
            "logreg__solver":["liblinear","saga"]
        }
    ),
    "SVM": (
        Pipeline([
            ("scaler", StandardScaler()),
            ("svm", SVC(probability=True, class_weight="balanced", random_state=42))
        ]),
        {
            "svm__C":[0.1,1,10],
            "svm__kernel":["linear","rbf"],
            "svm__gamma":["scale","auto"]
        }
    ),
    "DecisionTree": (
        DecisionTreeClassifier(random_state=42, class_weight="balanced"),
        {
            "max_depth":[3,5,10,None],
            "min_samples_split":[2,4,6],
            "criterion":["gini","entropy"]
        }
    )
}

# ------------------------------------------------------------
# 5. 5-fold benchmarking WITH MCC ADDED
# ------------------------------------------------------------
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
results = []

for name, (model, grid) in models.items():
    print(f"\n🔍 Tuning {name}...")
    gs = GridSearchCV(model, grid, scoring="roc_auc", cv=cv, n_jobs=-1)
    gs.fit(X, y)
    best = gs.best_estimator_

    # Evaluate exactly like original analysis (on full X,y)
    y_pred = best.predict(X)
    y_prob = best.predict_proba(X)[:,1]

    results.append({
        "Model": name,
        "CV_AUC": gs.best_score_,
        "Accuracy": accuracy_score(y, y_pred),
        "BalancedAcc": balanced_accuracy_score(y, y_pred),
        "F1": f1_score(y, y_pred, average="macro"),
        "Kappa": cohen_kappa_score(y, y_pred),
        "MCC": matthews_corrcoef(y, y_pred)
    })

results_df = pd.DataFrame(results).sort_values("CV_AUC", ascending=False)
print("\n=== FINAL BENCHMARKING RESULTS (with MCC) ===")
print(results_df)

results_df.to_csv("Internal_Binary_Benchmark_with_MCC.csv", index=False)
###################################################################################
### Leave-One-Cohort Out (Stratified AUC) and external validation using LR
##################################################################################
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score, f1_score,
    cohen_kappa_score, matthews_corrcoef,
    roc_auc_score
)
import seaborn as sns
sns.set_style("whitegrid")

print("📌 Loading data...")

# =========================================================
# 1. LOAD INTERNAL + EXTERNAL (correct orientation)
# =========================================================

internal_tpm = pd.read_csv("Combined_ARG_VFDB_CLR_batch_corrected.csv", index_col=0)
external_tpm = pd.read_csv("Combined_CLR_ext.csv", index_col=0).T

internal_meta = pd.read_csv("Metadata_Aligned_to_FilteredMatrix.csv")
external_meta = pd.read_csv("metadata_ext.csv")

pls = pd.read_csv("PLS_TopGenes_Ranked_with_ComponentStats.csv")
pls_genes_raw = pls[pls["Component"].isin(["PLS_1", "PLS_3"])]["Gene"].unique().tolist()
print(f"Loaded {len(pls_genes_raw)} raw PLS genes.")


# =========================================================
# 2. HARMONIZE GENE NAMES
# =========================================================

def clean_name(x):
    return x.replace("VF_", "").replace("ARG_", "").replace(" ", "").strip()

internal_tpm.columns = [clean_name(c) for c in internal_tpm.columns]
external_tpm.columns = [clean_name(c) for c in external_tpm.columns]
pls_genes = [clean_name(g) for g in pls_genes_raw]

print("✔ Gene name harmonization complete.")


# =========================================================
# 3. ALIGN SAMPLES
# =========================================================

common_internal = internal_tpm.index.intersection(internal_meta["Sample_ID"])
internal_tpm = internal_tpm.loc[common_internal]
internal_meta = internal_meta[internal_meta["Sample_ID"].isin(common_internal)]
internal_meta = internal_meta.set_index("Sample_ID").loc[internal_tpm.index]

common_external = external_tpm.index.intersection(external_meta["Sample_ID"])
external_tpm = external_tpm.loc[common_external]
external_meta = external_meta[external_meta["Sample_ID"].isin(common_external)]
external_meta = external_meta.set_index("Sample_ID").loc[external_tpm.index]

print(f"✔ Internal samples: {internal_tpm.shape}")
print(f"✔ External samples: {external_tpm.shape}")


# =========================================================
# 4. MAKE BINARY LABELS
# =========================================================

internal_meta["Binary"] = internal_meta["Group"].replace({
    "Healthy": 0, "Adenoma": 1, "Cancer": 1
}).astype(int)

external_meta["Binary"] = external_meta["Group"].replace({
    "Control": 0, "Healthy": 0,
    "CRC": 1, "Case": 1, "Cancer": 1, "Adenoma": 1
}).astype(int)

# =========================================================
# 5. INTERSECT FEATURES
# =========================================================

internal_genes = set(internal_tpm.columns)
external_genes = set(external_tpm.columns)
pls_set = set(pls_genes)

marker_genes = list(internal_genes & external_genes & pls_set)

print(f"✔ {len(marker_genes)} intersecting PLS genes after cleaning.")

if len(marker_genes) < 5:
    print("❗ WARNING: Very few overlapping PLS genes. Model may be unstable.")

X_internal = internal_tpm[marker_genes].copy()
y_internal = internal_meta["Binary"]

X_external = external_tpm[marker_genes].copy()
y_external = external_meta["Binary"]


# =========================================================
# 6. LOGISTIC REGRESSION PIPELINE (UNCHANGED)
# =========================================================

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(max_iter=5000, class_weight="balanced", random_state=42))
])

param_grid = {
    "logreg__penalty": ["l1", "l2"],
    "logreg__C": [0.05, 0.1, 0.5, 1, 2, 5],
    "logreg__solver": ["liblinear", "saga"]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def eval_model(model, X, y):
    p = model.predict(X)
    pr = model.predict_proba(X)[:,1]
    return {
        "Accuracy": accuracy_score(y, p),
        "BalancedAcc": balanced_accuracy_score(y, p),
        "F1": f1_score(y, p, average="macro"),
        "Kappa": cohen_kappa_score(y, p),
        "MCC": matthews_corrcoef(y, p),
        "AUC": roc_auc_score(y, pr)
    }


# =========================================================
# 7. LOCO — Cohort_1, Cohort_2, Cohort_3
# =========================================================

print("\n📌 Running LOCO evaluation...")

loco_results = []

for cohort in ["Cohort_1", "Cohort_2", "Cohort_3"]:
    train_idx = internal_meta["Project"] != cohort
    test_idx  = internal_meta["Project"] == cohort

    if y_internal.loc[test_idx].nunique() < 2:
        print(f"Skipping {cohort}: only one class present.")
        continue

    print(f"🔹 LOCO {cohort}")

    gs = GridSearchCV(pipe, param_grid, scoring="roc_auc", cv=cv, n_jobs=-1)
    gs.fit(X_internal.loc[train_idx], y_internal.loc[train_idx])
    best_model = gs.best_estimator_

    res = eval_model(best_model, X_internal.loc[test_idx], y_internal.loc[test_idx])
    res["Cohort"] = cohort
    loco_results.append(res)

loco_df = pd.DataFrame(loco_results)
loco_df.to_csv("LOCO_Results.csv", index=False)

print("\nLOCO:")
print(loco_df)


# =========================================================
# 8. INTERNAL → EXTERNAL 
# =========================================================

print("\n📌 Internal → External...")

gs = GridSearchCV(pipe, param_grid, scoring="roc_auc", cv=cv, n_jobs=-1)
gs.fit(X_internal, y_internal)

internal_model = gs.best_estimator_
res_internal_to_ext = eval_model(internal_model, X_external, y_external)
res_internal_to_ext["Cohort"] = "Internal→External"

cross_df = pd.DataFrame([res_internal_to_ext])
cross_df.to_csv("CrossCohort_Results.csv", index=False)

print("\nInternal → External:")
print(cross_df)

print("\n🎉 FINISHED.")
