# -*- coding: utf-8 -*-
"""CRC_ANALYSIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WeGjMOdUMO3wcu_jsHeQZwHminwJmKEs
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# === Load importance summary ===
summary_df = pd.read_csv("/content/consistent_species_feature_summary.csv")

# === Select top N species ===
top_n = 50
top_df = summary_df.head(top_n)

# === Set visual theme ===
sns.set_theme(style="white")  # No grid

# === Plot ===
plt.figure(figsize=(9, 7))
bars = plt.barh(
    y=top_df["Species"],
    width=top_df["Importance_Mean"],
    xerr=top_df["Importance_STD"],
    color="#009E73",  # skyblue
    edgecolor='black',
    linewidth=0.7,
    capsize=2
)

# Invert Y-axis for descending rank
plt.gca().invert_yaxis()

# Labels and layout
plt.xlabel("Mean Importance (± Std Dev)", fontsize=11, color='black')
plt.xticks(fontsize=10, color='black')
plt.yticks(fontsize=9, color='black')

# Remove background grid
plt.grid(False)

# Set thicker outer borders
ax = plt.gca()
for spine in ["top", "right", "bottom", "left"]:
    ax.spines[spine].set_visible(True)
    ax.spines[spine].set_linewidth(2)

plt.tight_layout()

# Save as high-res TIFF
plt.savefig("General_PERMUTATION_Importance.tiff", dpi=600, bbox_inches="tight", format="tiff")
plt.show()

import pandas as pd

# Load the data
df = pd.read_csv("consistent_species_feature_summary _raw.csv")

# Remove any row where 'Species' contains 'relative_ab'
df = df[~df['Species'].str.contains('relative_ab', case=False, na=False)]

# Step 2: Keep only rows where Consistency == 1
df_consistent = df[df['Consistency'] == 1]

# Step 3: Sort by Importance_Mean in descending order
df_sorted = df_consistent.sort_values(by='Importance_Mean', ascending=False)

# Step 4: Save the result
df_sorted.to_csv("Consistent_Species_Sorted.csv", index=False)

print("✅ File saved as 'Consistent_Species_Sorted.csv'")

"""Random forest Log Loss on Consistent Random forest Features

"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import log_loss

# Load your data
expr_df = pd.read_csv("/content/Expression_Matrix_Aligned.csv", index_col=0)
meta_df = pd.read_csv("/content/Aligned_metadata.csv")
rf_species_df = pd.read_csv("/content/Consistent_Species_Sorted.csv")

# Align sample IDs
meta_df["Sample_ID"] = meta_df["Sample_ID"].astype(str).str.strip()
expr_df.index = expr_df.index.astype(str).str.strip()
meta_df = meta_df.set_index("Sample_ID").loc[expr_df.index]

# Encode group labels
le = LabelEncoder()
meta_df["Group_Code"] = le.fit_transform(meta_df["Group"])
class_names = le.classes_

# Initialize results
results = []

# Loop through each species
for species in rf_species_df["Species"]:
    if species not in expr_df.columns:
        continue

    meta_df["Species_Abundance"] = expr_df[species]

    # Prevalence/variance check
    if meta_df["Species_Abundance"].std() == 0:
        continue

    try:
        X = meta_df[["Species_Abundance"]]
        y = meta_df["Group_Code"]

        model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
        model.fit(X, y)

        # Predict probabilities and compute log-loss
        preds = model.predict_proba(X)
        loss = log_loss(y, preds)

        result_row = {
            "Species": species,
            "Log_Loss": round(loss, 4)
        }

        results.append(result_row)

    except Exception as e:
        print(f"⚠️ Skipping {species} due to error: {e}")
        continue

# Save results
if results:
    df_results = pd.DataFrame(results).sort_values("Log_Loss")
    df_results.to_csv("RF_Log_Loss_Per_Species.csv", index=False)
    print("✅ Random Forest log-loss results saved to 'RF_Log_Loss_Per_Species.csv'")
    df_results.head()
else:
    print("⚠️ No valid species were processed. Check for low variance or missing data.")

"""Plot for the RF log loss from above"""

# Imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the log loss data
log_loss_df = pd.read_csv("/content/RF_Log_Loss_Per_Species.csv")  # Adjust path if needed
log_loss_df = log_loss_df.sort_values("Log_Loss")

# Nature-style plot settings
sns.set_theme(style="whitegrid", font_scale=1.3, rc={
    "axes.labelsize": 14,
    "axes.titlesize": 16,
    "xtick.labelsize": 12,
    "ytick.labelsize": 11,
    "axes.edgecolor": "black",
    "grid.linestyle": "--"
})

# Create the plot
plt.figure(figsize=(8, 12))
ax = sns.barplot(
    data=log_loss_df,
    x="Log_Loss",
    y="Species",
    palette="viridis",
    edgecolor='black',      # Bar border color
    linewidth=2            # Bar border thickness
)

# Add vertical dashed reference line at Log Loss = 0.1
plt.axvline(0.1, color="red", linestyle="--", linewidth=2, label="Log Loss = 0.1")

# Customize plot
#plt.title("Random Forest Log Loss per Species", fontsize=16, pad=10)
plt.xlabel("Log Loss (lower = better classifier)", fontsize=14)
plt.ylabel("Species", fontsize=14)
plt.legend(loc="upper right", fontsize=12, frameon=True)
plt.tight_layout()

# Save high-resolution version
plt.savefig("RF_Log_Loss_Per_Species_NatureStyle_Bordered.png", dpi=600, bbox_inches='tight')
plt.show()

"""Selection of species with lower log loss and statiscal analysis and comparisons with boxplots visualization

Run Ordinal forest for the Log loss features from above

Save Ordinal Forest evaluation metrics
"""

# ===============================
# Ordinal Forest-Style Classifier for Microbiome Data
# ===============================

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import classification_report, confusion_matrix, f1_score, make_scorer
import matplotlib.pyplot as plt
import seaborn as sns

# -------------------------------
# Step 1: Load Data
# -------------------------------
logloss = pd.read_csv("RF_Log_Loss_Per_Species.csv")
expr = pd.read_csv("Expression_Matrix_Aligned.csv")
meta = pd.read_csv("Aligned_metadata.csv")

# -------------------------------
# Step 2: Filter Species by Log Loss (≤ 0.1)
# -------------------------------
filtered_logloss = logloss[logloss["Log_Loss"] <= 0.1]
shortlisted_species_set = set(filtered_logloss["Species"].dropna().astype(str).str.strip())
expr_columns_set = set(expr.columns.astype(str).str.strip())

# -------------------------------
# Step 3: Identify Valid Species Present in Expression Matrix
# -------------------------------
valid_species = sorted(expr_columns_set.intersection(shortlisted_species_set))

print(f"📉 Species with log loss ≤ 0.1: {len(shortlisted_species_set)}")
print(f"✅ Found {len(valid_species)} valid shortlisted species.")

if len(valid_species) == 0:
    raise ValueError("No valid shortlisted species found in expression matrix columns.")

# -------------------------------
# Step 4: Subset Expression Matrix
# -------------------------------
expr_filtered = expr[["Sample_ID"] + valid_species]

# -------------------------------
# Step 5: Merge with Metadata
# -------------------------------
merged = pd.merge(meta, expr_filtered, on="Sample_ID", how="inner")
merged['Group'] = pd.Categorical(merged['Group'], categories=['Healthy', 'Adenoma', 'Cancer'], ordered=True)

# -------------------------------
# Step 6: Drop Missing Data
# -------------------------------
merged = merged.dropna(subset=valid_species + ['Group'])

if merged.empty:
    raise ValueError("No rows remaining after dropping missing values.")

# -------------------------------
# Step 7: Prepare Features and Target
# -------------------------------
X = merged[valid_species].apply(pd.to_numeric, errors='coerce')
y = merged[['Group']]

# Drop columns with too many missing values
na_fraction = X.isna().mean()
X = X.loc[:, na_fraction <= 0.5]

# Impute remaining NAs with median
X = X.fillna(X.median())

# Remove constant columns
X = X.loc[:, X.nunique() > 1]

if X.empty:
    raise ValueError("All features were removed due to missing or constant values.")

# Store the final feature names BEFORE any potential conversion to numpy
feature_names = X.columns.tolist()

# -------------------------------
# Step 8: Encode Group as Ordinal
# -------------------------------
encoder = OrdinalEncoder(categories=[['Healthy', 'Adenoma', 'Cancer']])
y_encoded = encoder.fit_transform(y).ravel().astype(int)

# -------------------------------
# Step 9: Train/Test Split
# -------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.33, random_state=42, stratify=y_encoded)

# -------------------------------
# Step 10: Train Random Forest Classifier
# -------------------------------
rf = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train, y_train)

# -------------------------------
# Step 10a: Cross-Validation Evaluation
# -------------------------------
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
# Use the original DataFrame X for cross-validation if needed, or ensure X_train columns match
# If X_train/X_test are numpy arrays, cross_val_score should handle it as long as shapes are consistent
accuracy_scores = cross_val_score(rf, X, y_encoded, cv=cv, scoring='accuracy')
f1_macro_scores = cross_val_score(rf, X, y_encoded, cv=cv, scoring=make_scorer(f1_score, average='macro'))

print("\n🔁 Cross-Validation Results (10-fold):")
print(f"  - Accuracy: {accuracy_scores.mean():.4f} ± {accuracy_scores.std():.4f}")
print(f"  - F1 Macro: {f1_macro_scores.mean():.4f} ± {f1_macro_scores.std():.4f}")

# -------------------------------
# Step 10b: Negative Control - Label Shuffling
# -------------------------------
from sklearn.utils import shuffle
y_shuffled = shuffle(y_encoded, random_state=42)
shuffled_scores = cross_val_score(rf, X, y_shuffled, cv=cv, scoring='accuracy')
print(f"\n🔀 Shuffled Label Accuracy (control): {shuffled_scores.mean():.4f}")

# -------------------------------
# Step 11: Predict and Evaluate on Test Set
# -------------------------------
y_pred = rf.predict(X_test)

print("\n📊 Classification Report:")
# Use the original encoder categories for target names
print(classification_report(y_test, y_pred, target_names=encoder.categories_[0]))

print("\n📊 Confusion Matrix:")
conf_matrix = confusion_matrix(y_test, y_pred)
# Use the original encoder categories for index and columns
conf_df = pd.DataFrame(conf_matrix, index=encoder.categories_[0], columns=encoder.categories_[0])
print(conf_df)

###########################################################################
# -------------------------------
# Step 11a: Compute Multiclass AUROC
# -------------------------------
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize

# Binarize true labels
y_test_bin = label_binarize(y_test, classes=[0, 1, 2])
# Get predicted probabilities
y_proba = rf.predict_proba(X_test)

# Compute AUROC for each class
auroc_per_class = roc_auc_score(y_test_bin, y_proba, average=None)
auroc_macro = roc_auc_score(y_test_bin, y_proba, average='macro')

# Display results
for idx, class_name in enumerate(encoder.categories_[0]):
    print(f"🟢 AUROC - {class_name}: {auroc_per_class[idx]:.4f}")
print(f"⭐ Macro-average AUROC: {auroc_macro:.4f}")

from sklearn.metrics import classification_report

# Re-generate classification report as dict
report_dict = classification_report(y_test, y_pred, target_names=encoder.categories_[0], output_dict=True)

# Prepare summary dictionary
summary_metrics = {
    "Metric": [],
    "Value": []
}

# Add AUROC
for idx, class_name in enumerate(encoder.categories_[0]):
    summary_metrics["Metric"].append(f"AUROC - {class_name}")
    summary_metrics["Value"].append(auroc_per_class[idx])

summary_metrics["Metric"].append("AUROC - Macro Average")
summary_metrics["Value"].append(auroc_macro)

# Add accuracy and F1 scores
summary_metrics["Metric"].append("Cross-Validation Accuracy")
summary_metrics["Value"].append(f"{accuracy_scores.mean():.4f} ± {accuracy_scores.std():.4f}")

summary_metrics["Metric"].append("Cross-Validation F1 Macro")
summary_metrics["Value"].append(f"{f1_macro_scores.mean():.4f} ± {f1_macro_scores.std():.4f}")

summary_metrics["Metric"].append("Shuffled Label Accuracy (control)")
summary_metrics["Value"].append(f"{shuffled_scores.mean():.4f}")

# Add classification report metrics (macro avg, weighted avg, etc.)
for key in report_dict:
    if isinstance(report_dict[key], dict):
        for subkey in report_dict[key]:
            summary_metrics["Metric"].append(f"{key} - {subkey}")
            summary_metrics["Value"].append(report_dict[key][subkey])

# Save to CSV
summary_df = pd.DataFrame(summary_metrics)
summary_df.to_csv("Ordinal_RF_Full_Evaluation_Metrics.csv", index=False)

print("\n✅ All evaluation metrics saved to 'Ordinal_RF_Full_Evaluation_Metrics.csv'")

"""Plot Ordinal forest Species importance"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Feature importance from Random Forest
# Use the stored feature_names variable
importances = pd.Series(rf.feature_importances_, index=feature_names)
top17 = importances.sort_values(ascending=False).head(17)

# Plotting
plt.figure(figsize=(7, 6))
sns.set(style="white")

# Use seaborn barplot with edgecolor and linewidth for thick bars
#ax = sns.barplot(x=top17.values, y=top17.index, edgecolor='black', linewidth=2.5, palette='viridis')

ax = sns.barplot(
    x=top17.values,
    y=top17.index,
    color='blue',       # uniform bar color
    edgecolor='black',
    linewidth=2.5
)


# Aesthetics
#plt.title("Top 17 Important Species (Ordinal Forest-style)", fontsize=16, fontweight='bold')
plt.xlabel("Feature Importance", fontsize=14)
plt.ylabel("", fontsize=14)

# Thicken axes borders
ax = plt.gca()
ax.grid(False)
for spine in ax.spines.values():
    spine.set_linewidth(2)

# Tight layout and display
plt.tight_layout()
plt.savefig("Top_Important_Species2.png", dpi=600)
plt.show()


# -------------------------------
# Step 13: Save Top Features to CSV
# -------------------------------
top_features = importances.sort_values(ascending=False)
top_features.head(17).to_csv("Top_Important_Species.csv", header=["Importance"])
print("\n💾 Top  species saved to 'Top_Important_Species.csv'")

"""Plot PCA and TSNE to visualize sample clustering of the top species"""

##############################################################
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import pandas as pd

# Define custom group colors
group_colors = {
    "Adenoma": "#984ea3",  # purple
    "Cancer": "#4daf4a",   # green
    "Healthy": "#ffcc00"   # yellow
}

# -------------------------------
# PCA Visualization (with explained variance)
# -------------------------------
pca = PCA(n_components=2)
pcs = pca.fit_transform(X)
explained_var = pca.explained_variance_ratio_ * 100  # convert to percentage

# Create DataFrame for plotting
pc_df = pd.DataFrame(pcs, columns=['PC1', 'PC2'])
pc_df['Group'] = merged['Group'].values

# Plot
plt.figure(figsize=(8, 6))
sns.set(style="white")

sns.scatterplot(
    data=pc_df,
    x='PC1', y='PC2',
    hue='Group',
    palette=group_colors,
    s=100, edgecolor='black', linewidth=1.5
)

# Titles and axis labels with variance contribution
#plt.title("PCA of Samples by Group", fontsize=16, fontweight='bold')
plt.xlabel(f"PC 1 ({explained_var[0]:.2f}%)", fontsize=14, fontweight='bold')
plt.ylabel(f"PC 2 ({explained_var[1]:.2f}%)", fontsize=14, fontweight='bold')

# Aesthetic styling
ax = plt.gca()
ax.grid(False)
for spine in ax.spines.values():
    spine.set_linewidth(2)

plt.tight_layout()
#plt.savefig("PCA_Samples_By_Group.png", dpi=600)
plt.show()

# -------------------------------
# t-SNE Visualization (Step 15)
# -------------------------------
tsne = TSNE(n_components=2, perplexity=30, random_state=42, init='pca', learning_rate='auto')
tsne_coords = tsne.fit_transform(X)
tsne_df = pd.DataFrame(tsne_coords, columns=['TSNE1', 'TSNE2'])
tsne_df['Group'] = merged['Group'].values

plt.figure(figsize=(5, 4))
sns.set(style="white")

sns.scatterplot(
    data=tsne_df,
    x='TSNE1', y='TSNE2',
    hue='Group',
    palette=group_colors,
    s=100, edgecolor='black', linewidth=1.5
)

#plt.title("t-SNE of Samples by Group", fontsize=16, fontweight='bold')
plt.xlabel("t-SNE 1", fontsize=14)
plt.ylabel("t-SNE 2", fontsize=14)

# Reduce legend font size
plt.legend(title='', fontsize=9, title_fontsize=8, loc='best')

# Remove gridlines and thicken plot borders
ax = plt.gca()
ax.grid(False)
for spine in ax.spines.values():
    spine.set_linewidth(2)

plt.tight_layout()
plt.savefig("tSNE_Samples_By_Group.png", dpi=600)
plt.show()

"""Statistical analysis of the distribution of the top species"""

# -------------------------------
# Step 17: Kruskal-Wallis Test + Multi-Panel Boxplots for All 16 Species
# -------------------------------
from scipy.stats import kruskal
from statsmodels.stats.multitest import multipletests
import os
import math

# Use all 12 species from model input
all_species = list(X.columns)

# Create output directory for plots
os.makedirs("feature_plots", exist_ok=True)

kruskal_results = []

# Perform Kruskal-Wallis test for each species
for species in all_species:
    groups = [merged[merged['Group'] == g][species].dropna() for g in ['Healthy', 'Adenoma', 'Cancer']]
    stat, p_value = kruskal(*groups)
    kruskal_results.append({'Species': species, 'Kruskal_Statistic': stat, 'P_Value': p_value})

# Convert to DataFrame
kruskal_df = pd.DataFrame(kruskal_results)

# Apply FDR correction (Benjamini-Hochberg)
kruskal_df['FDR_Adjusted_P'] = multipletests(kruskal_df['P_Value'], method='fdr_bh')[1]

# Save test results
kruskal_df.to_csv("kruskal_test_results.csv", index=False)

# Filter to significant species (FDR < 0.05)
significant_species = kruskal_df[kruskal_df['FDR_Adjusted_P'] < 0.05]['Species'].tolist()

print(f"\n🧪 Kruskal-Wallis test completed on all 12 model species.")
print(f"✅ {len(significant_species)} species were significant (FDR < 0.05)")
print("📄 Results saved to 'kruskal_test_results.csv'")

# -------------------------------
# Step 18: Multi-Panel Boxplot with log2 Abundance
# -------------------------------
# Log-transform abundance values
plot_data = merged.copy()
for species in significant_species:
    plot_data[species] = np.log2(plot_data[species] + 1)

# Define custom color palette
group_colors = {
    "Adenoma": "#984ea3",
    "Cancer": "#4daf4a",
    "Healthy": "#ffcc00"
}
palette = [group_colors[g] for g in ['Healthy', 'Adenoma', 'Cancer']]


# Define border thickness
border_width = 2

# Layout for multi-panel figure
n_species = len(significant_species)
cols = 4
rows = math.ceil(n_species / cols)
fig, axes = plt.subplots(rows, cols, figsize=(4 * cols, 4 * rows), sharey=False)
axes = axes.flatten()

# Plot each species
for i, species in enumerate(significant_species):
    ax = axes[i]
    sns.boxplot(data=plot_data, x='Group', y=species, palette=group_colors, ax=ax, linewidth=border_width)
    p_val = kruskal_df.loc[kruskal_df['Species'] == species, 'FDR_Adjusted_P'].values[0]

    # Format title with bold species name and FDR p-value
    ax.set_title(f"{species}\nFDR p = {p_val:.2e}", fontsize=10, fontweight='bold')
    ax.set_xlabel("")
    ax.set_ylabel("log2(abundance + 1)")
    ax.tick_params(axis='x', rotation=20)

    # Thicken borders
    for spine in ax.spines.values():
        spine.set_linewidth(border_width)


    # Increase border thickness of each subplot
    for spine in ax.spines.values():
        spine.set_linewidth(border_width)

# Remove unused subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

#fig.suptitle("log2 Abundance of Significant Species by Group", fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.96])

# Save and show plot
plt.savefig("feature_plots_multi_species_boxplot_log2.png", dpi=600)
plt.show()

print("📊 Multi-panel boxplot saved to 'feature_plots/multi_species_boxplot_log2.png'")


# Melt the data into long format for easy analysis
long_df = plot_data.melt(
    id_vars='Group',
    value_vars=significant_species,
    var_name='Species',
    value_name='log2_Abundance'
)

# Save to CSV
long_df.to_csv("Significant_Species_Abundance_LongFormat.csv", index=False)

print("✅ Raw plot data saved to 'Significant_Species_Abundance_LongFormat.csv'")

import pandas as pd
import numpy as np

# -------------------------------
# Step 1: Load the long format abundance data
# -------------------------------
df = pd.read_csv("Significant_Species_Abundance_LongFormat.csv")

# -------------------------------
# Step 2: Calculate group-wise mean abundance per species
# -------------------------------
groupwise_means = df.groupby(['Species', 'Group'])['log2_Abundance'].mean().unstack()

# -------------------------------
# Step 3: Compute log2 fold changes
# -------------------------------
groupwise_means['log2FC_Cancer_vs_Healthy'] = groupwise_means['Cancer'] - groupwise_means['Healthy']
groupwise_means['log2FC_Adenoma_vs_Healthy'] = groupwise_means['Adenoma'] - groupwise_means['Healthy']
groupwise_means['log2FC_Cancer_vs_Adenoma'] = groupwise_means['Cancer'] - groupwise_means['Adenoma']

# -------------------------------
# Step 4: Compute raw fold changes from log2 FC
# -------------------------------
groupwise_means['FC_Cancer_vs_Healthy'] = 2 ** groupwise_means['log2FC_Cancer_vs_Healthy']
groupwise_means['FC_Adenoma_vs_Healthy'] = 2 ** groupwise_means['log2FC_Adenoma_vs_Healthy']
groupwise_means['FC_Cancer_vs_Adenoma'] = 2 ** groupwise_means['log2FC_Cancer_vs_Adenoma']

# -------------------------------
# Step 5: Round values for readability and save
# -------------------------------
groupwise_means_rounded = groupwise_means.round(4)
groupwise_means_rounded.to_csv("Groupwise_Abundance_and_FoldChange.csv")

print("✅ Fold change analysis complete. Results saved to 'Groupwise_Abundance_and_FoldChange.csv'")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# -----------------------------
# Step 1: Load the fold change data
# -----------------------------
df = pd.read_csv("Groupwise_Abundance_and_FoldChange.csv", index_col=0)

# -----------------------------
# Step 2: Select and rename log2FC columns
# -----------------------------
log2fc_df = df[[
    'log2FC_Cancer_vs_Healthy',
    'log2FC_Adenoma_vs_Healthy',
    'log2FC_Cancer_vs_Adenoma'
]].copy()
log2fc_df.columns = [col.replace('log2FC_', '').replace('_', ' ') for col in log2fc_df.columns]

# -----------------------------
# Step 3: Create heatmap
# -----------------------------
plt.figure(figsize=(8, 5))
sns.set(style="white")

ax = sns.heatmap(
    log2fc_df,
    annot=True,
    annot_kws={"fontsize": 8.5},
    cmap='coolwarm',
    center=0,
    linewidths=0.5,
    cbar_kws={'label': 'Log2 Fold Change'},
    fmt=".4f"
)

# Rotate axis labels
plt.xticks(rotation=50, ha='right', fontsize=9.5)
plt.yticks(fontsize=9.5)

# Thicken outer axes borders
for spine in ax.spines.values():
    spine.set_linewidth(2)

# Reduce colorbar (legend) font sizes
cbar = ax.collections[0].colorbar
cbar.ax.tick_params(labelsize=9)  # tick labels
cbar.set_label("Log2 Fold Change", fontsize=9)  # label title

plt.tight_layout()
plt.savefig("CRC_Log2FC_Heatmap_Formatted.png", dpi=600, bbox_inches='tight')
plt.show()

import pandas as pd
import numpy as np
from scipy.stats import mannwhitneyu
from statsmodels.stats.multitest import multipletests

# -------------------------------
# Step 1: Load long format data
# -------------------------------
df = pd.read_csv("Significant_Species_Abundance_LongFormat.csv")

# -------------------------------
# Step 2: Initialize p-values
# -------------------------------
pvals = []

species_list = df['Species'].unique()

for species in species_list:
    sub_df = df[df['Species'] == species]

    healthy = sub_df[sub_df['Group'] == 'Healthy']['log2_Abundance']
    adenoma = sub_df[sub_df['Group'] == 'Adenoma']['log2_Abundance']
    cancer = sub_df[sub_df['Group'] == 'Cancer']['log2_Abundance']

    # Pairwise Mann–Whitney U tests
    p1 = mannwhitneyu(cancer, healthy, alternative='two-sided').pvalue
    p2 = mannwhitneyu(adenoma, healthy, alternative='two-sided').pvalue
    p3 = mannwhitneyu(cancer, adenoma, alternative='two-sided').pvalue

    pvals.append({
        'Species': species,
        'p_Cancer_vs_Healthy': p1,
        'p_Adenoma_vs_Healthy': p2,
        'p_Cancer_vs_Adenoma': p3
    })

pval_df = pd.DataFrame(pvals)

# -------------------------------
# Step 3: Apply FDR correction
# -------------------------------
for col in ['p_Cancer_vs_Healthy', 'p_Adenoma_vs_Healthy', 'p_Cancer_vs_Adenoma']:
    corrected = multipletests(pval_df[col], method='fdr_bh')[1]
    pval_df[f'FDR_{col}'] = corrected

# -------------------------------
# Step 4: Merge with fold change table
# -------------------------------
fc_df = pd.read_csv("Groupwise_Abundance_and_FoldChange.csv")
fc_df.reset_index(inplace=True)

# Merge both dataframes
final_df = pd.merge(fc_df, pval_df, on='Species')

# Save result
final_df.to_csv("Groupwise_Abundance_FoldChange_with_FDR.csv", index=False)

print("✅ Fold change + statistical tests (with FDR correction) saved to 'Groupwise_Abundance_FoldChange_with_FDR.csv'")

!pip install econml

# ==============================================
# Double/Debiased Machine Learning (LinearDML)
# for Ordinal Outcome using Random Forests
# (Per Species Analysis)
# ==============================================

# Required Libraries
import pandas as pd
import numpy as np
from econml.dml import LinearDML
from sklearn.ensemble import RandomForestRegressor

# -----------------------
# Step 1: Load Data
# -----------------------
expr = pd.read_csv("Expression_Matrix_Aligned.csv")
meta = pd.read_csv("Aligned_metadata.csv")
top_species = pd.read_csv("Top_Important_Species.csv")

# -----------------------
# Step 2: Prepare Data
# -----------------------
species_list = top_species.iloc[:, 0].tolist()
expr_filtered = expr[['Sample_ID'] + species_list]
merged = pd.merge(meta, expr_filtered, on="Sample_ID", how="inner")
merged['OrdinalOutcome'] = merged['Group'].map({'Healthy': 0, 'Adenoma': 1, 'Cancer': 2})
merged['Sex'] = merged['Sex'].map({'female': 0, 'male': 1})

Y = merged['OrdinalOutcome'].values
X = merged[['Age', 'BMI', 'Sex']].values

results = []

# -----------------------
# Step 3: Loop over Species
# -----------------------
for species in species_list:
    print(f"Estimating for species: {species}")
    T = merged[[species]].values

    dml_model = LinearDML(
        model_y=RandomForestRegressor(n_estimators=100, random_state=42),
        model_t=RandomForestRegressor(n_estimators=100, random_state=42),
        discrete_treatment=False,
        random_state=42
    )

    dml_model.fit(Y, T, X=X)

    treatment_effects = dml_model.effect(X)
    ate = np.mean(treatment_effects)
    conf_int = dml_model.effect_interval(X)

    results.append({
        'Species': species,
        'ATE': ate,
        'CI Lower': np.mean(conf_int[0]),
        'CI Upper': np.mean(conf_int[1])
    })

# -----------------------
# Step 4: Results DataFrame
# -----------------------
results_df = pd.DataFrame(results)

print("\n🎯 Double ML Causal Effect Estimation (Per Species):")
print(results_df)

results_df.to_csv("DML_Causal_Effects_Per_Species.csv", index=False)
print("\n✅ Results saved to 'DML_Causal_Effects_Per_Species.csv'")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------
# Load the DML results
# -----------------------
results_df = pd.read_csv("DML_Causal_Effects_Per_Species.csv")

# Sort species by ATE for visual clarity
results_df = results_df.sort_values(by="ATE")

# -----------------------
# Create Forest Plot
# -----------------------
plt.figure(figsize=(6, 5))
sns.set(style="white")  # Clean white background

# Error bars with bold markers
plt.errorbar(
    x=results_df['ATE'],
    y=results_df['Species'],
    xerr=[
        results_df['ATE'] - results_df['CI Lower'],
        results_df['CI Upper'] - results_df['ATE']
    ],
    fmt='o',
    color='blue',
    ecolor='gray',
    elinewidth=2.5,
    capsize=5,
    markersize=6.5,
    markeredgewidth=1.8
)

# Vertical reference line at zero
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.6)

# Labels and title
#plt.title("Causal Effects of Microbial Species on CRC Progression", fontsize=16, fontweight='bold')
plt.xlabel("ATE", fontsize=14)
#plt.ylabel("Microbial Species", fontsize=14)

# Aesthetic polish
ax = plt.gca()
ax.grid(False)  # remove grid
for spine in ax.spines.values():
    spine.set_linewidth(2)  # bold axis borders

# Layout and save
plt.tight_layout()
#plt.savefig("DML_Causal_Effects.png", dpi=600)
plt.show()

print("✅ Nature-level plot saved as 'Nature_Level_DML_Causal_Effects_Polished.png'")

# ==============================================
# Sensitivity Analysis for Microbial Species (E-value)
# ==============================================

import pandas as pd
import numpy as np

# Function to calculate E-value
# E-value formula from VanderWeele & Ding (2017)
def compute_evalue(estimate, lower_ci, upper_ci):
    rr = np.exp(np.abs(estimate))
    rr_ci = np.exp(np.abs(lower_ci if estimate > 0 else upper_ci))
    evalue_point = rr + np.sqrt(rr * (rr - 1))
    evalue_ci = rr_ci + np.sqrt(rr_ci * (rr_ci - 1))
    return evalue_point, evalue_ci

# -----------------------
# Load data
# -----------------------
results_df = pd.read_csv("DML_Causal_Effects_Per_Species.csv")

# Results container
evalue_results = []

# -----------------------
# Calculate E-values
# -----------------------
for idx, row in results_df.iterrows():
    ate = row['ATE']
    ci_lower = row['CI Lower']
    ci_upper = row['CI Upper']

    evalue_point, evalue_ci = compute_evalue(ate, ci_lower, ci_upper)

    evalue_results.append({
        'Species': row['Species'],
        'ATE': ate,
        'E-value (Point Estimate)': evalue_point,
        'E-value (Confidence Interval)': evalue_ci
    })

# -----------------------
# Results DataFrame
# -----------------------
evalue_df = pd.DataFrame(evalue_results)
evalue_df.sort_values(by="E-value (Point Estimate)", ascending=False, inplace=True)

print("\n📌 Sensitivity Analysis (E-values):")
print(evalue_df)

evalue_df.to_csv("Sensitivity_Analysis_Evalues.csv", index=False)
print("\n✅ Sensitivity analysis results saved to 'Sensitivity_Analysis_Evalues.csv'")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import matplotlib.colors as mcolors
import matplotlib.cm as cm

# -----------------------
# Load sensitivity analysis results
# -----------------------
evalue_df = pd.read_csv("Sensitivity_Analysis_Evalues.csv")

# Replace infinite E-values with a large finite number
max_finite_evalue = evalue_df['E-value (Point Estimate)'].replace(np.inf, np.nan).max()
replacement_value = max_finite_evalue * 2.2

# Handle infinite values
plot_df = evalue_df.copy()
plot_df['E-value (Point Estimate)'] = plot_df['E-value (Point Estimate)'].replace(np.inf, replacement_value)
plot_df['Log E-value (Point Estimate)'] = np.log10(plot_df['E-value (Point Estimate)'])

# Sort for clean display
plot_df = plot_df.sort_values(by='Log E-value (Point Estimate)', ascending=True)

# Normalize for color mapping
norm = mcolors.Normalize(vmin=plot_df['Log E-value (Point Estimate)'].min(),
                         vmax=plot_df['Log E-value (Point Estimate)'].max())
cmap = plt.colormaps['coolwarm']  # updated for matplotlib ≥3.7
colors = cmap(norm(plot_df['Log E-value (Point Estimate)'].values))

# -----------------------
# Create bar plot
# -----------------------
fig, ax = plt.subplots(figsize=(6, 5))
sns.set(style="white")

bars = ax.barh(
    y=plot_df['Species'],
    width=plot_df['Log E-value (Point Estimate)'],
    color=colors,
    edgecolor='black',
    linewidth=2
)

# Add colorbar
sm = cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])
cbar = plt.colorbar(sm, ax=ax, orientation='vertical')
cbar.set_label("Log10 E-value (Point Estimate)", fontsize=12)

# Styling
ax.set_xlabel("Sensitivity (E-values)", fontsize=12)
ax.set_title("", fontsize=10, fontweight='bold')

ax.grid(False)
for spine in ax.spines.values():
    spine.set_linewidth(2)

plt.tight_layout()
plt.savefig("Sensitivity_Evalue_Colorbar_Corrected.png", dpi=600, bbox_inches='tight')
plt.show()

print("✅ Plot saved with color scale and matplotlib 3.7+ compatibility.")

"""Bootstrap Robustness Check for Causal Estimates"""

# ==============================================
# Bootstrap Robustness Check for Causal Estimates
# ==============================================

import pandas as pd
import numpy as np
from sklearn.utils import resample
from econml.dml import LinearDML
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt
import seaborn as sns

# Load Data
expr = pd.read_csv("Expression_Matrix_Aligned.csv")
meta = pd.read_csv("Aligned_metadata.csv")
top_species = pd.read_csv("Top_Important_Species.csv")

species_list = top_species.iloc[:, 0].tolist()
expr_filtered = expr[['Sample_ID'] + species_list]
merged = pd.merge(meta, expr_filtered, on="Sample_ID", how="inner")
merged['OrdinalOutcome'] = merged['Group'].map({'Healthy': 0, 'Adenoma': 1, 'Cancer': 2})
merged['Sex'] = merged['Sex'].map({'female': 0, 'male': 1})

X = merged[['Age', 'BMI', 'Sex']].values
Y = merged['OrdinalOutcome'].values

# Parameters
n_bootstraps = 100
bootstrap_results = {species: [] for species in species_list}

# Bootstrap loop
for i in range(n_bootstraps):
    print(f"Bootstrap iteration: {i+1}/{n_bootstraps}")
    boot_sample = resample(merged, replace=True, random_state=i)
    Y_boot = boot_sample['OrdinalOutcome'].values
    X_boot = boot_sample[['Age', 'BMI', 'Sex']].values

    for species in species_list:
        T_boot = boot_sample[[species]].values

        dml_model = LinearDML(
            model_y=RandomForestRegressor(n_estimators=100, random_state=42),
            model_t=RandomForestRegressor(n_estimators=100, random_state=42),
            discrete_treatment=False,
            random_state=42
        )

        dml_model.fit(Y_boot, T_boot, X=X_boot)
        ate_boot = np.mean(dml_model.effect(X_boot))
        bootstrap_results[species].append(ate_boot)

# Calculate confidence intervals
bootstrap_ci = []
for species in species_list:
    lower = np.percentile(bootstrap_results[species], 2.5)
    upper = np.percentile(bootstrap_results[species], 97.5)
    mean_ate = np.mean(bootstrap_results[species])
    bootstrap_ci.append({'Species': species, 'Mean_ATE': mean_ate, 'CI Lower': lower, 'CI Upper': upper})

bootstrap_df = pd.DataFrame(bootstrap_ci).sort_values(by='Mean_ATE')
bootstrap_df.to_csv("Bootstrap_Causal_Effects_CI.csv", index=False)
print("\n✅ Bootstrap results saved to 'Bootstrap_Causal_Effects_CI.csv'")

"""Bootstrap Robustness plot"""

import matplotlib.pyplot as plt
import seaborn as sns

# Sort species for better readability
bootstrap_df_sorted = bootstrap_df.sort_values(by='Mean_ATE')

# Set plot aesthetics
plt.figure(figsize=(12, 8))
sns.set(style="white")

# Barplot with thick borders
sns.barplot(
    x='Mean_ATE',
    y='Species',
    data=bootstrap_df_sorted,
    palette='viridis',
    edgecolor='black',
    linewidth=2
)

# Add error bars
plt.errorbar(
    bootstrap_df_sorted['Mean_ATE'],
    bootstrap_df_sorted['Species'],
    xerr=[
        bootstrap_df_sorted['Mean_ATE'] - bootstrap_df_sorted['CI Lower'],
        bootstrap_df_sorted['CI Upper'] - bootstrap_df_sorted['Mean_ATE']
    ],
    fmt='none',
    ecolor='black',
    capsize=5,
    linewidth=2
)

# Vertical line at zero
plt.axvline(x=0, linestyle='--', color='red', linewidth=1.5)

# Labels and styling
plt.xlabel('Mean ATE (Bootstrap)', fontsize=14)
plt.ylabel('Microbial Species', fontsize=14)
plt.title('Bootstrap Robustness of Causal Effects', fontsize=16, fontweight='bold')

# Thicken plot borders
ax = plt.gca()
ax.grid(False)
for spine in ax.spines.values():
    spine.set_linewidth(2)

plt.tight_layout()
#plt.savefig("Bootstrap_Robustness_Check.png", dpi=600)
plt.show()

"""Classification Visualization Based on Mean ATE (Bootstrap)"""

# ==============================================
# Classification Visualization Based on Mean ATE (Bootstrap)
# ==============================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load previously calculated bootstrap results
bootstrap_df = pd.read_csv("Bootstrap_Causal_Effects_CI.csv")

# Classification based on Mean_ATE values
conditions = [
    (bootstrap_df['Mean_ATE'] > 50),
    (bootstrap_df['Mean_ATE'] < -50)
]
choices = ['Promoter', 'Protector']
bootstrap_df['Classification'] = np.select(conditions, choices, default='Neutral')

# Sort by Mean ATE for visualization
bootstrap_df.sort_values(by='Mean_ATE', inplace=True)

# Plotting
plt.figure(figsize=(8, 6))
sns.set(style="white")

palette = {'Promoter': '#d73027', 'Protector': '#1a9850', 'Neutral': '#fee08b'}

sns.barplot(x='Mean_ATE', y='Species', hue='Classification',
            data=bootstrap_df, palette=palette, edgecolor='black', linewidth=2)

# Add confidence intervals
for index, row in bootstrap_df.iterrows():
    plt.errorbar(x=row['Mean_ATE'], y=index,
                 xerr=[[row['Mean_ATE'] - row['CI Lower']], [row['CI Upper'] - row['Mean_ATE']]],
                 fmt='none', ecolor='black', capsize=4, linewidth=1.5)

# Customize plot
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(2)

ax.grid(False)

plt.axvline(0, linestyle='--', color='black', linewidth=2)
plt.xlabel("Mean ATE (Bootstrap)", fontsize=14)
#plt.ylabel("Microbial Species", fontsize=14)
#plt.title("Classification of Microbial Species Based on Mean ATE (Bootstrap)", fontsize=16, fontweight='bold')

plt.legend(title='', fontsize=9, title_fontsize=9)
plt.tight_layout()

plt.savefig("Bootstrap_Classification_Mean_ATE.png", dpi=600)
plt.show()

print("\n📊 Classification plot saved to 'Bootstrap_Classification_Mean_ATE.png'")

"""Classification of microbial interactions as Antagonistic or synergistic using DML"""

# ==============================================
# Microbial Interaction Analysis (Synergistic/Antagonistic)
# using Double Machine Learning (LinearDML)
# ==============================================

import pandas as pd
import numpy as np
from econml.dml import LinearDML
from sklearn.ensemble import RandomForestRegressor
from itertools import combinations

# Load Data
expr = pd.read_csv("Expression_Matrix_Aligned.csv")
meta = pd.read_csv("Aligned_metadata.csv")
top_species = pd.read_csv("Top_Important_Species.csv")

species_list = top_species.iloc[:, 0].tolist()
expr_filtered = expr[['Sample_ID'] + species_list]
merged = pd.merge(meta, expr_filtered, on="Sample_ID", how="inner")

# Define Outcome and Covariates
merged['OrdinalOutcome'] = merged['Group'].map({'Healthy': 0, 'Adenoma': 1, 'Cancer': 2})
merged['Sex'] = merged['Sex'].map({'female': 0, 'male': 1})

Y = merged['OrdinalOutcome'].values
X = merged[['Age', 'BMI', 'Sex']].values

interaction_results = []

for species_pair in combinations(species_list, 2):
    sp1, sp2 = species_pair
    print(f"Analyzing interaction between {sp1} and {sp2}")

    merged['interaction'] = merged[sp1] * merged[sp2]
    T = merged[[sp1, sp2, 'interaction']].values

    dml_model = LinearDML(
        model_y=RandomForestRegressor(n_estimators=100, random_state=42),
        model_t=RandomForestRegressor(n_estimators=100, random_state=42),
        discrete_treatment=False,
        random_state=42
    )

    dml_model.fit(Y, T, X=X)

    # Robust fix: explicitly use const_marginal_effect
    effects = dml_model.const_marginal_effect(X)

    # Check dimensions explicitly
    if effects.ndim == 1 and effects.shape[0] == 3:
        interaction_effect = effects[2]
    else:
        interaction_effect = effects[:, 2]

    mean_interaction_effect = np.mean(interaction_effect)

    # Confidence intervals
    conf_int = dml_model.const_marginal_effect_interval(X)

    if conf_int[0].ndim == 1 and conf_int[0].shape[0] == 3:
        interaction_CI_lower = conf_int[0][2]
        interaction_CI_upper = conf_int[1][2]
    else:
        interaction_CI_lower = np.mean(conf_int[0][:, 2])
        interaction_CI_upper = np.mean(conf_int[1][:, 2])

    interaction_results.append({
        'Species_1': sp1,
        'Species_2': sp2,
        'Interaction_Effect': mean_interaction_effect,
        'CI Lower': interaction_CI_lower,
        'CI Upper': interaction_CI_upper
    })

interaction_df = pd.DataFrame(interaction_results)
interaction_df.to_csv("Microbial_Interaction_Effects_Corrected.csv", index=False)

print("\n✅ Interaction analysis saved to 'Microbial_Interaction_Effects_Corrected.csv'")
print(interaction_df.head())

"""Plotting of significant microbial interactions with classification (synergistic/antagonistic)"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.lines import Line2D

# Load interaction results
interaction_df = pd.read_csv("Microbial_Interaction_Effects_Corrected.csv")

# Filter significant interactions (CI excludes zero)
significant_df = interaction_df[
    (interaction_df['CI Lower'] > 0) | (interaction_df['CI Upper'] < 0)
].copy()

# Check if significant interactions exist
if significant_df.empty:
    print("⚠️ No significant interactions found based on confidence intervals.")
else:
    # Create readable interaction labels
    significant_df['Interaction Label'] = significant_df['Species_1'] + " & " + significant_df['Species_2']
    significant_df.sort_values(by="Interaction_Effect", inplace=True)

    # Assign colors based on promoting/protecting
    significant_df['Color'] = significant_df['Interaction_Effect'].apply(
        lambda x: 'red' if x > 0 else 'green'
    )

    # Start plotting
    plt.figure(figsize=(8, 6))
    sns.set(style="white")

    # Plot each interaction
    for idx, row in significant_df.iterrows():
        plt.errorbar(
            row['Interaction_Effect'],
            row['Interaction Label'],
            xerr=[[row['Interaction_Effect'] - row['CI Lower']],
                  [row['CI Upper'] - row['Interaction_Effect']]],
            fmt='o',
            ecolor='black',
            elinewidth=2,
            capsize=5,
            markersize=10,
            color=row['Color']
        )

    # Vertical line at zero
    plt.axvline(x=0, color='blue', linestyle='--', linewidth=1.5)

    # Aesthetics: thick borders, no gridlines
    ax = plt.gca()
    ax.grid(False)
    for spine in ax.spines.values():
        spine.set_linewidth(2)

    # Labels
    plt.xlabel("ATE", fontsize=14)

    # Explicit custom legend
    custom_legend = [
        Line2D([0], [0], marker='o', color='w', label='Synergistic',
               markerfacecolor='red', markersize=10, markeredgecolor='black'),
        Line2D([0], [0], marker='o', color='w', label='Antagonistic',
               markerfacecolor='green', markersize=10, markeredgecolor='black')
    ]

    plt.legend(handles=custom_legend, title='', fontsize=9, title_fontsize=13)

    plt.tight_layout()
    plt.savefig("Significant_Microbial_Interactions_Final.png", dpi=600)
    plt.show()

    print("📊 Final plot saved as 'Significant_Microbial_Interactions_Final.png'")

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

# -------------------------------
# Step 1: Load and Filter Interactions
# -------------------------------
df = pd.read_csv("Microbial_Interaction_Effects_Corrected.csv")

# Keep only statistically significant interactions (CI excludes zero)
df_sig = df[(df['CI Lower'] > 0) | (df['CI Upper'] < 0)].copy()

# -------------------------------
# Step 2: Build Network Graph
# -------------------------------
G = nx.Graph()

for _, row in df_sig.iterrows():
    sp1, sp2 = row['Species_1'], row['Species_2']
    effect = row['Interaction_Effect']
    G.add_edge(sp1, sp2,
               weight=abs(effect),
               effect=effect,
               color='red' if effect > 0 else 'green')  # Synergistic (red), Antagonistic (green)

# -------------------------------
# Step 3: Visualize the Network
# -------------------------------
pos = nx.spring_layout(G, k=10, seed=42)

edge_colors = [d['color'] for _, _, d in G.edges(data=True)]
edge_widths = [d['weight'] / max(df_sig['Interaction_Effect'].abs()) * 6 for _, _, d in G.edges(data=True)]

plt.figure(figsize=(14, 8))
nx.draw_networkx_nodes(G, pos, node_color='skyblue', node_size=800, edgecolors='black', linewidths=1.5)
nx.draw_networkx_labels(G, pos, font_size=9, font_weight='bold')
nx.draw_networkx_edges(G, pos, edge_color=edge_colors, width=edge_widths, alpha=0.85)

legend_elements = [
    Line2D([0], [0], color='red', lw=2.5, label='Synergistic'),
    Line2D([0], [0], color='green', lw=2.5, label='Antagonistic')
]
plt.legend(handles=legend_elements, loc='upper left', fontsize=10, frameon=True, title="")
plt.axis('off')
plt.tight_layout()
plt.savefig("Microbial_Interaction_Network.png", dpi=600, bbox_inches='tight')
plt.show()

print("✅ Network plot saved as 'Microbial_Interaction_Network.png'")

# -------------------------------
# Step 4: Compute Network Metrics
# -------------------------------
degree = dict(G.degree())
strength = dict(G.degree(weight='weight'))
betweenness = nx.betweenness_centrality(G, weight='weight')
closeness = nx.closeness_centrality(G)
eigenvector = nx.eigenvector_centrality_numpy(G, weight='weight')

# Compile metrics into a DataFrame
metrics_df = pd.DataFrame({
    'Node': list(G.nodes()),
    'Degree': [degree[n] for n in G.nodes()],
    'Strength': [strength[n] for n in G.nodes()],
    'Betweenness': [betweenness[n] for n in G.nodes()],
    'Closeness': [closeness[n] for n in G.nodes()],
    'Eigenvector': [eigenvector[n] for n in G.nodes()]
}).round(4)

# -------------------------------
# Step 5: Save Metrics
# -------------------------------
metrics_df.to_csv("Microbial_Interaction_Network_Metrics.csv", index=False)
print("✅ Network metrics saved to 'Microbial_Interaction_Network_Metrics.csv'")

# -------------------------------
# Step 6: Highlight Top Hubs
# -------------------------------
top_degree = metrics_df.sort_values(by='Degree', ascending=False).head(5)
top_strength = metrics_df.sort_values(by='Strength', ascending=False).head(5)
top_betweenness = metrics_df.sort_values(by='Betweenness', ascending=False).head(5)

print("\n📌 Top 5 Hub Species by Degree:\n", top_degree[['Node', 'Degree']])
print("\n📌 Top 5 Influential Species by Strength:\n", top_strength[['Node', 'Strength']])
print("\n📌 Top 5 Bridge Species by Betweenness:\n", top_betweenness[['Node', 'Betweenness']])

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import numpy as np

# -------------------------------
# Step 1: Load and Filter Interactions
# -------------------------------
df = pd.read_csv("Microbial_Interaction_Effects_Corrected.csv")
df_sig = df[(df['CI Lower'] > 0) | (df['CI Upper'] < 0)].copy()

# -------------------------------
# Step 2: Build the Network Graph
# -------------------------------
G = nx.Graph()
for _, row in df_sig.iterrows():
    sp1, sp2 = row['Species_1'], row['Species_2']
    effect = row['Interaction_Effect']
    G.add_edge(
        sp1, sp2,
        weight=abs(effect),
        effect=effect,
        color='red' if effect > 0 else 'green'
    )

# -------------------------------
# Step 3: Centrality Calculations
# -------------------------------
strength = dict(G.degree(weight='weight'))
betweenness = nx.betweenness_centrality(G, weight='weight')

node_betweenness = np.array([betweenness[n] for n in G.nodes()])
max_strength = max(strength.values()) if strength else 1
node_sizes = [500 + 1500 * (strength[n] / max_strength) for n in G.nodes()]

# Color mapping
cmap = cm.get_cmap('YlGnBu')
norm = mcolors.Normalize(vmin=min(node_betweenness), vmax=max(node_betweenness))
node_colors = [cmap(norm(b)) for b in node_betweenness]
node_colors = [(r, g, b, 0.9) for r, g, b, _ in node_colors]  # add transparency

# -------------------------------
# Step 4: Network Visualization
# -------------------------------
fig, ax = plt.subplots(figsize=(8, 5))
pos = nx.spring_layout(G, k=6, seed=42)

# Draw network
nodes = nx.draw_networkx_nodes(
    G, pos, ax=ax,
    node_size=node_sizes,
    node_color=node_colors,
    edgecolors='black',
    linewidths=1.8
)
for node, (x, y) in pos.items():
    ax.text(
        x + 0.0001, y, node,  # shift label slightly to the right
        fontsize=8,
        fontweight='bold',
        color='black',
        ha='center',
        va='center'
    )

nx.draw_networkx_edges(
    G, pos, ax=ax,
    edge_color=[d['color'] for _, _, d in G.edges(data=True)],
    width=[d['weight'] / max(df_sig['Interaction_Effect'].abs()) * 6 for _, _, d in G.edges(data=True)],
    alpha=1.0
)

# Add colorbar for betweenness centrality
sm = cm.ScalarMappable(cmap=cmap, norm=norm)
sm.set_array(node_betweenness)
cbar = plt.colorbar(sm, ax=ax, shrink=0.3)
cbar.set_label('Betweenness Centrality', fontsize=10)

# Add edge interaction type legend
legend_elements = [
    Line2D([0], [0], color='red', lw=3.0, label='Synergistic'),
    Line2D([0], [0], color='green', lw=3.0, label='Antagonistic')
]
ax.legend(handles=legend_elements, loc='upper left', fontsize=8, frameon=True)

# Final touches
#ax.set_title("Microbial Interaction Network with Centrality Mapping", fontsize=14, fontweight='bold')
ax.axis('off')
plt.tight_layout()
plt.savefig("Microbial_Interaction_Network_Centrality_Colored.png", dpi=600, bbox_inches='tight')
plt.show()

"""Intervention Analysis"""

import pandas as pd
import numpy as np
from econml.dml import LinearDML
from sklearn.ensemble import RandomForestRegressor
from scipy.stats import ttest_ind
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
expr = pd.read_csv("Expression_Matrix_Aligned.csv")
meta = pd.read_csv("Aligned_metadata.csv")
top_species = pd.read_csv("Top_Important_Species.csv")

species_list = top_species.iloc[:, 0].tolist()
expr_filtered = expr[['Sample_ID'] + species_list]
merged = pd.merge(meta, expr_filtered, on="Sample_ID", how="inner")

# Outcome and covariates
merged['OrdinalOutcome'] = merged['Group'].map({'Healthy': 0, 'Adenoma': 1, 'Cancer': 2})
merged['Sex'] = merged['Sex'].map({'female': 0, 'male': 1})

Y = merged['OrdinalOutcome'].values
X = merged[['Age', 'BMI', 'Sex']].values

# Calculate baseline CRC score
baseline_crc = merged['OrdinalOutcome'].mean()

# Store final intervention results with risk metrics
intervention_results = []
intervention_effects = []

for species in species_list:
    print(f"Analyzing intervention for: {species}")

    T = merged[[species]].values

    # Train model
    dml = LinearDML(
        model_y=RandomForestRegressor(n_estimators=100, random_state=42),
        model_t=RandomForestRegressor(n_estimators=100, random_state=42),
        discrete_treatment=False,
        random_state=42
    )
    dml.fit(Y, T, X=X)

    # ATE
    ate = np.mean(dml.effect(X))

    # Interventions
    std_dev = merged[species].std()
    effect_up = dml.const_marginal_effect(X) * std_dev
    effect_down = dml.const_marginal_effect(X) * -std_dev

    mean_up = np.mean(effect_up)
    mean_down = np.mean(effect_down)

    # Simulated new CRC scores
    simulated_up = baseline_crc + mean_up
    simulated_down = baseline_crc + mean_down

    # Risk metrics
    arr_up = baseline_crc - simulated_up
    rr_up = simulated_up / baseline_crc if baseline_crc != 0 else np.nan
    try:
        or_up = (simulated_up / (1 - simulated_up)) / (baseline_crc / (1 - baseline_crc))
    except ZeroDivisionError:
        or_up = np.nan

    arr_down = baseline_crc - simulated_down
    rr_down = simulated_down / baseline_crc if baseline_crc != 0 else np.nan
    try:
        or_down = (simulated_down / (1 - simulated_down)) / (baseline_crc / (1 - baseline_crc))
    except ZeroDivisionError:
        or_down = np.nan

    # P-value: t-test of local effects
    p_value = ttest_ind(effect_up.flatten(), effect_down.flatten(), equal_var=False).pvalue

    # Store summary metrics
    intervention_results.append({
        'Species': species,
        'ATE': round(ate, 3),
        'Baseline_CRC': round(baseline_crc, 3),
        'Sim_CRC_+1SD': round(simulated_up, 3),
        'ARR_+1SD': round(arr_up, 3),
        'RR_+1SD': round(rr_up, 3),
        'OR_+1SD': round(or_up, 3) if not np.isnan(or_up) else 'NA',
        'Sim_CRC_-1SD': round(simulated_down, 3),
        'ARR_-1SD': round(arr_down, 3),
        'RR_-1SD': round(rr_down, 3),
        'OR_-1SD': round(or_down, 3) if not np.isnan(or_down) else 'NA',
        'P_value': round(p_value, 4)
    })

    # Store raw intervention effects
    intervention_effects.append({
        'Species': species,
        'ATE': ate,
        'Intervention (+1 SD)': mean_up,
        'Intervention (-1 SD)': mean_down
    })

# Save results
output_df = pd.DataFrame(intervention_results)
output_df.to_csv("EconML_Intervention_Effect_Table_With_RiskMetrics.csv", index=False)

intervention_df = pd.DataFrame(intervention_effects)
intervention_df.to_csv("EconML_Intervention_Results.csv", index=False)

print("✅ All results saved successfully.")

from matplotlib.patches import Patch
import matplotlib.pyplot as plt # Explicitly import matplotlib.pyplot
import seaborn as sns # Explicitly import seaborn


def plot_arr_bar(df_to_plot, arr_col, title, filename): # Renamed parameter for clarity
    df_sorted = df_to_plot.sort_values(by=arr_col)

    # Color bars dynamically
    bar_colors = ['#1a9850' if val > 0 else '#d73027' for val in df_sorted[arr_col]]

    # Plot
    plt.figure(figsize=(6, 5))
    bars = plt.barh(
        df_sorted['Species'],
        df_sorted[arr_col],
        color=bar_colors,
        edgecolor='black',
        linewidth=2.0
    )

    # Vertical line at zero
    plt.axvline(x=0, color='black', linestyle='--', linewidth=1.6)

    # Add color legend
    legend_elements = [
        Patch(facecolor='#1a9850', edgecolor='black', label='Protective (ARR > 0)'),
        Patch(facecolor='#d73027', edgecolor='black', label='Risk-promoting (ARR < 0)')
    ]
    plt.legend(handles=legend_elements, title='', fontsize=6.3, title_fontsize=6)

    # Labels and styling
    # plt.title(title, fontsize=16, fontweight='bold') # Title commented out as in original notebook
    plt.xlabel("ARR", fontsize=14)

    ax = plt.gca()
    ax.grid(False)
    for spine in ax.spines.values():
        spine.set_linewidth(2)

    plt.tight_layout()
    plt.savefig(filename, dpi=600) # Save commented out as in original notebook
    plt.show()

# -------------------------------
# Plot 1: ARR from +1 SD intervention
# -------------------------------
plot_arr_bar(
    output_df, # Changed 'df' to 'output_df'
    arr_col='ARR_+1SD',
    title='+1 SD Microbial Abundance',
    filename='ARR_Plus1SD_BarPlot.png'
)

# -------------------------------
# Plot 2: ARR from –1 SD intervention
# -------------------------------
plot_arr_bar(
    output_df, # Changed 'df' to 'output_df'
    arr_col='ARR_-1SD',
    title='–1 SD Microbial Abundance',
    filename='ARR_Minus1SD_BarPlot.png'
)

print("✅ Plots updated with dynamic color coding based on ARR sign.")

"""composite intervention score"""

import pandas as pd
import numpy as np

# Load the intervention table
df = pd.read_csv("EconML_Intervention_Effect_Table_With_RiskMetrics.csv")

# Replace 'NA' strings in OR columns with np.nan for safety
df['OR_+1SD'] = pd.to_numeric(df['OR_+1SD'], errors='coerce')
df['OR_-1SD'] = pd.to_numeric(df['OR_-1SD'], errors='coerce')

# Clip p-values to avoid division by zero or inflated scores
df['P_value_clipped'] = df['P_value'].clip(lower=1e-6)

# Compute unnormalized intervention score
df['InterventionScore'] = (
    df['ARR_+1SD'].abs() +
    df['ARR_-1SD'].abs() +
    df['ATE'].abs()
) * (1 / df['P_value_clipped'])

# Normalize the score to [0–1] using min-max scaling
min_score = df['InterventionScore'].min()
max_score = df['InterventionScore'].max()
df['InterventionScore_Normalized'] = (df['InterventionScore'] - min_score) / (max_score - min_score)

# Sort by normalized score for readability
df_sorted = df.sort_values(by='InterventionScore_Normalized', ascending=False)

# Save final scored and normalized table
df_sorted.to_csv("EconML_Intervention_Score_Normalized.csv", index=False)

print("✅ Full table with normalized scores saved to 'EconML_Intervention_Score_Normalized.csv'")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------
# Step 1: Load data
# -----------------------
df = pd.read_csv("EconML_Intervention_Score_Normalized.csv")

# -----------------------
# Step 2: Classify by normalized score
# -----------------------
def classify(score):
    if score >= 0.25:
        return 'High'
    elif score >= 0.1:
        return 'Moderate'
    else:
        return 'Low'

df['Priority'] = df['InterventionScore_Normalized'].apply(classify)

# Sort for readability
df_sorted = df.sort_values(by='InterventionScore_Normalized', ascending=True)

# -----------------------
# Step 3: Create strip plot
# -----------------------
plt.figure(figsize=(6, 5))
sns.set(style="white")

sns.stripplot(
    x='InterventionScore_Normalized',
    y='Species',
    data=df_sorted,
    hue='Priority',
    palette={'High': '#d73027', 'Moderate': '#fee08b', 'Low': '#1a9850'},
    dodge=False,
    size=10,
    linewidth=1.5,
    edgecolor='black'
)

# Aesthetics
#plt.title("Microbial Species Prioritized by Intervention Score", fontsize=16, fontweight='bold')
plt.xlabel("Intervention Score", fontsize=14)
#plt.ylabel("Microbial Species", fontsize=14)

# Legend and styling
plt.legend(title='', fontsize=9, title_fontsize=12)
ax = plt.gca()
ax.grid(False)
for spine in ax.spines.values():
    spine.set_linewidth(2)

plt.tight_layout()
plt.savefig("Intervention_StripPlot_Priority.png", dpi=600)
plt.show()

print("✅ Strip plot created with High/Moderate/Low priority tiers.")