# -*- coding: utf-8 -*-
"""Causal_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WeGjMOdUMO3wcu_jsHeQZwHminwJmKEs

Causal Inference Analysis
"""

import pandas as pd
from google.colab import files

# 1) Read in your uploaded files
biomarkers_df = pd.read_csv("robust_biomarkers.csv")
card_df       = pd.read_csv("CRC_CARD.csv")
vfdb_df       = pd.read_csv("VF_Processed.csv")

# 2) Clean Feature names
biomarkers_df["Feature"] = biomarkers_df["Feature"].str.strip()

# 3) Split into ARG_ and VF_ subsets
arg_df = biomarkers_df[biomarkers_df["Feature"].str.startswith("ARG_")].copy()
vf_df  = biomarkers_df[biomarkers_df["Feature"].str.startswith("VF_")].copy()

# 4) Prefix annotation tables to match your Feature names
card_df["Gene"]  = "ARG_" + card_df["Gene"].astype(str).str.strip()
vfdb_df["Gene"]  = "VF_"  + vfdb_df["Gene"].astype(str).str.strip()

# 5) Aggregate Species & Mechanism per gene
card_agg = (
    card_df
    .groupby("Gene")
    .agg({
        "Matched_Species":     lambda x: ", ".join(sorted(set(x))),
        "Resistance_Mechanism": "first"
    })
    .reset_index()
    .rename(columns={"Matched_Species":"Species",
                     "Resistance_Mechanism":"Mechanism"})
)

vfdb_agg = (
    vfdb_df
    .groupby("Gene")
    .agg({
        "Matched_Species": lambda x: ", ".join(sorted(set(x))),
        "Class_Mechanism": "first"
    })
    .reset_index()
    .rename(columns={"Matched_Species":"Species",
                     "Class_Mechanism":"Mechanism"})
)

# 6) Merge onto your biomarker lists
arg_annotated = pd.merge(arg_df, card_agg,
                         left_on="Feature", right_on="Gene",
                         how="left").drop(columns="Gene")

vf_annotated = pd.merge(vf_df, vfdb_agg,
                        left_on="Feature", right_on="Gene",
                        how="left").drop(columns="Gene")

# 7) Combine and select columns
combined = pd.concat([arg_annotated, vf_annotated], axis=0)

keep_cols = [
    "Feature", "Importance_Mean", "Stability (%)", "Consistency",
    "Mechanism", "Antibiotics_Class",
    "VF Class", "VF Function", "Species"
]

# ensure all keep_cols exist
for c in keep_cols:
    if c not in combined.columns:
        combined[c] = pd.NA

annotated_all = combined[keep_cols]

# 8) **Drop unwanted columns** before saving
annotated_all = annotated_all.drop(columns=[
    "Antibiotics_Class", "VF Class", "VF Function"
], errors="ignore")

# 9) Save & download full annotated
annotated_all.to_csv("robust_biomarkers_annotated.csv", index=False)
print("✅ Saved robust_biomarkers_annotated.csv")
files.download("robust_biomarkers_annotated.csv")

# 10) Filter only Consistent == 1, then drop again and download
annotated_consistent = annotated_all[annotated_all["Consistency"] == 1].copy()
annotated_consistent.to_csv("robust_biomarkers_consistent_only.csv", index=False)
print("✅ Saved robust_biomarkers_consistent_only.csv")
files.download("robust_biomarkers_consistent_only.csv")

# === Step 2: Import required libraries
import pandas as pd

# === Step 4: Load files
rf_df = pd.read_csv("robust_biomarkers_consistent_only.csv")
ordinal_df = pd.read_csv("ordinal_forest_feature_importance.csv").rename(columns={"Gene": "Feature"})

# === Step 5: Merge on Feature column
merged = rf_df.merge(ordinal_df[['Feature', 'Importance']], on="Feature", how="inner")

# === Step 6: Clean and re-order columns
final_cols = [
    "Feature",
    "Importance",           # From Ordinal Forest
    "Importance_Mean",      # From RF
    "Stability (%)",
    "Consistency",
    "Mechanism",
    "Species"
]

merged = merged[final_cols]

# === Step 7: Save merged output
merged.to_csv("Filtered_biomarker_annotated.csv", index=False)
print("✅ File saved: Filtered_biomarker_annotated.csv")

# === Step 8: Preview
merged.head()

# ================================
# 📊 Functional Summary Pie Chart (Threshold 4%) using 'Mechanism'
# ================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
import os

# === VISUAL STYLING ===
sns.set(style="whitegrid")
mpl.rcParams.update({
    "axes.edgecolor": "black",
    "axes.linewidth": 1.5,
    "axes.labelsize": 13,
    "axes.titlesize": 14,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "legend.fontsize": 11,
    "figure.dpi": 600,
})

# === PATHS ===
file_path = "/content/Filtered_biomarker_annotated.csv"
save_dir = "/content/"
os.makedirs(save_dir, exist_ok=True)

# === LOAD DATA ===
df = pd.read_csv(file_path)
df["Function_Group"] = df["Mechanism"].fillna("Unknown")

# === CALCULATE FUNCTION COUNTS AND PERCENTAGE ===
func_counts = df["Function_Group"].value_counts()
total = func_counts.sum()
percentages = (func_counts / total) * 100

# Group anything ≤ 4% into "Other"
threshold = 1
main_labels = percentages[percentages > threshold].index.tolist()
grouped = func_counts[main_labels]
other_sum = func_counts[~func_counts.index.isin(main_labels)].sum()

if other_sum > 0:
    grouped["Other"] = other_sum

# === PIE CHART ===
colors = sns.color_palette("Set3", len(grouped))  # Changed to Set2
plt.figure(figsize=(9, 8))
plt.pie(
    grouped,
    labels=[f"{label} ({count})" for label, count in grouped.items()],
    autopct='%1.1f%%',
    startangle=180,
    colors=colors,
    wedgeprops={"linewidth": 2.0, "edgecolor": "black"},
    textprops={"fontsize": 10,"fontweight": "bold"}
)

#plt.title("Functional Distribution of Consistent Biomarkers", fontsize=15)
plt.tight_layout()

pie_file = os.path.join(save_dir, "consistent_mechanism_summary_piechart_threshold4_actual.png")
plt.savefig(pie_file, dpi=600, bbox_inches="tight")
plt.show()

print(f"✅ Saved pie chart to: {pie_file}")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
import os
from scipy.stats import chi2_contingency
import numpy as np

# === CONFIGURATION ===
annot_file = "/content/Filtered_biomarker_annotated.csv"
meta_file = "Metadata_Aligned_VF_ARG_CountMatrix.csv"
expr_file = "combined_ARG_VFDB_final_DATA.csv"
save_dir = "outputs_function_distribution"
os.makedirs(save_dir, exist_ok=True)

# === LOAD DATA ===
meta = pd.read_csv(meta_file)
expr = pd.read_csv(expr_file, index_col=0).T.reset_index().rename(columns={"index": "Sample_ID"})
annot = pd.read_csv(annot_file)

# === CLEAN & PREPARE ===
annot = annot.dropna(subset=["Feature"])
annot["Function_Group"] = annot["Mechanism"].fillna("Unknown")

features = [f for f in annot["Feature"].tolist() if f in expr.columns]
expr = expr[["Sample_ID"] + features]
merged = pd.merge(meta, expr, on="Sample_ID", how="inner")

# === LONG FORMAT TRANSFORMATION ===
long_df = merged.melt(id_vars=["Sample_ID", "Group"], var_name="Feature", value_name="Abundance")
long_df["Abundance"] = pd.to_numeric(long_df["Abundance"], errors="coerce")
long_df = long_df[long_df["Abundance"] > 0]
long_df = pd.merge(long_df, annot[["Feature", "Function_Group"]], on="Feature", how="left")

# === COUNT PER FUNCTION AND GROUP ===
count_df = long_df.groupby(["Group", "Function_Group"])["Feature"].count().reset_index()
count_df = count_df.rename(columns={"Feature": "Count"})

# === NORMALIZE TO PROPORTIONS ===
total_per_group = count_df.groupby("Group")["Count"].sum().reset_index().rename(columns={"Count": "Total"})
count_df = pd.merge(count_df, total_per_group, on="Group")
count_df["Proportion"] = count_df["Count"] / count_df["Total"] * 100

# === SAVE COMPARISON SUMMARY TABLE ===
pivot = count_df.pivot(index="Function_Group", columns="Group", values="Proportion").fillna(0)
pivot["Max_Diff"] = pivot.max(axis=1) - pivot.min(axis=1)
pivot = pivot.sort_values("Max_Diff", ascending=False)
pivot_path = os.path.join(save_dir, "Functional_Group_Differences_Across_Stages.csv")
pivot.to_csv(pivot_path)
print(f"✅ Comparison table saved to: {pivot_path}")

# === CHI-SQUARE TEST (FUNCTION GROUP x GROUP) ===
contingency = count_df.pivot_table(
    index="Function_Group", columns="Group", values="Count", fill_value=0
)

chi2, p_val, dof, expected = chi2_contingency(contingency)

# === EFFECT SIZE (Cramér's V) ===
n = contingency.to_numpy().sum()
min_dim = min(contingency.shape) - 1
cramers_v = np.sqrt(chi2 / (n * min_dim))

# === REPORT STATS ===
print("\n📊 Chi-square test results:")
print(f"  χ² = {chi2:.2f}, df = {dof}, p-value = {p_val:.4e}")
print(f"  Cramér's V = {cramers_v:.3f} (Effect size)")

# === SAVE CONTINGENCY AND EXPECTED TABLES ===
expected_df = pd.DataFrame(expected, index=contingency.index, columns=contingency.columns)
expected_path = os.path.join(save_dir, "Expected_Function_Distribution.csv")
observed_path = os.path.join(save_dir, "Observed_Function_Distribution.csv")
expected_df.to_csv(expected_path)
contingency.to_csv(observed_path)
print(f"✅ Saved expected counts to: {expected_path}")
print(f"✅ Saved observed counts to: {observed_path}")

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

# === Paths ===
save_dir = "outputs_function_distribution"
observed_path = os.path.join(save_dir, "Observed_Function_Distribution.csv")
expected_path = os.path.join(save_dir, "Expected_Function_Distribution.csv")
heatmap_path = os.path.join(save_dir, "Posthoc_Residual_Heatmap.png")

# === Load Data ===
observed = pd.read_csv(observed_path, index_col=0)
expected = pd.read_csv(expected_path, index_col=0)

# === Ensure Same Shape and Order ===
observed = observed.loc[expected.index, expected.columns]

# === Calculate Pearson Residuals ===
residuals = (observed - expected) / np.sqrt(expected)
residuals = residuals.replace([np.inf, -np.inf], np.nan).fillna(0)

# === Save Residuals to CSV ===
residuals.to_csv(os.path.join(save_dir, "Posthoc_Pearson_Residuals.csv"))

# === Load Residuals ===
residual_path = "outputs_function_distribution/Posthoc_Pearson_Residuals.csv"
residuals = pd.read_csv(residual_path, index_col=0)

# === Melt to long format ===
long_df = residuals.reset_index().melt(id_vars="Function_Group", var_name="Group", value_name="Residual")

# === Custom group colors ===
group_colors = {
    "Healthy": "#ffcc00",
    "Adenoma": "#984ea3",
    "Cancer": "#4daf4a"
}

# === Styling ===
sns.set(style="white", font_scale=1.1)
plt.figure(figsize=(9, 5))

# === Plot ===
ax = sns.barplot(
    data=long_df,
    y="Function_Group",  # Horizontal bars for clarity
    x="Residual",
    hue="Group",
    palette=group_colors,
    edgecolor="black",
    linewidth=1.5,
    saturation=0.9
)

# === Axis Customization ===
plt.axvline(0, color="gray", linewidth=1.3, linestyle="--")
plt.xlabel("Pearson Residual", fontsize=13)
plt.ylabel("Function Mechanism", fontsize=13)
#plt.title("Post-hoc Pearson Residuals by Function and CRC Group", fontsize=15, fontweight="bold")

# === Keep and Style Borders ===
for spine in ax.spines.values():
    spine.set_linewidth(2)
    spine.set_color("black")

# === Legend and layout ===
plt.legend(title="Group", bbox_to_anchor=(1.01, 1), loc="upper left", frameon=True)
plt.xticks(fontsize=11)
plt.yticks(fontsize=11)

plt.tight_layout()

# === Save ===
bar_path = "outputs_function_distribution/Posthoc_Residuals_Barplot_CustomColor.png"
#plt.savefig(bar_path, dpi=600, bbox_inches="tight")
plt.show()

print(f"✅ Bar plot saved to: {bar_path}")

# ============================
# 🔬 CRC Biomarker log₂FC Heatmap
# ============================

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
from scipy.stats import mannwhitneyu
from statsmodels.stats.multitest import multipletests
from google.colab import files
from io import BytesIO


# === Read Uploaded Data ===
meta = pd.read_csv("Metadata_Aligned_VF_ARG_CountMatrix.csv")
matrix = pd.read_csv("combined_ARG_VFDB_final_DATA.csv", index_col=0).T
biomarkers = pd.read_csv("/content/Filtered_biomarker_annotated.csv")

# === Format ===
meta["Sample_ID"] = meta["Sample_ID"].astype(str)
matrix.index.name = "Sample_ID"
matrix.reset_index(inplace=True)
merged = pd.merge(matrix, meta, on="Sample_ID", how="inner")

# === Biomarkers & Log2 Transform ===
top_features = biomarkers["Feature"].tolist()
log_data = np.log2(merged[top_features] + 1)
log_data["Group"] = merged["Group"]

# === Comparisons ===
comparisons = [("Cancer", "Healthy"), ("Adenoma", "Healthy"), ("Cancer", "Adenoma")]
fc_matrix = pd.DataFrame(index=top_features)
pval_matrix = pd.DataFrame(index=top_features)
all_results = []

# === Compute log2FC + MWU Test ===
for group_a, group_b in comparisons:
    log2fc_list = []
    pval_list = []
    for gene in top_features:
        data_a = log_data[log_data["Group"] == group_a][gene]
        data_b = log_data[log_data["Group"] == group_b][gene]
        stat, p = mannwhitneyu(data_a, data_b, alternative="two-sided")
        log2fc = data_a.mean() - data_b.mean()
        log2fc_list.append(log2fc)
        pval_list.append(p)
        all_results.append({
            "Biomarker": gene,
            "Comparison": f"{group_a} vs {group_b}",
            "log2FC": log2fc,
            "p-value": p
        })
    fc_matrix[f"{group_a} vs {group_b}"] = log2fc_list
    pval_matrix[f"{group_a} vs {group_b}"] = pval_list

# === Adjust p-values ===
for comp in pval_matrix.columns:
    _, fdr, _, _ = multipletests(pval_matrix[comp], method="fdr_bh")
    pval_matrix[comp] = fdr

# === Export Results ===
results_df = pd.DataFrame(all_results)
results_df["FDR"] = results_df.groupby("Comparison")["p-value"].transform(lambda p: multipletests(p, method="fdr_bh")[1])
results_df["-log10(FDR)"] = -np.log10(results_df["FDR"] + 1e-10)

results_df.to_csv("statistical_comparison_log2fc.csv", index=False)
files.download("statistical_comparison_log2fc.csv")

# === Plot Heatmap (Enhanced Style) ===
plt.figure(figsize=(6, len(top_features) * 0.35))
sns.set(style="white")

ax = sns.heatmap(
    fc_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    linewidths=0.5,
    linecolor="gray",
    annot_kws={"size": 8},  # Font size for numbers
    cbar_kws={"label": "log₂ Fold Change"}
)

# Rotate x-axis labels
ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha="right", fontsize=8)
# Adjust y-axis font size
ax.set_yticklabels(ax.get_yticklabels(), fontsize=8)

plt.tight_layout()
#plt.savefig("heatmap_log2fc_consistent_biomarkers.png", dpi=600)
plt.show()

files.download("heatmap_log2fc_consistent_biomarkers.png")

# =============================
# 📊 Signature Score Analysis (Colab)
# =============================

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import kruskal
from sklearn.decomposition import PCA
import os

# === SETUP ===
matrix_file = "/content/combined_ARG_VFDB_final_DATA.csv"
meta_file = "/content/Metadata_Aligned_VF_ARG_CountMatrix.csv"
biomarker_file = "/content/Filtered_biomarker_annotated.csv"
save_dir = "/content/signature_score_outputs"
os.makedirs(save_dir, exist_ok=True)

# === LOAD ===
df = pd.read_csv(matrix_file, index_col=0).T
df.index.name = "Sample_ID"
df.reset_index(inplace=True)

meta = pd.read_csv(meta_file)
meta["Sample_ID"] = meta["Sample_ID"].astype(str)
merged = pd.merge(df, meta, on="Sample_ID", how="inner")

biomarkers = pd.read_csv(biomarker_file)["Feature"].tolist()

# === Transform & Subset ===
log_data = merged[["Sample_ID", "Group"] + biomarkers].copy()
log_data[biomarkers] = np.log2(log_data[biomarkers] + 1)

# === Scores ===
log_data["Mean_Score"] = log_data[biomarkers].mean(axis=1)
pca = PCA(n_components=1)
log_data["PCA1_Score"] = pca.fit_transform(log_data[biomarkers])

# === Kruskal-Wallis Test ===
groups = log_data["Group"].unique()
p_mean = kruskal(*[log_data[log_data["Group"] == g]["Mean_Score"] for g in groups]).pvalue
p_pca = kruskal(*[log_data[log_data["Group"] == g]["PCA1_Score"] for g in groups]).pvalue

# === Mean Score Boxplot (High-Impact, Custom Colors, No Gridlines) ===
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(5, 4))
sns.set(style="white")  # Removed background grid

# Custom color palette for groups
group_colors = {"Healthy": "#ffcc00", "Adenoma": "#984ea3", "Cancer": "#4daf4a"}

# Boxplot with your specified colors
ax = sns.boxplot(
    data=log_data,
    x="Group",
    y="Mean_Score",
    palette=group_colors,
    linewidth=2.2,
    width=0.5,
    boxprops=dict(alpha=0.9)
)

# Overlay jittered individual points
sns.stripplot(
    data=log_data,
    x="Group",
    y="Mean_Score",
    color="black",
    alpha=0.45,
    jitter=0.25,
    size=4.5
)

# Axis labels (no title)
plt.ylabel("Mean Signature Score", fontsize=13)
plt.xlabel("Disease Group", fontsize=13)
plt.xticks(fontsize=11)
plt.yticks(fontsize=11)

# Remove gridlines
ax.grid(False)

# Thicken border spines
for spine in ax.spines.values():
    spine.set_linewidth(1.8)

plt.tight_layout()
#plt.savefig(f"{save_dir}/mean_score_boxplot_highimpact_customcolors.png", dpi=600)
plt.show()

log_data[["Sample_ID", "Group", "Mean_Score", "PCA1_Score"]].to_csv(f"{save_dir}/signature_scores.csv", index=False)

!pip install econml

# ==============================================
# Double/Debiased Machine Learning (LinearDML)
# for Ordinal Outcome using Random Forests
# (Per Species Analysis)
# ==============================================

import pandas as pd
import numpy as np
from econml.dml import LinearDML
from sklearn.ensemble import RandomForestRegressor

# -----------------------
# Step 1: Load & Format Data
# -----------------------
# Expression matrix (long format → transpose)
expr = pd.read_csv("/content/combined_ARG_VFDB_final_DATA.csv", index_col=0)
expr = expr.T  # Now rows = samples, columns = features
expr.index.name = "Sample_ID"
expr.reset_index(inplace=True)

# Metadata and selected features
meta = pd.read_csv("/content/Metadata_Aligned_VF_ARG_CountMatrix.csv")
top_species = pd.read_csv("/content/Filtered_biomarker_annotated.csv")

# -----------------------
# Step 2: Prepare for Merge
# -----------------------
species_list = top_species['Feature'].tolist()
expr_filtered = expr[['Sample_ID'] + [f for f in species_list if f in expr.columns]]

# Merge metadata and expression
meta["Sample_ID"] = meta["Sample_ID"].astype(str)
expr_filtered["Sample_ID"] = expr_filtered["Sample_ID"].astype(str)
merged = pd.merge(meta, expr_filtered, on="Sample_ID", how="inner")

# Encode labels
merged['OrdinalOutcome'] = merged['Group'].map({'Healthy': 0, 'Adenoma': 1, 'Cancer': 2})
merged['Sex'] = merged['Sex'].map({'female': 0, 'male': 1})

Y = merged['OrdinalOutcome'].values
X = merged[['Age', 'BMI', 'Sex']].values

# -----------------------
# Step 3: Causal Estimation
# -----------------------
results = []
for species in species_list:
    if species not in merged.columns:
        continue

    print(f"Estimating for species: {species}")
    T = merged[[species]].values

    dml_model = LinearDML(
        model_y=RandomForestRegressor(n_estimators=100, random_state=42),
        model_t=RandomForestRegressor(n_estimators=100, random_state=42),
        discrete_treatment=False,
        random_state=42
    )

    dml_model.fit(Y, T, X=X)
    treatment_effects = dml_model.effect(X)
    ate = np.mean(treatment_effects)
    conf_int = dml_model.effect_interval(X)

    results.append({
        'Species': species,
        'ATE': ate,
        'CI Lower': np.mean(conf_int[0]),
        'CI Upper': np.mean(conf_int[1])
    })

# -----------------------
# Step 4: Save Results
# -----------------------
results_df = pd.DataFrame(results)
print("\n✅ DML Causal Effect Estimation Completed")
print(results_df)

results_df.to_csv("DML_Causal_Effects_Per_Species.csv", index=False)
print("📁 Saved to 'DML_Causal_Effects_Per_Species.csv'")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------
# Load the DML results
# -----------------------
results_df = pd.read_csv("DML_Causal_Effects_Per_Species.csv")

# Sort species by ATE for visual clarity
results_df = results_df.sort_values(by="ATE")

# -----------------------
# Create Forest Plot
# -----------------------
plt.figure(figsize=(5, 5))
sns.set(style="white")  # Clean white background

# Error bars with bold markers
plt.errorbar(
    x=results_df['ATE'],
    y=results_df['Species'],
    xerr=[
        results_df['ATE'] - results_df['CI Lower'],
        results_df['CI Upper'] - results_df['ATE']
    ],
    fmt='o',
    color='blue',
    ecolor='gray',
    elinewidth=2.5,
    capsize=5,
    markersize=6.5,
    markeredgewidth=1.8
)

# Vertical reference line at zero
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.6)

# Labels and title
#plt.title("Causal Effects of Microbial Species on CRC Progression", fontsize=16, fontweight='bold')
plt.xlabel("ATE", fontsize=14)
#plt.ylabel("Microbial Species", fontsize=14)

# Aesthetic polish
ax = plt.gca()
ax.grid(False)  # remove grid
for spine in ax.spines.values():
    spine.set_linewidth(2)  # bold axis borders

# Layout and save
plt.tight_layout()
#plt.savefig("DML_Causal_Effects.png", dpi=600)
plt.show()

print(" Nature-level plot saved as 'Nature_Level_DML_Causal_Effects_Polished.png'")

# ==============================================
# Sensitivity Analysis for Microbial Species (E-value)
# ==============================================

import pandas as pd
import numpy as np

# Function to calculate E-value
# E-value formula from VanderWeele & Ding (2017)
def compute_evalue(estimate, lower_ci, upper_ci):
    rr = np.exp(np.abs(estimate))
    rr_ci = np.exp(np.abs(lower_ci if estimate > 0 else upper_ci))
    evalue_point = rr + np.sqrt(rr * (rr - 1))
    evalue_ci = rr_ci + np.sqrt(rr_ci * (rr_ci - 1))
    return evalue_point, evalue_ci

# -----------------------
# Load data
# -----------------------
results_df = pd.read_csv("DML_Causal_Effects_Per_Species.csv")

# Results container
evalue_results = []

# -----------------------
# Calculate E-values
# -----------------------
for idx, row in results_df.iterrows():
    ate = row['ATE']
    ci_lower = row['CI Lower']
    ci_upper = row['CI Upper']

    evalue_point, evalue_ci = compute_evalue(ate, ci_lower, ci_upper)

    evalue_results.append({
        'Species': row['Species'],
        'ATE': ate,
        'E-value (Point Estimate)': evalue_point,
        'E-value (Confidence Interval)': evalue_ci
    })

# -----------------------
# Results DataFrame
# -----------------------
evalue_df = pd.DataFrame(evalue_results)
evalue_df.sort_values(by="E-value (Point Estimate)", ascending=False, inplace=True)

print("\n=Ì Sensitivity Analysis (E-values):")
print(evalue_df)

evalue_df.to_csv("Sensitivity_Analysis_Evalues.csv", index=False)
print("\n Sensitivity analysis results saved to 'Sensitivity_Analysis_Evalues.csv'")

#-----------------------
#Load sensitivity analysis results
# -----------------------

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import matplotlib.colors as mcolors
import matplotlib.cm as cm

evalue_df = pd.read_csv("Sensitivity_Analysis_Evalues.csv")

# Replace infinite E-values with a large finite number
max_finite_evalue = evalue_df['E-value (Point Estimate)'].replace(np.inf, np.nan).max()
replacement_value = max_finite_evalue * 2.2

# Handle infinite values
plot_df = evalue_df.copy()
plot_df['E-value (Point Estimate)'] = plot_df['E-value (Point Estimate)'].replace(np.inf, replacement_value)
plot_df['Log E-value (Point Estimate)'] = np.log10(plot_df['E-value (Point Estimate)'])

# Sort for clean display
plot_df = plot_df.sort_values(by='Log E-value (Point Estimate)', ascending=True)

# Normalize for color mapping
norm = mcolors.Normalize(vmin=plot_df['Log E-value (Point Estimate)'].min(),
                         vmax=plot_df['Log E-value (Point Estimate)'].max())
cmap = plt.colormaps['coolwarm']  # updated for matplotlib e3.7
colors = cmap(norm(plot_df['Log E-value (Point Estimate)'].values))

# -----------------------
# Create bar plot
# -----------------------
fig, ax = plt.subplots(figsize=(5, 5))
sns.set(style="white")

bars = ax.barh(
    y=plot_df['Species'],
    width=plot_df['Log E-value (Point Estimate)'],
    color=colors,
    edgecolor='black',
    linewidth=2
)

# Add colorbar
sm = cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])
cbar = plt.colorbar(sm, ax=ax, orientation='vertical')
cbar.set_label("Log10 E-value (Point Estimate)", fontsize=12)

# Styling
ax.set_xlabel("Sensitivity (E-values)", fontsize=10)
ax.set_title("", fontsize=12, fontweight='bold')

ax.grid(False)
for spine in ax.spines.values():
    spine.set_linewidth(2)

plt.tight_layout()
#plt.savefig("Sensitivity_Evalue_Colorbar_Corrected.png", dpi=600, bbox_inches='tight')
plt.show()

print(" Plot saved with color scale and matplotlib 3.7+ compatibility.")

"""Bootstrap Robustness Check for Causal Estimates"""

# ==============================================
# Bootstrap Robustness Check for Causal Estimates
# ==============================================

import pandas as pd
import numpy as np
from sklearn.utils import resample
from econml.dml import LinearDML
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt
import seaborn as sns


###################################################################

# Expression matrix (long format → transpose)
expr = pd.read_csv("/content/combined_ARG_VFDB_final_DATA.csv", index_col=0)
expr = expr.T  # Now rows = samples, columns = features
expr.index.name = "Sample_ID"
expr.reset_index(inplace=True)

# Metadata and selected features
meta = pd.read_csv("/content/Metadata_Aligned_VF_ARG_CountMatrix.csv")
top_species = pd.read_csv("/content/Filtered_biomarker_annotated.csv")

# -----------------------
# Step 2: Prepare for Merge
# -----------------------
species_list = top_species['Feature'].tolist()
expr_filtered = expr[['Sample_ID'] + [f for f in species_list if f in expr.columns]]

# Merge metadata and expression
meta["Sample_ID"] = meta["Sample_ID"].astype(str)
expr_filtered["Sample_ID"] = expr_filtered["Sample_ID"].astype(str)
merged = pd.merge(meta, expr_filtered, on="Sample_ID", how="inner")

# Encode labels
merged['OrdinalOutcome'] = merged['Group'].map({'Healthy': 0, 'Adenoma': 1, 'Cancer': 2})
merged['Sex'] = merged['Sex'].map({'female': 0, 'male': 1})

Y = merged['OrdinalOutcome'].values
X = merged[['Age', 'BMI', 'Sex']].values



##########################################################
# Parameters
n_bootstraps = 100
bootstrap_results = {species: [] for species in species_list}

# Bootstrap loop
for i in range(n_bootstraps):
    print(f"Bootstrap iteration: {i+1}/{n_bootstraps}")
    boot_sample = resample(merged, replace=True, random_state=i)
    Y_boot = boot_sample['OrdinalOutcome'].values
    X_boot = boot_sample[['Age', 'BMI', 'Sex']].values

    for species in species_list:
        T_boot = boot_sample[[species]].values

        dml_model = LinearDML(
            model_y=RandomForestRegressor(n_estimators=100, random_state=42),
            model_t=RandomForestRegressor(n_estimators=100, random_state=42),
            discrete_treatment=False,
            random_state=42
        )

        dml_model.fit(Y_boot, T_boot, X=X_boot)
        ate_boot = np.mean(dml_model.effect(X_boot))
        bootstrap_results[species].append(ate_boot)

# Calculate confidence intervals
bootstrap_ci = []
for species in species_list:
    lower = np.percentile(bootstrap_results[species], 2.5)
    upper = np.percentile(bootstrap_results[species], 97.5)
    mean_ate = np.mean(bootstrap_results[species])
    bootstrap_ci.append({'Species': species, 'Mean_ATE': mean_ate, 'CI Lower': lower, 'CI Upper': upper})

bootstrap_df = pd.DataFrame(bootstrap_ci).sort_values(by='Mean_ATE')
bootstrap_df.to_csv("Bootstrap_Causal_Effects_CI.csv", index=False)
print("\n Bootstrap results saved to 'Bootstrap_Causal_Effects_CI.csv'")

"""Bootstrap Robustness plot"""

import matplotlib.pyplot as plt
import seaborn as sns

# Sort species for better readability
bootstrap_df_sorted = bootstrap_df.sort_values(by='Mean_ATE')

# Set plot aesthetics
plt.figure(figsize=(7, 6))
sns.set(style="white")

# Barplot with thick borders
sns.barplot(
    x='Mean_ATE',
    y='Species',
    data=bootstrap_df_sorted,
    palette='viridis',
    edgecolor='black',
    linewidth=2
)

# Add error bars
plt.errorbar(
    bootstrap_df_sorted['Mean_ATE'],
    bootstrap_df_sorted['Species'],
    xerr=[
        bootstrap_df_sorted['Mean_ATE'] - bootstrap_df_sorted['CI Lower'],
        bootstrap_df_sorted['CI Upper'] - bootstrap_df_sorted['Mean_ATE']
    ],
    fmt='none',
    ecolor='black',
    capsize=5,
    linewidth=2
)

# Vertical line at zero
plt.axvline(x=0, linestyle='--', color='red', linewidth=1.5)

# Labels and styling
plt.xlabel('Mean ATE (Bootstrap)', fontsize=14)
plt.ylabel('VF/ARG Genes', fontsize=14)
#plt.title('Bootstrap Robustness of Causal Effects', fontsize=16, fontweight='bold')

# Thicken plot borders
ax = plt.gca()
ax.grid(False)
for spine in ax.spines.values():
    spine.set_linewidth(2)

plt.tight_layout()
plt.savefig("Bootstrap_Robustness_Check.png", dpi=600)
plt.show()

from statsmodels.stats.power import TTestPower

# Desired power and alpha
desired_power = 0.8
alpha = 0.05
power_tool = TTestPower()

sample_size_results = []

for _, row in bootstrap_df.iterrows():
    species = row['Species']
    ate = row['Mean_ATE']
    std = np.std(bootstrap_results[species])

    if std == 0 or np.isnan(std) or ate == 0:
        required_n = np.nan
    else:
        effect_size = abs(ate / std)  # Cohen's d
        try:
            required_n = power_tool.solve_power(effect_size=effect_size, power=desired_power, alpha=alpha, alternative='two-sided')
        except:
            required_n = np.nan

    sample_size_results.append({
        'Species': species,
        'Mean_ATE': ate,
        'Std': std,
        'Required_Sample_Size': np.ceil(required_n) if not np.isnan(required_n) else np.nan
    })

# Save results
required_df = pd.DataFrame(sample_size_results).sort_values(by="Required_Sample_Size")
required_df.to_csv("Sample_Size_Required_CRC_Causal_Analysis.csv", index=False)

print("\n📊 Required sample sizes saved to: 'Sample_Size_Required_CRC_Causal_Analysis.csv'")
print(required_df.head(10))

# ================================
# 📊 Required Sample Size Plot
# ================================

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl

# === Load your data ===
df = pd.read_csv("Sample_Size_Required_CRC_Causal_Analysis.csv")

# === Sort and Filter (optional) ===
df = df.sort_values("Required_Sample_Size", ascending=True)
df_filtered = df[df["Required_Sample_Size"] <= 500]  # Show top powered genes

# === Plot Styling ===
sns.set(style="whitegrid")
mpl.rcParams.update({
    "axes.edgecolor": "black",
    "axes.linewidth": 1.5,
    "axes.labelsize": 12,
    "axes.titlesize": 14,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "legend.fontsize": 10,
    "figure.dpi": 600
})

# === Bar Plot ===
plt.figure(figsize=(6, 5))
ax = sns.barplot(
    data=df_filtered,
    x="Required_Sample_Size",
    y="Species",
    palette="viridis",
    edgecolor="black"
)

# Label threshold line
plt.axvline(x=100, color='red', linestyle='--', linewidth=1.5)
plt.text(102, 1, "N = 100", color='red', fontsize=10, va="bottom")

plt.xlabel("Estimated Required Sample Size (80% power)", fontsize=12)
plt.ylabel("Microbial Gene (ARG/VF)", fontsize=12)
#plt.title("Sample Size Needed to Detect Gene-Level Causal Effects", fontsize=14, weight='bold')

# Border polish
for spine in ax.spines.values():
    spine.set_linewidth(1.5)

plt.tight_layout()
#plt.savefig("Required_Sample_Size_CRC_Causal_Plot.png", dpi=600)
plt.show()

# ============================================
# 💡 Interaction Causal Analysis using LinearDML
# ============================================

import pandas as pd
import numpy as np
from econml.dml import LinearDML
from sklearn.ensemble import RandomForestRegressor
from itertools import combinations

# === Load Files ===
expr = pd.read_csv("/content/combined_ARG_VFDB_final_DATA.csv", index_col=0).T
expr.index.name = "Sample_ID"
expr.reset_index(inplace=True)

meta = pd.read_csv("/content/Metadata_Aligned_VF_ARG_CountMatrix.csv")
meta["Sample_ID"] = meta["Sample_ID"].astype(str)

biomarker_df = pd.read_csv("/content/Filtered_biomarker_annotated.csv")
biomarkers = biomarker_df["Feature"].dropna().unique().tolist()

# === Validate and filter features present in the matrix ===
available_features = [f for f in biomarkers if f in expr.columns]
print(f"✅ {len(available_features)} of {len(biomarkers)} features found in expression matrix.")

# === Filter expression to valid features + Sample_ID ===
expr_filtered = expr[["Sample_ID"] + available_features]
merged = pd.merge(meta, expr_filtered, on="Sample_ID", how="inner")

# === Encode outcome and confounders ===
merged['OrdinalOutcome'] = merged['Group'].map({'Healthy': 0, 'Adenoma': 1, 'Cancer': 2})
merged['Sex'] = merged['Sex'].map({'female': 0, 'male': 1})

Y = merged['OrdinalOutcome'].values
X = merged[['Age', 'BMI', 'Sex']].values

# === Loop over pairs ===
interaction_results = []

for sp1, sp2 in combinations(available_features, 2):
    print(f"🔍 Analyzing: {sp1} × {sp2}")

    merged['interaction'] = merged[sp1] * merged[sp2]
    T = merged[[sp1, sp2, 'interaction']].values

    # Causal model
    model = LinearDML(
        model_y=RandomForestRegressor(n_estimators=100, random_state=42),
        model_t=RandomForestRegressor(n_estimators=100, random_state=42),
        discrete_treatment=False,
        random_state=42
    )
    model.fit(Y, T, X=X)

    # Extract effects
    try:
        effects = model.const_marginal_effect(X)
        conf_int = model.const_marginal_effect_interval(X)

        if effects.ndim == 1:
            interaction_effect = effects[2]
            lower_ci = conf_int[0][2]
            upper_ci = conf_int[1][2]
        else:
            interaction_effect = effects[:, 2]
            lower_ci = conf_int[0][:, 2].mean()
            upper_ci = conf_int[1][:, 2].mean()

        mean_effect = np.mean(interaction_effect)

        interaction_results.append({
            'Species_1': sp1,
            'Species_2': sp2,
            'Interaction_Effect': mean_effect,
            'CI Lower': lower_ci,
            'CI Upper': upper_ci
        })

    except Exception as e:
        print(f"⚠️ Failed on {sp1} × {sp2}: {e}")
        continue

# === Save results ===
result_df = pd.DataFrame(interaction_results)
result_df = result_df.sort_values(by="Interaction_Effect", ascending=False)
result_df.to_csv("Microbial_Interaction_Effects_Corrected.csv", index=False)

print("✅ Saved to 'Microbial_Interaction_Effects_Corrected.csv'")
print(result_df.head(10))

"""Plotting of significant microbial interactions with classification (synergistic/antagonistic)"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.lines import Line2D

# Load interaction results
interaction_df = pd.read_csv("Microbial_Interaction_Effects_Corrected.csv")

# Filter significant interactions (CI excludes zero)
significant_df = interaction_df[
    (interaction_df['CI Lower'] > 0) | (interaction_df['CI Upper'] < 0)
].copy()

# Check if significant interactions exist
if significant_df.empty:
    print("⚠️ No significant interactions found based on confidence intervals.")
else:
    # Create readable interaction labels
    significant_df['Interaction Label'] = significant_df['Species_1'] + " & " + significant_df['Species_2']
    significant_df.sort_values(by="Interaction_Effect", inplace=True)

    # Assign colors based on promoting/protecting
    significant_df['Color'] = significant_df['Interaction_Effect'].apply(
        lambda x: 'red' if x > 0 else 'green'
    )

    # Start plotting
    plt.figure(figsize=(8, 6))
    sns.set(style="white")

    # Plot each interaction
    for idx, row in significant_df.iterrows():
        plt.errorbar(
            row['Interaction_Effect'],
            row['Interaction Label'],
            xerr=[[row['Interaction_Effect'] - row['CI Lower']],
                  [row['CI Upper'] - row['Interaction_Effect']]],
            fmt='o',
            ecolor='black',
            elinewidth=2,
            capsize=5,
            markersize=10,
            color=row['Color']
        )

    # Vertical line at zero
    plt.axvline(x=0, color='blue', linestyle='--', linewidth=1.5)

    # Aesthetics: thick borders, no gridlines
    ax = plt.gca()
    ax.grid(False)
    for spine in ax.spines.values():
        spine.set_linewidth(2)

    # Labels
    plt.xlabel("ATE", fontsize=14)

    # Explicit custom legend
    custom_legend = [
        Line2D([0], [0], marker='o', color='w', label='Positive interaction',
               markerfacecolor='red', markersize=10, markeredgecolor='black'),
        Line2D([0], [0], marker='o', color='w', label='Negative interaction',
               markerfacecolor='green', markersize=10, markeredgecolor='black')
    ]

    plt.legend(handles=custom_legend, title='', fontsize=9, title_fontsize=13)

    plt.tight_layout()
    plt.savefig("Significant_Microbial_Interactions_Final.png", dpi=600)
    plt.show()

    print("📊 Final plot saved as 'Significant_Microbial_Interactions_Final.png'")

import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


# === Filter Significant Interactions ===
significant_df = interaction_df[
    (interaction_df['CI Lower'] > 0) | (interaction_df['CI Upper'] < 0)
].copy()

# === Load your results ===
df = pd.read_csv("Microbial_Interaction_Effects_Corrected.csv")


# === Filter Top N Interactions ===
top_n = 50  # you can change this
df["AbsEffect"] = df["Interaction_Effect"].abs()
top_df = df.sort_values(by="AbsEffect", ascending=False).head(top_n)

# === Build Network ===
G = nx.Graph()

# Add edges with attributes
for _, row in top_df.iterrows():
    G.add_edge(
        row['Species_1'],
        row['Species_2'],
        weight=row['AbsEffect'],
        effect=row['Interaction_Effect']
    )


# -------------------------------
# Step 4: Compute Network Metrics
# -------------------------------
degree = dict(G.degree())
strength = dict(G.degree(weight='weight'))
betweenness = nx.betweenness_centrality(G, weight='weight')
closeness = nx.closeness_centrality(G)
eigenvector = nx.eigenvector_centrality_numpy(G, weight='weight')

# Compile metrics into a DataFrame
metrics_df = pd.DataFrame({
    'Node': list(G.nodes()),
    'Degree': [degree[n] for n in G.nodes()],
    'Strength': [strength[n] for n in G.nodes()],
    'Betweenness': [betweenness[n] for n in G.nodes()],
    'Closeness': [closeness[n] for n in G.nodes()],
    'Eigenvector': [eigenvector[n] for n in G.nodes()]
}).round(4)

# -------------------------------
# Step 5: Save Metrics
# -------------------------------
metrics_df.to_csv("Gene_Interaction_Network_Metrics.csv", index=False)

# -------------------------------
# Step 6: Highlight Top Hubs
# -------------------------------
top_degree = metrics_df.sort_values(by='Degree', ascending=False).head(5)
top_strength = metrics_df.sort_values(by='Strength', ascending=False).head(5)
top_betweenness = metrics_df.sort_values(by='Betweenness', ascending=False).head(5)

import networkx as nx
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib import colors as mcolors
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd


# …after you load df…
df = pd.read_csv("Microbial_Interaction_Effects_Corrected.csv")

# Filter only those interactions whose confidence interval does not cross zero
df_sig = df[(df["CI Lower"] > 0) | (df["CI Upper"] < 0)].copy()


G = nx.Graph()
for _, row in df_sig.iterrows():
    sp1, sp2 = row['Species_1'], row['Species_2']
    effect   = row['Interaction_Effect']
    G.add_edge(
        sp1, sp2,
        weight = abs(effect),
        effect = effect,
        color  = 'red' if effect > 0 else 'green'
    )

# …follow with your centrality, sizing, coloring, plotting code…

# -------------------------------
# Step 2: Build the Network Graph
# -------------------------------
G = nx.Graph()
for _, row in df_sig.iterrows():
    sp1, sp2 = row['Species_1'], row['Species_2']
    effect = row['Interaction_Effect']
    G.add_edge(
        sp1, sp2,
        weight=abs(effect),
        effect=effect,
        color='red' if effect > 0 else 'green'
    )

# -------------------------------
# Step 3: Centrality Calculations
# -------------------------------
strength = dict(G.degree(weight='weight'))
betweenness = nx.betweenness_centrality(G, weight='weight')

node_betweenness = np.array([betweenness[n] for n in G.nodes()])
max_strength = max(strength.values()) if strength else 1
node_sizes = [500 + 1500 * (strength[n] / max_strength) for n in G.nodes()]

# Color mapping (lighter for ARG_ErmF)
cmap = cm.get_cmap('YlGnBu')
norm = mcolors.Normalize(vmin=min(node_betweenness), vmax=max(node_betweenness))

node_colors = []
for n in G.nodes():
    b = betweenness[n]
    if n == "ARG_ErmF":
        # artificially reduce color intensity for visibility
        b_scaled = b * 0.4
    else:
        b_scaled = b
    rgba = cmap(norm(b_scaled))
    node_colors.append((rgba[0], rgba[1], rgba[2], 0.9))  # Add alpha

# -------------------------------
# Step 4: Network Visualization
# -------------------------------
fig, ax = plt.subplots(figsize=(8, 5))
pos = nx.spring_layout(G, k=100, seed=42)

# Draw nodes
nodes = nx.draw_networkx_nodes(
    G, pos, ax=ax,
    node_size=node_sizes,
    node_color=node_colors,
    edgecolors='black',
    linewidths=1.5
)

# Draw labels
for node, (x, y) in pos.items():
    ax.text(
        x + 0.0001, y, node,
        fontsize=8,
        fontweight='bold',
        color='black',
        ha='center',
        va='center'
    )

# Draw edges
nx.draw_networkx_edges(
    G, pos, ax=ax,
    edge_color=[d['color'] for _, _, d in G.edges(data=True)],
    width=[d['weight'] / max(df_sig['Interaction_Effect'].abs()) * 6 for _, _, d in G.edges(data=True)],
    alpha=1.0
)

# Add colorbar
sm = cm.ScalarMappable(cmap=cmap, norm=norm)
sm.set_array(node_betweenness)
cbar = plt.colorbar(sm, ax=ax, shrink=0.3)
cbar.set_label('Betweenness Centrality', fontsize=10)

# Legend for edge types
legend_elements = [
    Line2D([0], [0], color='red', lw=4.0, label='Positive interaction'),
    Line2D([0], [0], color='green', lw=4.0, label='Negative interaction')
]
ax.legend(handles=legend_elements, loc='upper right', fontsize=8, frameon=True)

# Final touches
ax.axis('off')
plt.tight_layout()
#plt.savefig("Gene_Interaction_Network_Centrality_Colored.png", dpi=600, bbox_inches='tight')
plt.show()